# Each injection: (id, file under l8/probe/crates, [(old, new, expected count)], pin filter)
INJ_ALL = [
 ("decode-from-bytes", "before/src/bits/reader.rs",
  [("Self::from_storage(bytes, bytes.len() as u64 * 8, 0)", "Self::from_storage(bytes, (bytes.len() * 8) as u64, 0)", 1)],
  "test(version_decode_crosses_the_usize_position_boundary)"),
 ("decode-live-len", "before/src/bits/reader.rs",
  [("bytes.len() as u64 * 8 - 1 - u64::from(last.trailing_zeros())", "(bytes.len() * 8) as u64 - 1 - u64::from(last.trailing_zeros())", 1)],
  "test(version_decode_crosses_the_usize_position_boundary)"),
 ("decode-padding-total", "before/src/bits/storage.rs",
  [("let total = bytes.len() as u64 * 8;", "let total = (bytes.len() * 8) as u64;", 1)],
  "test(version_decode_crosses_the_usize_position_boundary)"),
 ("compare-reader-open", "before/src/bits/reader.rs",
  [("ByteWords::new(body, tail, (position / 8) as usize)", "ByteWords::new(body, tail, (position as usize) / 8)", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
 ("compare-gamma-window", "before/src/bits/reader/gamma/window.rs",
  [("usize::try_from(position / 8).unwrap_or(usize::MAX)", "(position as usize) / 8", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
 ("join-live-usize", "before/src/bits/writer.rs",
  [("self.live += 1;", "self.live = (self.live as usize + 1) as u64;", 1),
   ("self.live += u64::from(len);", "self.live = (self.live as usize + len as usize) as u64;", 2),
   ("self.live += body.len() as u64 * 8;", "self.live = (self.live as usize + body.len() * 8) as u64;", 1)],
  "test(version_join_output_crosses_the_usize_position_boundary)"),
 ("rank-decode-frac-len", "before/src/rank.rs",
  [("groups.len() as u64 * FRACTION_GROUP_BITS - u64::from(pad)", "(groups.len() * FRACTION_GROUP_BITS as usize) as u64 - u64::from(pad)", 1)],
  "test(rank_decode_accepts_the_first_exponent_past_usize)"),
 ("rank-arith-route", "before/src/rank.rs",
  [("usize::try_from(common_exp - a_exp).is_ok() && usize::try_from(common_exp - b_exp).is_ok()", "{ let _ = (a_exp, b_exp, common_exp); true }", 1)],
  "test(rank_arithmetic_straddles_the_usize_alignment_limit)"),
 ("rank-accumulate-sign", "before/src/rank.rs",
  [("acc.sub_shifted_limbs(exp - rhs.exp, rhs.num.iter_u64_digits());", "acc.add_shifted_limbs(exp - rhs.exp, rhs.num.iter_u64_digits());", 1)],
  "test(rank_arithmetic_straddles_the_usize_alignment_limit)"),
 ("forks-count-narrow", "before/src/party/forks.rs",
  [("if let Ok(exact) = usize::try_from(count) {", "if let Ok(exact) = u64::try_from(count).map(|c| c as usize) {", 1)],
  "test(forks_accept_the_first_count_past_usize)"),
 ("suanpan-landing-narrow", "suanpan/src/accumulator.rs",
  [("usize::try_from(position)\n        .ok()", "Some(position as usize)", 1)],
  "test(suanpan_rejects_unaddressable_digit_landings)"),
]

# Trap probes: a pin that still passes never reached the guarded site with a
# position at or past 2^32.
INJ = [
 ("probe-reader-open", "before/src/bits/reader.rs",
  [("let mut reader = BufBitReader::new(ByteWords::new(body, tail, (position / 8) as usize));",
    "assert!(position < (1u64 << 32), \"L8 probe: reader opened at a position past 2^32\");\n        let mut reader = BufBitReader::new(ByteWords::new(body, tail, (position / 8) as usize));", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
 ("probe-gamma-window", "before/src/bits/reader/gamma/window.rs",
  [("let byte = usize::try_from(position / 8).unwrap_or(usize::MAX);",
    "assert!(position < (1u64 << 32), \"L8 probe: gamma window at a position past 2^32\");\n    let byte = usize::try_from(position / 8).unwrap_or(usize::MAX);", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
 ("control-reader-open", "before/src/bits/reader.rs",
  [("let mut reader = BufBitReader::new(ByteWords::new(body, tail, (position / 8) as usize));",
    "assert!(position < (1u64 << 20), \"L8 control: reader opened past 2^20\");\n        let mut reader = BufBitReader::new(ByteWords::new(body, tail, (position / 8) as usize));", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
 ("control-gamma-window", "before/src/bits/reader/gamma/window.rs",
  [("let byte = usize::try_from(position / 8).unwrap_or(usize::MAX);",
    "assert!(position < (1u64 << 20), \"L8 control: gamma window past 2^20\");\n    let byte = usize::try_from(position / 8).unwrap_or(usize::MAX);", 1)],
  "test(version_compare_crosses_the_usize_position_boundary)"),
]
