MUTS = [
  ('M01-join-no-collapse', 'src/party/join.rs',
   'built = if left_owned && matches!(built, RegionKind::Owned) {',
   'built = if false && left_owned && matches!(built, RegionKind::Owned) {'),
  ('M02-compare-pending-swap', 'src/party/compare.rs',
   '            self.pending.push(first_right);\n            self.pending.push(second_right);',
   '            self.pending.push(second_right);\n            self.pending.push(first_right);'),
  ('M03-sync-forget-b-right', 'src/party/sync.rs',
   '(Some(a), Some(b)) => a.reader().join(b.reader()).map(Self::Joined),',
   '(Some(a), Some(_b)) => Some(Self::Borrowed(a)),'),
  ('M05-forks-again-inverted', 'src/party/forks.rs',
   '            if path != extra {\n                return !path;',
   '            if path != extra {\n                return path;'),
  ('M06-remove-forget-right-sibling', 'src/party/fork/remove.rs',
   '                let sibling = if branch.has_right_child() {\n                    Sibling::Deferred',
   '                let sibling = if false && branch.has_right_child() {\n                    Sibling::Deferred'),
  ('M07-difference-disposition-swap', 'src/party/without/difference.rs',
   '            SubtreeDisposition::Discard\n        } else {\n            SubtreeDisposition::Retain',
   '            SubtreeDisposition::Retain\n        } else {\n            SubtreeDisposition::Discard'),
  ('M08-fold-drops-back', 'src/fold.rs',
   '                    uncombined.push(back);',
   '                    drop(back);'),
  ('M10-sync-all-extra-share', 'src/clock.rs',
   'let share_count = others.len() + 1;',
   'let share_count = others.len() + 2;'),
  ('M11-join-all-drops-groups', 'src/party.rs',
   '                let mut uncombined = vec![back];\n                uncombined.extend(groups);\n                return Err(uncombined);',
   '                let uncombined = vec![back];\n                drop(groups);\n                return Err(uncombined);'),
  ('M12-without-fast-path-inverted', 'src/party.rs',
   '        if self.reader().is_disjoint(other.reader()) {\n            Some(self)',
   '        if !self.reader().is_disjoint(other.reader()) {\n            Some(self)'),
  ('M13-regions-absent-right-owned', 'src/party/io/regions.rs',
   '        } else {\n            self.owned = false;\n        }\n        boundary',
   '        } else {\n            self.owned = true;\n        }\n        boundary'),
  ('M15-fork-owned-halves-swapped', 'src/party/fork.rs',
   '                keep.branch(PartyBranch::Left);\n                keep.owned();\n                give.branch(PartyBranch::Right);\n                give.owned();',
   '                keep.branch(PartyBranch::Right);\n                keep.owned();\n                give.branch(PartyBranch::Left);\n                give.owned();'),
  ('M16-select-path-skip-inverted', 'src/party/fork.rs',
   '                    if choice.is_right() {\n                        // Preorder',
   '                    if !choice.is_right() {\n                        // Preorder'),
  ('M17-sync-prefix-always-left', 'src/party/sync.rs',
   '            sync.prefix.branch(joined);',
   '            sync.prefix.branch(PartyBranch::Left);'),
  ('M18-clock-join-all-drops-version', 'src/clock.rs',
   '            Err(other_party) => Err(Clock::from_parts(other_party, other_version)),',
   '            Err(other_party) => Err(Clock::from_parts(other_party, Version::new())),'),
]
