//! The supply-run batching contract: byte-budget chunking at the encoder.
//!
//! The decoder accepts any batching (its record loop is chunking-agnostic),
//! so every law here is stated against the *encoder*: records accumulate
//! greedily until the frame's wire size — the [`SUPPLY_FRAME_OVERHEAD`]
//! envelope plus the run body — would outgrow the [`RunBudget`], a run never
//! dips below one record, and a run never spans reactions. Round trips are
//! asserted through the same
//! decode → re-encode path the session uses, with the decode side fed
//! deliberately unbatched input to prove batching is the encoder's choice.

use std::collections::BTreeMap;

use futures::{TryStreamExt, stream};
use proptest::prelude::*;

use crate::{
    Version,
    message::Message,
    tree::{
        mirror::streaming::{
            Backend, Local,
            message::Reaction,
            remote::codec::{
                DEFAULT_TARGET_MESSAGE_SIZE, Flow, Frame, LeafRun, Reaction as WireReaction,
                RunBudget, SUPPLY_FRAME_OVERHEAD,
            },
        },
        typed::{
            Prefix,
            height::{UnderRoot, UnderUnderRoot},
        },
    },
};

use super::{
    super::{Scope, decode_reply, encode_reply},
    LeafCase, leaf_run, runtime,
};

/// Inclusive bound on leaves per generated run scenario.
const MAX_CASE_LEAVES: usize = 10;

/// Upper envelope on one encoded `u64` leaf record here: a 4-byte header,
/// a version of at most two bytes, and the fixed 8-byte payload.
const MAX_RECORD_LEN: usize = 14;

/// Exclusive bound on generated byte budgets: past every record and past a
/// whole case's run with its frame envelope, so the sweep covers zero,
/// sub-record, mid-run, and run-swallowing budgets.
const MAX_CASE_BUDGET: usize = (MAX_CASE_LEAVES + 1) * MAX_RECORD_LEN + SUPPLY_FRAME_OVERHEAD;

/// The first `count` leaves (in path order) whose content paths collide in
/// their leading byte, so all of them live under one supplied subtree.
fn colliding_leaves(count: usize) -> Vec<LeafCase> {
    let mut by_radix: BTreeMap<u8, Vec<LeafCase>> = BTreeMap::new();
    for value in 0..u64::MAX {
        let leaf = LeafCase::new(value, value as u8 % 4);
        let bytes: [u8; 32] = leaf.path().into();
        let group = by_radix.entry(bytes[0]).or_default();
        group.push(leaf);
        if group.len() == count {
            let mut group = group.clone();
            group.sort_by_key(LeafCase::path);
            return group;
        }
    }
    unreachable!("the finite radix alphabet forces {count} collisions")
}

/// Two leaves whose content paths *differ* in their leading byte, so they
/// decode into two distinct supply reactions.
fn separated_leaves() -> [LeafCase; 2] {
    let first = LeafCase::new(0, 0);
    let first_bytes: [u8; 32] = first.path().into();
    for value in 1..u64::MAX {
        let leaf = LeafCase::new(value, value as u8 % 4);
        let bytes: [u8; 32] = leaf.path().into();
        if bytes[0] != first_bytes[0] {
            let mut pair = [first.clone(), leaf];
            pair.sort_by_key(LeafCase::path);
            return pair;
        }
    }
    unreachable!("content paths are not all equal in their leading byte")
}

/// One single-record supply frame per leaf: the least-batched wire form.
fn unbatched_frames(leaves: &[LeafCase]) -> Vec<Frame<u64>> {
    let count = leaves.len();
    leaves
        .iter()
        .enumerate()
        .map(|(position, leaf)| {
            let flow = if position + 1 == count {
                Flow::End
            } else {
                Flow::Continue
            };
            Frame::Reaction(
                WireReaction::Supply(leaf_run(&[(&leaf.version, &leaf.message)])),
                flow,
            )
        })
        .collect()
}

/// Decode `frames` as one reply to the opening scope, then re-encode it
/// under `budget`, returning the emitted wire frames.
fn recode(frames: Vec<Frame<u64>>, budget: RunBudget) -> Vec<Frame<u64>> {
    let runtime = runtime();
    runtime.block_on(async {
        let mut input = stream::iter(frames);
        let decoded = decode_reply::<Local, u64, UnderUnderRoot, _>(
            Local,
            Scope::<UnderRoot>::opening(&[]),
            &mut input,
        )
        .await
        .expect("ascending in-scope leaves assemble");
        encode_reply(Local, budget, Scope::opening(&[]), decoded.reply)
            .map_ok(|encoded| encoded.into_parts().0)
            .try_collect::<Vec<_>>()
            .await
            .expect("the local backend is infallible")
    })
}

/// Split every emitted frame into its supply run, requiring supplies only.
fn runs_of(frames: &[Frame<u64>]) -> Vec<&LeafRun<u64>> {
    frames
        .iter()
        .map(|frame| match frame {
            Frame::Reaction(WireReaction::Supply(run), _) => run,
            other => panic!("a pure-supply reply emitted {other:?}"),
        })
        .collect()
}

/// The decoded records of `runs`, flattened in wire order.
fn records_of(runs: &[&LeafRun<u64>]) -> Vec<(Version, Message<u64>)> {
    runs.iter()
        .flat_map(|run| {
            run.records()
                .collect::<Result<Vec<_>, _>>()
                .expect("an encoder-produced run holds canonical records")
        })
        .collect()
}

proptest! {
    /// For any budget, one reaction's leaves chunk greedily into runs.
    ///
    /// Records accumulate in path order until the next would push the
    /// frame's wire size (envelope plus run body) past the budget; every
    /// run flushed early is full (its successor's first record would not
    /// have fit); no run is empty; only a lone record may push a frame past
    /// the budget. Decoding the chunked frames reproduces the exact leaves,
    /// so chunking is invisible above the wire.
    #[test]
    fn supply_runs_chunk_greedily_by_bytes(
        count in 1..=MAX_CASE_LEAVES,
        budget in 0..MAX_CASE_BUDGET,
    ) {
        let leaves = colliding_leaves(count);
        let frames = recode(unbatched_frames(&leaves), RunBudget::from_bytes(budget));

        // Every frame is a supply run; the reply boundary sits on the last.
        for (position, frame) in frames.iter().enumerate() {
            let expected = if position + 1 == frames.len() {
                Flow::End
            } else {
                Flow::Continue
            };
            prop_assert!(
                matches!(frame, Frame::Reaction(_, flow) if *flow == expected),
                "frame {position} carries the wrong flow"
            );
        }

        let runs = runs_of(&frames);
        for (position, run) in runs.iter().enumerate() {
            let records = run.record_count();
            prop_assert!(records >= 1, "run {position} is empty");
            // The budget bounds the whole wire frame, not just the run body.
            prop_assert!(
                SUPPLY_FRAME_OVERHEAD + run.encoded_len() <= budget || records == 1,
                "run {position} exceeds the budget with {records} records"
            );
            // Greedy: a non-final run flushed only because the next record
            // would have pushed its frame past the budget.
            if position + 1 < runs.len() {
                let (version, message) = runs[position + 1]
                    .records()
                    .next()
                    .expect("a nonempty run yields a first record")
                    .expect("an encoder-produced run holds canonical records");
                prop_assert!(
                    SUPPLY_FRAME_OVERHEAD
                        + run.encoded_len()
                        + LeafRun::record_len(&version, &message)
                        > budget,
                    "run {position} flushed although the next record fit"
                );
            }
        }

        // Chunking loses nothing and reorders nothing.
        let records = records_of(&runs);
        prop_assert_eq!(records.len(), leaves.len());
        for (record, leaf) in records.iter().zip(&leaves) {
            prop_assert_eq!(record.0.as_bytes(), leaf.version.as_bytes());
            prop_assert_eq!(record.1.as_slice(), leaf.message.as_slice());
        }
    }
}

/// A single record larger than the budget ships alone in its own run,
/// exceeding the budget: the minimum-one-record rule keeps every leaf
/// shippable under any setting, including a zero budget.
#[test]
fn an_oversized_record_ships_alone() {
    let leaves = colliding_leaves(3);
    let frames = recode(unbatched_frames(&leaves), RunBudget::from_bytes(0));

    let runs = runs_of(&frames);
    assert_eq!(runs.len(), leaves.len(), "each record rides its own run");
    for run in &runs {
        assert_eq!(run.record_count(), 1);
        assert!(
            run.encoded_len() > 0,
            "a lone record still exceeds budget 0"
        );
    }
    assert_eq!(records_of(&runs).len(), leaves.len());
}

/// Runs never span reactions: two supplied subtrees whose records would
/// comfortably share one run still ship as two runs, because batching scope
/// is one reaction's leaf enumeration.
#[test]
fn runs_never_span_reactions() {
    let leaves = separated_leaves();
    let frames = recode(
        unbatched_frames(&leaves),
        RunBudget::from_bytes(DEFAULT_TARGET_MESSAGE_SIZE),
    );

    let runs = runs_of(&frames);
    assert_eq!(runs.len(), 2, "two reactions must emit two runs");
    for run in &runs {
        assert_eq!(run.record_count(), 1);
    }
}

/// The re-encoded reply of a multi-leaf reaction under the default budget
/// is one batched frame whose decode reproduces the protocol reply
/// exactly: the round trip is lossless through the batched form.
#[test]
fn a_batched_run_round_trips_the_reply() {
    let leaves = colliding_leaves(4);
    let frames = recode(unbatched_frames(&leaves), RunBudget::default());
    assert_eq!(frames.len(), 1, "one reaction batches into one frame");

    let runtime = runtime();
    let reply = runtime.block_on(async {
        let mut input = stream::iter(frames);
        decode_reply::<Local, u64, UnderUnderRoot, _>(
            Local,
            Scope::<UnderRoot>::opening(&[]),
            &mut input,
        )
        .await
        .expect("the batched frame decodes")
        .reply
    });
    let [Reaction::Supply(_, node)] = reply.replies.as_slice() else {
        panic!("one batched run must decode to one supplied node");
    };
    let prefix = Prefix::<UnderRoot>::containing(&leaves[0].path());
    let rebuilt = runtime.block_on(async {
        Local
            .leaves(prefix, node.clone())
            .try_collect::<Vec<_>>()
            .await
            .expect("the local backend is infallible")
    });
    assert_eq!(rebuilt.len(), leaves.len());
}
