#import "fig.typ": *

= Compactness: the coding against the counting floor <compactness>

@skyline claimed the coding is compact and paid $4.3%$ for
canonicality. This section makes both halves precise. The question
"how far is this representation from the information-theoretic
minimum?" has no answer until one names the set being counted, so we
begin there, and we end with the caveat that keeps the headline
number honest.

== The framing <ctf>

For each $n$, let $cal(F)(n)$ be the family of versions whose
canonical stream fits in $n$ bits, and let
$H(n) = log_2 |cal(F)(n)|$. _Any_ injective assignment of bit
strings to the members of $cal(F)(n)$ — ours, or the best
conceivable replacement, prefix-free or not — must give some member
at least $ceil(H(n))$ bits: fewer than $2^(H(n))$ distinct strings
are shorter than that, and there are $2^(H(n))$ members to name.
Our coding spends at most $n$ on every member, by definition of
$cal(F)(n)$. So the
_worst-case multiplicative overhead_ of the coding, against a floor
that any competitor also faces on the same set, is

$ n / H(n), $

and the statement holds at every $n$ simultaneously — there is no
cherry-picked operating point. Note precisely what kind of claim
this is: worst case against worst case — our longest spelling on
$cal(F)(n)$ against the longest spelling any coding must have on
$cal(F)(n)$ — not a bound on any particular version's cost, and not
an average. This is the standard competitive framing for universal
codes, and its self-referential flavor (the
coding's own reach defines the set) is both its strength — no
external model of "likely versions" is smuggled in — and the source
of the honest caveat in @ctf-caveat.

Because canonical streams are in bijection with versions (@canonical:
one string per value), counting streams of at most $n$ bits _is_
counting versions, and the whole question reduces to: _how many
canonical streams are there?_

== Counting canonical streams <census>

The stream grammar is small enough to count exactly. A stream is a
full binary tree in preorder; each leaf carries a gamma-coded
payload; a leaf that is the _right sibling of a leaf_ may not carry
payload zero (the sibling-merge rule, @canonical); the tree must be
complete with no trailing bits. Set nonnegativity aside for a
moment — @nonneg prices it separately.

Count with generating functions in a formal variable $x$ marking
bits. The payload code puts $2^k$ values at cost exactly $2k + 1$
bits (the values $v$ with $floor(log_2 (v + 1)) = k$), so the values
by code length are generated by

$ G(x) = sum_(k >= 0) 2^k x^(2k + 1) = x / (1 - 2 x^2). $

A leaf is a flag bit plus a payload: $A = x G$. A leaf sitting as the
right sibling of another leaf excludes the 1-bit zero code:
$A' = x (G - x)$. An internal node is a flag bit plus two children,
with the exclusion binding exactly when both children are leaves:

$ B = x (A A' + A B + B A + B B), quad V = A + B $

($V$ generating all canonical streams). In standard form the
equation for $B$ is the quadratic

$ x B^2 + (2 x A - 1) B + x A A' = 0, $

and the count of $n$-bit streams grows as the reciprocal of the
dominant singularity: the branch point where the discriminant

$ Delta(x) = (1 - 2 x A)^2 - 4 x^2 A A' $

vanishes. Substituting $A$ and $A'$ and clearing denominators,
$Delta = 0$ reduces to $(1 - 2 x^2 - 2 x^3)^2 = 8 x^8$, whose two
sign branches give two quartics; the one shown,

$ 1 - 2 x^2 - 2 x^3 - 2 sqrt(2) x^4 = 0, $

carries the smaller positive root and hence the operative
singularity, $x_c = 0.514500dots$ — safely inside $G$'s own radius of
convergence $1 \/ sqrt(2)$, so the branch point governs. By the
standard transfer for square-root singularities, the number of
exactly-$n$-bit canonical streams is $Theta(2^(alpha n) n^(-3\/2))$
with

$ alpha = log_2 (1 / x_c) = 0.958757dots, $

hence — summing over lengths up to $n$ changes nothing, since the
series is geometrically dominated by its last terms — the
sibling-merge-only grammar counts
$H_0 (n) = alpha n - 3/2 log_2 n + O(1)$ bits of choice. The true
$H(n)$ subtracts nonnegativity's further $Theta(log n)$-bit pruning
(@nonneg prices it: about three more bits at $n = 800$), which
changes nothing at the asymptote:

$ n / H(n) --> 1 / alpha = 1.043017dots $

*The coding sits within $4.3%$ of the information-theoretic floor,
asymptotically.* (Derived; in our implementation the closed form is
additionally cross-checked against an exact census of the grammar —
a dynamic program over stream lengths, itself cross-pinned against
brute-force enumeration of every bit string at small lengths — and
agrees to hundredths of a bit at $n = 800$.)

== The asymptotic tax is the sibling-merge rule, all of it <tax>

Where do the $4.3%$ go? Run the same computation with the
sibling-merge rule deleted — every leaf free to carry zero. The payload code
satisfies Kraft's equality:

$ sum_(k >= 0) 2^k dot 2^(-(2k + 1)) = sum_(k >= 0) 2^(-(k+1)) = 1, $

and the topology flag is a complete 1-bit code, so the unconstrained
composite is _prefix-complete_: every infinite bit string begins with
exactly one well-formed stream — no coding room is wasted at all.
Concretely, the unconstrained characteristic equation
$1 - 2 x^2 - 4 x^3 = 0$ has its root at exactly $x = 1\/2$: growth
$2^n$, zero asymptotic redundancy.

So the entire asymptotic gap is the set of strings the sibling-merge
rule _refuses_: spellings with a collapsible pair, excised so that
each value would have one spelling. (The other canonical rules are
priced separately: nonnegativity in @nonneg, at $Theta(log n)$ bits;
exactness for free.) The $4.3%$ is not overhead lost to a clumsy
code — the code is Kraft-tight — it is the measured price of "byte
equality is value equality," bought once, on purpose, and enjoyed by
every comparison, hash, and deduplication the system ever performs
(@canonical). Design decisions rarely come with a price tag this
exact.

== Nonnegativity is asymptotically free <nonneg>

The remaining canonical rule — no delta may drive the running height
negative — prunes more strings, but only polynomially many. The
zigzag map puts $+m$ and $-m$ in the same gamma bucket (they could
split only if the bucket boundary sat between them — that is, if
$2m + 1$ were itself a power of two, which no odd number above one
is), so under the uniform
counting measure on streams of a given length the height walk's
steps behave as draws from a sign-symmetric distribution; for such
walks, the probability that all $ell$ partial sums stay nonnegative
is $Theta(ell^(-1\/2))$ (Sparre–Andersen-type universality). A
polynomial factor does not move the exponential growth rate, so
$alpha$ is untouched; the effect on $H$ is $Theta(log n)$ bits. This
is the section's one probabilistic step — the second of the
introduction's three boundaries — and it is heuristic in two honest
respects: the steps share a total bit budget, so they are only
approximately independent draws; and they are lattice-valued with an
atom at zero, so the $ell^(-1\/2)$ _rate_ is the universality
statement rather than the exact fluctuation identity. We lean on it solely for the
asymptotic rate; the finite-$n$ numbers below come from exact
bracketing counts that do not touch it, and the census corroborates
the rate directly (about three bits of $H$ at $n = 800$, growing
logarithmically).

== Finite sizes <finite>

Asymptotics flatter every code; a version is typically tens to a few
hundred bytes. The exact census machinery gives the finite-$n$
picture (bracketed by rigorous over- and under-counting families
where the exact count is out of computational reach):

#figure(
  table(
    columns: (auto, auto, auto),
    align: (left, right, right),
    stroke: 0.4pt + gray-line,
    inset: 6pt,
    table.header([*stream budget*], [*bits* $n$], [*overhead* $n \/ H(n)$]),
    [50 bytes], [400], [$1.0863 dash 1.0865$],
    [100 bytes], [800], [$1.0669 dash 1.0673$],
    [200 bytes], [1600], [$approx 1.056$],
    [2 kilobytes], [16 384], [$approx 1.045$],
    [asymptotic], [—], [$1.043017$],
  ),
  caption: [Worst-case overhead against the counting floor, by stream
    size. Rows quoted as ranges are rigorously bracketed by the over-
    and under-counting families; the "$approx$" rows extrapolate by
    the validated closed form, beyond the brackets' computational
    reach. At 100 bytes — a realistic version under heavy history —
    the coding is within $6.7%$ of the floor: $4.3$ points of
    sibling-merge tax, about $2.0$ of universal finite-size effect
    (the $(3\/2) log_2 n$ term every maximal code pays), and about
    $0.4$ of nonnegativity tax.],
) <fig-overhead>

== The caveat that keeps the number honest <ctf-caveat>

The floor above is relative to the family the coding itself reaches.
Choose a different, natural-sounding family — versions with $ell$
plateaus and heights drawn uniformly below $2^w$ — and the same
coding fares differently: the family needs about $ell (w + 2)$ bits
of entropy, while gamma's worst case spends $2w + 1$ bits per
payload, a ratio approaching $2$ as $w$ grows. Same coding, same
definition of floor, different family, different verdict. Any
published form of the $4.3%$ claim must carry its family, and this
one does.

Why accept a code with that exposure? Because the alternative is
worse where it matters. Integer codes exist whose counting overhead
is exactly $1 times$ asymptotically — Elias delta and omega. That
sounds like it contradicts @tax (gamma is Kraft-complete too; the
tax was "all canonicality"), so the reconciliation deserves a
sentence. The sibling-merge pruning is the same rule under any
payload code; what differs is _where each code's counting mass
lives_. Gamma prices a value near $2^c$ at about $2c$ bits, so its
capacity-achieving streams are leaf-rich with modest payloads — and
a per-sibling-pair exclusion bites a constant fraction of the
choices at a constant fraction of the nodes. Delta prices the same
value at $c + O(log c)$, so its counting mass concentrates on
few-leaf, giant-payload streams, where sibling pairs — the only
thing pruned — are vanishingly rare. Formally: delta's and omega's
generating functions are themselves critical exactly at $x = 1\/2$,
and on $(0, 1\/2]$ the discriminant stays positive (at $x = 1\/2$
it evaluates to $1\/8$ — as it does for gamma, whose $G$ however
survives out to $1\/sqrt(2)$, giving its discriminant the room to
reach zero at $0.5145$ that delta's and omega's, expiring at
$1\/2$, never get), so no branch point forms below the code's own
singularity and $alpha = 1$: the pruning never becomes the binding
constraint.

The catch is where those codes win: the versions delta covers more
cheaply are exactly the few-plateau, giant-payload ones, and it pays
pointwise on small values — comparing coded payloads $v$ (each code
spells $v + 1$), gamma is better than or equal to delta on every
$v$ up to 30 and loses ground steadily from $v = 31$ on, while
omega does not overtake gamma until values in the hundreds.
Measured across organic gossip
histories (the paper's own two simulation regimes — data churn and
static message passing — replayed at scale on our implementation,
some 165,000 versions), 85 to 93 percent of payload values are at
most 15
(`fill`'s flattening, not the coding, is what keeps neighboring
plateaus close — @coding), and re-coding those corpora under delta
or omega costs six
to nine percent _more_ total bytes — the workload number that
settles the bet the counting metric alone cannot. The $4.3%$
counting tax and the factor-2 exposure on uniformly-wide families
are the deliberate price of logarithmic cost on the deltas the
system actually produces. A compactness claim is a bet about
workloads; this section states the bet's terms and the measured
reason to take it.
