//! Checks the adversarial families used by the resource meters.
//!
//! Each property ranges over a generator's valid inputs, verifies its
//! closed-form size and canonical encoding, and checks the semantic premise on
//! which the corresponding resource measurement relies.

use crate::{Count, Party, Rank, Version};

use num_bigint::BigUint;
use proptest::prelude::*;

use super::{
    alt_spine, arming_train, ascend_cliff, ascend_cliff_plateau, bigroot, bitlen, cancelling_chain,
    cliff_comb, cliff_fan, collapse_hole, concurrent_pair, copy_hole, dense, dense_suffix,
    dense_suffix_mate, dominated_undercut, dominated_undercut_id, freeze_parade, freeze_position,
    harmonic, hoisted_window, hugeleaf, id_spine, jump_comb, jump_pair, latent_ladder, lone_freeze,
    mask_drift_quadruple, mask_drift_triple, masked_hole, plateau_puncture,
    plateau_puncture_factors, promotion_rearm, promotion_rearm_mate, raise_hole, scattered_id,
    seam_plunge, seam_plunge_control, seam_stop, seam_stop_control, site_hole, tooth_tail,
    weight_comb, wide_arming, wide_tooth_comb, Encoding, FREEZE_DRIFT_BITS,
    PROMOTION_REARM_ARM_BITS,
};

/// Appended to the counter-comparison failures: the first cause to rule out is
/// a shared-process test runner, under which the process-global counters bleed
/// other tests' work into the reading being compared.
#[cfg(feature = "scan-meter")]
const ISOLATION_NOTE: &str = "note: the counter is process-global and meaningful only one \
     test per process: run under cargo nextest, not a shared-process cargo test";

/// Convert an arbitrary-precision expected result into a minimum tick count.
fn min_ticks_from_big(value: &BigUint) -> Count {
    Count(value.clone())
}

/// Build a uniform version through the public tick operation.
fn uniform(count: impl Into<Count>) -> Version {
    let mut version = Version::new();
    Party::seed().ticks(&mut version, count);
    version
}

/// Check an event-shape output: the construction stream has exactly the
/// closed-form `bits`, and it lifts through the transcoding bridge into a
/// version that survives a wire round-trip (canonicality of both codings).
fn check_version(p: &Encoding, bits: usize) {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let v = p.version();
    let wire = v.encode();
    let back = Version::decode(&wire[..]).expect("a stored version's wire bytes decode");
    assert_eq!(back, v, "wire round-trip");
    assert_eq!(back.encode(), wire, "byte-identical re-encode");
}

/// Check an id-shape output: `decode` accepts it, the decoded party re-encodes
/// to the generated bytes (canonicality), and the live bit length is exactly
/// `bits`.
fn check_party(p: &Encoding, bits: usize) -> Party {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let id = Party::decode(&p.bytes[..]).expect("generated shape is strict normal form");
    assert_eq!(id.encoded_bits(), p.bits as u64, "decoded live bit length");
    assert_eq!(id.encode(), p.bytes, "byte-identical re-encode");
    id
}

proptest! {
    /// The dense spine `S(d)` is canonical normal form at exactly `4d + 4`
    /// bits for every positive depth.
    #[test]
    fn dense_decodes_canonically_at_predicted_length(d in 1usize..=1_000) {
        check_version(&dense(d), 4 * d + 4);
    }

    /// `bigroot(b, d)` is canonical normal form at exactly `2b + 4d + 8` bits,
    /// across narrow and multiword root magnitudes.
    #[test]
    fn bigroot_decodes_canonically_at_predicted_length(
        b in prop_oneof![1usize..=128, Just(200usize)],
        d in 1usize..=64,
    ) {
        check_version(&bigroot(b, d), 2 * b + 4 * d + 8);
    }

    /// `hugeleaf(b)` is canonical normal form at exactly `2b + 2` bits across
    /// narrow and multiword magnitudes.
    #[test]
    fn hugeleaf_decodes_canonically_at_predicted_length(
        b in prop_oneof![1usize..=128, Just(200usize)],
    ) {
        check_version(&hugeleaf(b), 2 * b + 2);
    }

    /// `cliff_comb(k, n)` is canonical normal form at exactly
    /// `n(2k + 10) + 2` bits for every admitted tooth width and count.
    #[test]
    fn cliff_comb_decodes_canonically_at_predicted_length(
        k in prop_oneof![1usize..=128, Just(200usize)],
        n in 1usize..=50,
    ) {
        check_version(&cliff_comb(k, n), n * (2 * k + 10) + 2);
    }

    /// `jump_comb(k, n)` is canonical normal form at exactly
    /// `(n − 1)(2k + 10) + 14` bits for every admitted width and count.
    #[test]
    fn jump_comb_decodes_canonically_at_predicted_length(
        k in prop_oneof![1usize..=128, Just(200usize)],
        n in 2usize..=50,
    ) {
        check_version(&jump_comb(k, n), (n - 1) * (2 * k + 10) + 14);
    }

    /// `wide_tooth_comb(k, w, n)` is canonical normal form at exactly
    /// `n(2k + 2w + 6) + 2` bits throughout its three-dimensional domain.
    #[test]
    fn wide_tooth_comb_decodes_canonically_at_predicted_length(
        widths in (1usize..=100, 1usize..=100),
        n in 1usize..=32,
    ) {
        let (w, above) = widths;
        let k = w + above;
        check_version(&wide_tooth_comb(k, w, n), n * (2 * k + 2 * w + 6) + 2);
    }

    /// `cliff_fan(k, n)` is canonical normal form at exactly
    /// `12n + 2k + 6` bits throughout its domain.
    #[test]
    fn cliff_fan_decodes_canonically_at_predicted_length(
        k in prop_oneof![1usize..=128, Just(200usize)],
        n in 1usize..=50,
    ) {
        check_version(&cliff_fan(k, n), 12 * n + 2 * k + 6);
    }

    /// `cancelling_chain(k, n)` is canonical normal form at exactly
    /// `n(2k + 10) + 2` bits throughout its domain.
    #[test]
    fn cancelling_chain_decodes_canonically_at_predicted_length(
        k in prop_oneof![1usize..=128, Just(200usize)],
        n in 1usize..=50,
    ) {
        check_version(&cancelling_chain(k, n), n * (2 * k + 10) + 2);
    }
}

proptest! {
    /// `freeze_position(k)` is canonical normal form at exactly
    /// `4k(L + 2) + 2` bits for `L = P + 1 + bitlen(k)`, and its `min_ticks`
    /// equals `2k·2^L + k(k−1)(2^P + 1) + k`, where `P` is
    /// [`FREEZE_DRIFT_BITS`].
    #[test]
    fn freeze_position_decodes_canonically_at_predicted_length(
        k in prop_oneof![1usize..=64, Just(200usize)],
    ) {
        let band = FREEZE_DRIFT_BITS + 1 + bitlen(k);
        check_version(&freeze_position(k), 4 * k * (band + 2) + 2);
        let expected = (BigUint::from(2 * k as u64) << band)
            + BigUint::from((k * (k - 1)) as u64)
                * ((BigUint::ONE << FREEZE_DRIFT_BITS) + BigUint::ONE)
            + BigUint::from(k as u64);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            freeze_position(k).version().min_ticks(),
            ticks,
            "the leaf-sum closed form is the family's minimum tick count"
        );
    }

    /// `promotion_rearm(p)` is canonical normal form at exactly `(2A + 2P +
    /// 180)p + 4` bits, where `A` is [`PROMOTION_REARM_ARM_BITS`] and `P` is
    /// [`FREEZE_DRIFT_BITS`].
    ///
    /// Its `min_ticks` is exactly the stored-base sum `16p + p(2^A + 2^P + 2) +
    /// 1`.
    ///
    /// The closed form is the family's independent semantic leg: the
    /// `skyline_flatness` bands in `tests/meter.rs` re-derive it at meter scale, so
    /// this pin holds it at hand-checkable sizes.
    #[test]
    fn promotion_rearm_decodes_canonically_at_predicted_length(
        p in prop_oneof![1usize..=64, Just(200usize)],
    ) {
        check_version(
            &promotion_rearm(p),
            (2 * PROMOTION_REARM_ARM_BITS + 2 * FREEZE_DRIFT_BITS + 180) * p + 4,
        );
        let expected = BigUint::from(16 * p as u64)
            + BigUint::from(p as u64)
                * ((BigUint::ONE << PROMOTION_REARM_ARM_BITS)
                    + (BigUint::ONE << FREEZE_DRIFT_BITS)
                    + 2u8)
            + 1u8;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            promotion_rearm(p).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `lone_freeze(pre, post)` is canonical normal form at exactly `(2P +
    /// 4)·pre + 6·post + 14` bits, and its `min_ticks` is exactly the leaf-sum
    /// closed form `pre·(2^P + 2) + pre/2 + 3·post/2 + 3`.
    ///
    /// Here `P` is [`FREEZE_DRIFT_BITS`].
    ///
    /// The closed form is the family's independent semantic leg: the
    /// `skyline_flatness` bands in `tests/meter.rs` re-derive it at meter scale on
    /// both dials, so this pin holds it at hand-checkable sizes where the tree can
    /// also be spot-read (a plateau pair, the drop block, a tail pair, the terminal
    /// zero).
    #[test]
    fn lone_freeze_decodes_canonically_at_predicted_length(
        pre_pairs in 1usize..=20,
        post_pairs in 1usize..=20,
    ) {
        let (pre, post) = (2 * pre_pairs, 2 * post_pairs);
        check_version(
            &lone_freeze(pre, post),
            (2 * FREEZE_DRIFT_BITS + 4) * pre + 6 * post + 14,
        );
        let expected = BigUint::from(pre as u64)
            * ((BigUint::ONE << FREEZE_DRIFT_BITS) + BigUint::from(2u8))
            + BigUint::from((pre / 2) as u64)
            + BigUint::from((3 * post / 2) as u64)
            + BigUint::from(3u8);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            lone_freeze(pre, post).version().min_ticks(),
            ticks,
            "the leaf-sum closed form is the family's minimum tick count"
        );
    }

    /// `promotion_rearm_mate(p)` is canonical normal form at exactly `180p + 4`
    /// bits.
    ///
    /// Its `min_ticks` is exactly `18p + 1`, and `promotion_rearm(p)` dominates it
    /// pointwise (the pair band's exact value legs rest on the dominance).
    #[test]
    fn promotion_rearm_mate_decodes_canonically_at_predicted_length(
        p in prop_oneof![1usize..=64, Just(200usize)],
    ) {
        check_version(&promotion_rearm_mate(p), 180 * p + 4);
        let ticks = Count::from(18 * p as u64 + 1);
        assert_eq!(
            promotion_rearm_mate(p).version().min_ticks(),
            ticks,
            "the alternating spine's stored-base sum is its minimum tick count"
        );
    }
}

/// The harmonic spine's rank is exactly `(2^d − 1)/2^d` at representative
/// shallow and deep boundaries.
///
/// The general canonical-length property is checked separately. This test pins
/// the rank through readable text and, at meter scale, through
/// `1 − rank(H(d)) = 1/2^d`.
#[test]
fn harmonic_rank_matches_its_closed_form_at_boundaries() {
    assert_eq!(harmonic(2).version().rank().to_string(), "0.11");
    assert_eq!(harmonic(7).version().rank().to_string(), "0.1111111");
    // Meter scale: 1 − (2^d − 1)/2^d = 1/2^d, exact at any depth.
    let d = 4_096;
    let h = harmonic(d).version().rank();
    let one = uniform(1u8).rank();
    let gap = one
        .checked_sub(&h)
        .expect("H(d)'s rank is strictly under the unit rank");
    assert_eq!(gap.to_string(), format!("0.{}1", "0".repeat(d - 1)));
}

proptest! {
    /// `H(d)` is canonical normal form at exactly `6d + 2` bits for every
    /// positive depth.
    #[test]
    fn harmonic_decodes_canonically_at_predicted_length(d in 1usize..=1_000) {
        check_version(&harmonic(d), 6 * d + 2);
    }

    /// `A(d)` is canonical normal form at exactly `4d + 4` bits, with both
    /// alternation parities exercised across arbitrary positive depths.
    #[test]
    fn alt_spine_decodes_canonically_at_predicted_length(d in 1usize..=1_000) {
        check_version(&alt_spine(d), 4 * d + 4);
    }

    /// `dominated_undercut(k, b)` is canonical normal form at exactly
    /// `k(2b + 26) + 2` bits throughout its admitted width and site domain.
    #[test]
    fn dominated_undercut_decodes_canonically_at_predicted_length(
        k in 1usize..=50,
        b in 128usize..=200,
    ) {
        check_version(&dominated_undercut(k, b), k * (2 * b + 26) + 2);
    }

    /// `dominated_undercut_id(k)` is canonical normal form at exactly
    /// `6k + 2` bits throughout its positive site-count domain.
    #[test]
    fn dominated_undercut_id_decodes_canonically_at_predicted_length(k in 1usize..=100) {
        let _ = check_party(&dominated_undercut_id(k), 6 * k + 2);
    }
}

/// The scan meter observes encoded traversal, resets to zero, and reads
/// the same count for the same operation repeated.
///
/// Determinism is what makes it envelope-able, and its floor is live — a strict
/// decode scans every live bit at least once — so a ceiling asserted over it
/// can never pass vacuously at zero.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[cfg(feature = "scan-meter")]
#[test]
fn scan_meter_counts_deterministically_and_resets() {
    // A strict id decode reads each live bit exactly once through the
    // sequential cursor, so the count has both a floor and an exact
    // expectation.
    let count_decode = |d: usize| {
        let p = id_spine(d, false);
        super::reset_scan_bits();
        let _ = Party::decode(&p.bytes[..]).expect("id spine decodes");
        (super::scan_bits(), p.bits as u64)
    };
    let (first, bits) = count_decode(10_000);
    assert!(
        first >= bits,
        "a strict decode of {bits} live bits scanned only {first}: \
         the sequential cursor is not recording: {ISOLATION_NOTE}"
    );
    super::reset_scan_bits();
    assert_eq!(
        super::scan_bits(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    assert_eq!(
        count_decode(10_000).0,
        first,
        "identical operations scan identical bits: {ISOLATION_NOTE}"
    );
    assert!(
        count_decode(20_000).0 > first,
        "a longer stream must scan more bits: {ISOLATION_NOTE}"
    );

    // The write side is live too: joining two disjoint spines writes the joined
    // tree through the id builder, so the count covers reads of both operands
    // plus at least the output's own bits.
    let pa = id_spine(1_000, false);
    let pb = id_spine(1_000, true);
    let mut a = Party::decode(&pa.bytes[..]).expect("id spine decodes");
    let b = Party::decode(&pb.bytes[..]).expect("id spine decodes");
    super::reset_scan_bits();
    a.join(b).expect("the divert arms are disjoint");
    let joined = super::scan_bits();
    assert!(
        joined >= a.encoded_bits(),
        "a join that wrote {} output bits recorded only {joined} scan bits: \
         the id builder is not recording its writes: {ISOLATION_NOTE}",
        a.encoded_bits(),
    );
}

proptest! {
    /// `I(d, divert)` is canonical normal form at exactly `2d + 2` bits for
    /// both arms, and the two arms are disjoint at every positive depth.
    #[test]
    fn id_spine_decodes_canonically_at_predicted_length(d in 1usize..=500) {
        let a = check_party(&id_spine(d, false), 2 * d + 2);
        let b = check_party(&id_spine(d, true), 2 * d + 2);
        prop_assert!(a.is_disjoint(&b), "divert arms own disjoint regions");
    }

    /// `Z(e)` is canonical normal form at exactly `6e + 2` bits for every
    /// positive extent.
    #[test]
    fn scattered_id_decodes_canonically_at_predicted_length(e in 1usize..=500) {
        let _ = check_party(&scattered_id(e), 6 * e + 2);
    }
}

proptest! {
    /// A scattered party aligned with a comb retains one wide magnitude per
    /// selected tooth throughout the generators' shared domain.
    #[test]
    fn scattered_id_projection_retains_each_selected_tooth(
        k in prop_oneof![1usize..=96, Just(200usize)],
        half_teeth in 1usize..=24,
    ) {
        let n = 2 * half_teeth;
        let comb = cliff_comb(k, n).version();
        let party = Party::decode(&scattered_id(n / 2).bytes[..])
            .expect("scattered id is strict normal form");
        let projected = (&comb / &party).to_version();
        assert!(
            projected.encoded_bits() >= ((n / 2) * k) as u64,
            "projection through the scattered id must keep a wide magnitude per kept tooth \
             (got {} bits from {} teeth of {} bits)",
            projected.encoded_bits(),
            n,
            k
        );
    }
}

proptest! {
    /// Every mask-drift triple is canonical at its closed-form lengths and
    /// realizes the same full-walk `Less` verdict through fused and
    /// materialized projection.
    #[test]
    fn mask_drift_triple_decodes_canonically_and_realizes_less(
        k in prop_oneof![1usize..=96, Just(200usize)],
        half_teeth in 1usize..=24,
    ) {
        let n = 2 * half_teeth;
        let (comb, mask, plateau) = mask_drift_triple(k, n);
        check_version(&comb, n * (2 * k + 10) + 2);
        check_version(&plateau, 2 * k + 2);
        let party = check_party(&mask, 6 * (n / 2) + 2);
        let (v, w) = (comb.version(), plateau.version());
        let fused = (&v / &party).partial_cmp(&w);
        assert_eq!(
            fused,
            Some(std::cmp::Ordering::Less),
            "the projected comb sits strictly under the plateau"
        );
        assert_eq!(
            fused,
            (&v / &party).to_version().partial_cmp(&w),
            "the fused verdict is the materialized verdict"
        );
    }

    /// Every mask-drift quadruple is canonical at its closed-form lengths and
    /// realizes the same `Less` verdict through fused and materialized views.
    #[test]
    fn mask_drift_quadruple_decodes_canonically_and_realizes_less(
        k in prop_oneof![1usize..=96, Just(200usize)],
        half_teeth in 1usize..=24,
    ) {
        let n = 2 * half_teeth;
        let ((sparse, even_mask), (comb, odd_mask)) = mask_drift_quadruple(k, n);
        check_version(&sparse, (n / 2) * (2 * k + 14) + 2);
        check_version(&comb, n * (2 * k + 10) + 2);
        let p1 = check_party(&even_mask, 6 * (n / 2) + 2);
        let p2 = check_party(&odd_mask, 6 * (n / 2) + 4);
        let (v1, v2) = (sparse.version(), comb.version());
        assert!(
            (&v1 / &p1).to_version().is_empty(),
            "the even mask owns exactly the sparse comb's zero levels"
        );
        assert!(
            !(&v2 / &p2).to_version().is_empty(),
            "the odd mask keeps the full comb's teeth"
        );
        let fused = (&v1 / &p1).partial_cmp(&(&v2 / &p2));
        assert_eq!(
            fused,
            Some(std::cmp::Ordering::Less),
            "the empty view sits strictly under the tooth-keeping view"
        );
        assert_eq!(
            fused,
            (&v1 / &p1)
                .to_version()
                .partial_cmp(&(&v2 / &p2).to_version()),
            "the fused verdict is the materialized verdict"
        );
    }
}

/// One hole region's closed-form bit length: `4·lead + 2(m − 1) +
/// Σ_{v=1}^{m} 2·bitlen(v + 1)` (the wrapper and staircase structure plus
/// each descending step's gamma-coded leaf).
fn hole_region_bits(lead: usize, m: usize) -> usize {
    4 * lead + 2 * (m - 1) + (1..=m).map(|v| 2 * bitlen(v + 1)).sum::<usize>()
}

/// The summed region bits of one hole pair's `k` units, leads alternating
/// 2, 3 across units (even `k`, so exactly half each).
fn hole_regions_bits(k: usize, m: usize) -> usize {
    (k / 2) * (hole_region_bits(2, m) + hole_region_bits(3, m))
}

proptest! {
    /// Every sub-scan hole pair is canonical normal form on both sides at its
    /// closed-form bit lengths. The generated `k` is even, as required by the
    /// alternating pair construction.
    #[test]
    fn hole_pairs_decode_canonically_at_predicted_lengths(
        half_pairs in 1usize..=16,
        m in 1usize..=40,
    ) {
        let k = 2 * half_pairs;
        let regions = hole_regions_bits(k, m);
        let (ev, id) = collapse_hole(k, m);
        check_version(&ev, 6 * k + 2 + regions);
        let _ = check_party(&id, 6 * k);
        let (ev, id) = copy_hole(k, m);
        check_version(&ev, 6 + 2 * k + regions);
        let _ = check_party(&id, 2 * k + 6);
        let (ev, id) = raise_hole(k, m);
        check_version(&ev, 2 * k + 2 + regions);
        let _ = check_party(&id, 4 * k + 4);
        let (ev, id) = site_hole(k, m);
        check_version(&ev, 6 * k + 6 + regions);
        let _ = check_party(&id, 6 * k + 4);
    }
}

proptest! {
    /// Every masked-hole triple is canonical at its closed-form lengths and
    /// realizes the same full-walk `Less` verdict through fused and
    /// materialized projection.
    #[test]
    fn masked_hole_decodes_canonically_and_realizes_less(
        h in 2usize..=32,
        extra_depth in 1usize..=128,
    ) {
        let d = h + extra_depth;
        let (spine, mask, plateau) = masked_hole(d, h);
        check_version(&spine, 4 * d + 4);
        check_version(&plateau, 4);
        let party = check_party(&mask, 2 * h + 2);
        let (v, w) = (spine.version(), plateau.version());
        let fused = (&v / &party).partial_cmp(&w);
        assert_eq!(
            fused,
            Some(std::cmp::Ordering::Less),
            "the projected spine sits strictly under the plateau"
        );
        assert_eq!(
            fused,
            (&v / &party).to_version().partial_cmp(&w),
            "the fused verdict is the materialized verdict"
        );
    }
}

/// The leaf count of a stored version's skyline stream, by one iterative
/// topology walk (payload codes skipped unread).
fn leaf_count(v: &Version) -> usize {
    use crate::version::io::tree::{VersionNode, VersionTreeReader};
    let mut reader = VersionTreeReader::new(v);
    let mut pending = 1usize;
    let mut leaves = 0usize;
    while pending > 0 {
        pending -= 1;
        match reader.node() {
            VersionNode::Leaf => {
                reader.skip_payload();
                leaves += 1;
            }
            VersionNode::Branch => pending += 2,
        }
    }
    leaves
}

proptest! {
    /// `JP(k, m, d)` is canonical normal form at its closed-form bit lengths,
    /// and its overlays realize the interleave the family exists for.
    ///
    /// The meet keeps four leaves per comb level, while the join collapses
    /// every level to two plateaus. Its distance is the sum of its two lags.
    #[test]
    fn jump_pair_decodes_canonically_at_predicted_lengths_and_interleaves(
        k in prop_oneof![3usize..=96, Just(400usize)],
        m in 1usize..=12,
        d in 1usize..=8,
    ) {
        let (a, b) = jump_pair(k, m, d);
        check_version(&a, 132 * d + m * (2 * k + 14) + 2);
        check_version(&b, 132 * d + 14 * m + 2 * k + 2);
        let (a, b) = (a.version(), b.version());
        let spine_leaves = super::JUMP_PAIR_DIGIT_STRIDE * d;
        assert_eq!(
            leaf_count(&(&a & &b)),
            spine_leaves + 4 * m + 1,
            "the meet must keep the band and gap interleave whole"
        );
        assert_eq!(
            leaf_count(&(&a | &b)),
            spine_leaves + 2 * m + 1,
            "the join must collapse each comb level to its two plateaus"
        );
        // The valuation identity, on the public surface: the pair's
        // distance is its two lags' sum (rank modularity).
        let d1 = a.lag(&b);
        let d2 = b.lag(&a);
        assert_eq!(a.distance(&b), &d1 + &d2, "distance is the lags' sum");
    }

    /// `CP(n)` is concurrent at every supported population size, alternates
    /// dominance at every boundary, and has distance two.
    #[test]
    fn concurrent_pair_alternates_dominance_at_every_boundary(levels in 1u32..=6) {
        let n = 1usize << levels;
        let (v, w) = concurrent_pair(n);
        assert!(v.concurrent(&w), "the pair must be causally concurrent");
        assert_eq!(
            leaf_count(&(&v | &w)),
            n,
            "the join must keep one plateau per forked leaf"
        );
        assert_eq!(
            leaf_count(&(&v & &w)),
            n,
            "the meet must keep one plateau per forked leaf"
        );
        let two = uniform(2u8).rank();
        assert_eq!(v.distance(&w), two, "the schedule's heights are realized");
    }
}

proptest! {
    /// `dense_suffix(p, d)` is canonical at `134d + (2A + 2P + 20)p + 4` bits,
    /// where `A` is [`PROMOTION_REARM_ARM_BITS`] and `P` is
    /// [`FREEZE_DRIFT_BITS`], and its minimum tick count equals the generator's
    /// stored-base sum.
    #[test]
    fn dense_suffix_decodes_canonically_at_predicted_length(
        p in 1usize..=24,
        d in 1usize..=24,
    ) {
        check_version(
            &dense_suffix(p, d),
            134 * d + (2 * PROMOTION_REARM_ARM_BITS + 2 * FREEZE_DRIFT_BITS + 20) * p + 4,
        );
        let expected = BigUint::from(d as u64)
            + BigUint::from(p as u64)
                * ((BigUint::ONE << PROMOTION_REARM_ARM_BITS)
                    + (BigUint::ONE << FREEZE_DRIFT_BITS)
                    + 2u8)
            + 1u8;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            dense_suffix(p, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `dense_suffix_mate(p, d)` is canonical at `134d + 24p + 4` bits, has
    /// the predicted minimum tick count, and is dominated by its wide mate.
    #[test]
    fn dense_suffix_mate_decodes_canonically_at_predicted_length(
        p in 1usize..=24,
        d in 1usize..=24,
    ) {
        check_version(&dense_suffix_mate(p, d), 134 * d + 24 * p + 4);
        let ticks = crate::Count::from(d as u64 + 4 * p as u64 + 1);
        assert_eq!(
            dense_suffix_mate(p, d).version().min_ticks(),
            ticks,
            "the unit-block spine's stored-base sum is its minimum tick count"
        );
        let a = dense_suffix(p, d).version();
        let b = dense_suffix_mate(p, d).version();
        assert!(
            a.rank().checked_sub(&b.rank()).is_some(),
            "the dense-suffix operand dominates its mate"
        );
        assert_eq!(a.lag(&b), crate::Rank::ZERO, "the dominating side has no lag");
    }

    /// `wide_arming(w, d)` is canonical at `134d + 64w + 2P + 24` bits, where
    /// `P` is [`FREEZE_DRIFT_BITS`], and its minimum tick count equals the
    /// generator's stored-base sum.
    #[test]
    fn wide_arming_decodes_canonically_at_predicted_length(
        w in prop_oneof![10usize..=40, Just(64usize)],
        d in 1usize..=32,
    ) {
        check_version(&wide_arming(w, d), 134 * d + 64 * w + 2 * FREEZE_DRIFT_BITS + 24);
        let expected = BigUint::from(d as u64)
            + (BigUint::ONE << (32 * w))
            + (BigUint::ONE << FREEZE_DRIFT_BITS)
            + 3u8;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            wide_arming(w, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `hoisted_window(w, d, t)` is canonical at its closed-form length, and
    /// changing the tail leaves its minimum tick count unchanged.
    #[test]
    fn hoisted_window_decodes_canonically_at_predicted_length(
        w in 10usize..=24,
        d in 1usize..=16,
        extra_tail in 0usize..=512,
    ) {
        let t = 32 * (w + 2) + extra_tail;
        check_version(
            &hoisted_window(w, d, t),
            134 * d + 64 * w + 4 * t + 2 * FREEZE_DRIFT_BITS + 24,
        );
        let expected = BigUint::from(d as u64)
            + (BigUint::ONE << (32 * w))
            + (BigUint::ONE << FREEZE_DRIFT_BITS)
            + 3u8;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            hoisted_window(w, d, t).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count, and the \
             tail must not move it"
        );
    }
}

proptest! {
    /// Extending a hoisted window's tail cannot increase its rank.
    #[test]
    fn deeper_hoisted_window_has_no_greater_rank(
        w in 10usize..=20,
        d in 1usize..=12,
        extra_tail in 0usize..=256,
        extension in 1usize..=256,
    ) {
        let t = 32 * (w + 2) + extra_tail;
        let hoisted = hoisted_window(w, d, t).version();
        let deeper = hoisted_window(w, d, t + extension).version();
        assert!(
            hoisted.rank().checked_sub(&deeper.rank()).is_some(),
            "a deeper tail only shrinks the tail sliver's area"
        );
    }
}

/// Returns the boundary shapes' shared narrow value.
fn boundary_rung_ubig() -> BigUint {
    BigUint::from(5u8) << 64usize
}

/// Returns the boundary shapes' `w`-digit operand `5·2^(32(w−1))`.
fn boundary_wide_ubig(w: usize) -> BigUint {
    BigUint::from(5u8) << (32 * (w - 1))
}

proptest! {
    /// `seam_plunge(k, r)` is canonical at `(k + 1)(64r − 56) + 2` bits and
    /// has the stored-base sum predicted by its ascending leaves.
    #[test]
    fn descending_boundary_decodes_canonically_at_predicted_length(
        k in 1usize..=64,
        r in 5usize..=12,
    ) {
        let p = seam_plunge(k, r);
        check_version(&p, (k + 1) * (64 * r - 56) + 2);
        let expected = boundary_wide_ubig(r) * BigUint::from((k + 1) as u64)
            + boundary_rung_ubig() * BigUint::from(((k + 1) * (k + 2) / 2) as u64);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `seam_plunge_control(k, r)` is canonical at `136k + 64r + 78` bits,
    /// has its predicted tick count, and shares all but its final code with
    /// the corresponding plunge.
    #[test]
    fn descending_boundary_control_decodes_at_predicted_length(
        k in 1usize..=64,
        r in 5usize..=12,
    ) {
        let p = seam_plunge_control(k, r);
        check_version(&p, 136 * k + 64 * r + 78);
        let expected = boundary_wide_ubig(r) + boundary_rung_ubig() * BigUint::from((k + 2) as u64);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
        // The wire-prefix identity: the pair's stored streams agree byte for
        // byte up to the control's full length less its final code and
        // padding — asserted structurally instead of byte-wise here, by the
        // leaf heights: both trees walk the identical ascent.
        let plunge = seam_plunge(k, r).version();
        let control = p.version();
        let plunge_wire = plunge.encode();
        let control_wire = control.encode();
        // The shared prefix: topology and all but the last delta agree, so
        // the shorter stream's first bytes match the longer's (the final
        // codes differ in length, so compare up to the divergence).
        let shared = control_wire
            .iter()
            .zip(plunge_wire.iter())
            .take_while(|(c, p)| c == p)
            .count();
        assert!(
            shared * 8 + 200 >= control_wire.len() * 8,
            "the control's wire diverges from the plunge's more than one \
             final code early: {shared} shared bytes of {}",
            control_wire.len(),
        );
    }

    /// `seam_stop(k)` is canonical at `164k + 266` bits and has the
    /// stored-base sum predicted by its descending leaves.
    #[test]
    fn stopping_boundary_decodes_canonically_at_predicted_length(k in 1usize..=128) {
        let p = seam_stop(k);
        check_version(&p, 164 * k + 266);
        let expected = stopping_boundary_ticks(k);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// The boundary-stop shapes' shared stored-base sum: the pair differs only in
/// zero-base wrapping, so one closed form serves both pins.
fn stopping_boundary_ticks(k: usize) -> BigUint {
    (BigUint::from(5u8) << 128usize)
        + (BigUint::from((k - 1) as u64) << 80usize)
        + boundary_rung_ubig() * BigUint::from((k * (k - 1) / 2) as u64)
}

proptest! {
    /// `seam_stop_control(k)` is canonical at `164k + 262` bits and has the
    /// same minimum tick count as `seam_stop(k)`.
    #[test]
    fn stopping_boundary_control_decodes_at_predicted_length(k in 1usize..=128) {
        let p = seam_stop_control(k);
        check_version(&p, 164 * k + 262);
        let ticks = min_ticks_from_big(&stopping_boundary_ticks(k));
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `latent_ladder(w, k)` is canonical at its closed-form length and has
    /// the stored-base sum predicted by the parked pair and ladder leaves.
    #[test]
    fn latent_ladder_decodes_canonically_at_predicted_length(
        w in 3usize..=16,
        k in 1usize..=128,
    ) {
        let p = latent_ladder(w, k);
        check_version(&p, k * (64 * w - 56) + 64 * w - 48);
        let expected = boundary_wide_ubig(w) * BigUint::from((k + 1) as u64) + BigUint::ONE
            - BigUint::from((k * (k + 1) / 2) as u64);
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `plateau_puncture(w, d)` is canonical at its closed-form length. Its
    /// stored size, minimum tick count, and rank match the product embedding
    /// from which the family is derived.
    #[test]
    fn plateau_puncture_decodes_canonically_at_predicted_length(
        w in prop_oneof![10usize..=24, Just(40usize)],
        d in prop_oneof![1usize..=24, Just(40usize)],
    ) {
        check_version(&plateau_puncture(w, d), d * (64 * w + 262) + 4);
        // The reduction's size premise, exact on the committed instance: the
        // STORED stream is `128w + 198d + 2` bits — `4·bits(x) + 3·bits(2y) +
        // 5`, the climb and plunge codes at `2·bits(x)` each plus 3 bits per
        // level — linear in the factors' widths even though the encoded
        // construction above is `Θ(d·w)` (it spells the plateau per turn). The
        // floor's funding argument divides the fold's cost by exactly this
        // stored size, so the premise is pinned beside the length it must not
        // drift from (the arbitrary-factor proptest beside the query fold pins
        // the same bound as an inequality).
        assert_eq!(
            plateau_puncture(w, d).version().encoded_bits(),
            (128 * w + 198 * d + 2) as u64,
            "the stored stream must stay linear in the factors' widths"
        );
        let (x, y) = plateau_puncture_factors(w, d);
        let expected = BigUint::from(d as u64) * &x + 1u8;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            plateau_puncture(w, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
        // The rank is exactly (2xy + 1) / 2^(66d).
        let numerator = ((&x * &y) << 1usize) + 1u8;
        assert_eq!(
            plateau_puncture(w, d).version().rank(),
            Rank::from_raw(numerator, (66 * d) as u64),
            "the exact rank is the plateau times the punctured turn mass"
        );
    }

    /// `arming_train(n, w, g, alternate)` is canonical at its closed-form
    /// length and its minimum tick count matches the generator's recurrence
    /// for both swing directions.
    #[test]
    fn arming_train_decodes_canonically_at_predicted_length(
        n in 1usize..=8,
        w in 19usize..=24,
        g in 1usize..=5,
        alt in any::<bool>(),
    ) {
        let band = 32 * w + (usize::BITS - n.leading_zeros()) as usize + 2;
        check_version(
            &arming_train(n, w, g, alt),
            n * (g * (2 * band + 132) + 8 * band + 16) + 2,
        );
        // The mirror: replay the generator's plateau recurrence and sum every
        // leaf value (the bottom and trailing leaves are all 0).
        let arm = BigUint::ONE << (32 * w);
        let kicker = BigUint::ONE << FREEZE_DRIFT_BITS;
        let mut plateau = (BigUint::ONE << band) + (&arm << 1);
        let mut expected = BigUint::ZERO;
        for b in 0..n {
            expected += &plateau * BigUint::from(g as u64); // the window turns
            if alt && b % 2 == 1 {
                plateau -= &arm;
            } else {
                plateau += &arm;
            }
            for kick in [BigUint::ZERO, BigUint::ONE, kicker.clone(), BigUint::ONE] {
                plateau += kick;
                expected += &plateau;
            }
        }
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            arming_train(n, w, g, alt).version().min_ticks(),
            ticks,
            "the mirrored leaf-value sum is the family's minimum tick count"
        );
    }
}

proptest! {
    /// `weight_comb(n)` is canonical at `202n − 4` bits and has minimum tick
    /// count `34n − 1` for every supported power-of-two width.
    #[test]
    fn weight_comb_decodes_canonically_at_predicted_length(levels in 0u32..=7) {
        let n = 1usize << levels;
        check_version(&weight_comb(n), 202 * n - 4);
        let ticks = crate::Count::from(34 * n as u64 - 1);
        assert_eq!(
            weight_comb(n).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }

    /// `freeze_parade(k)` is canonical at `(4P + 394)k − 2` bits, where `P` is
    /// [`FREEZE_DRIFT_BITS`], and its minimum tick count matches the closed
    /// form for every supported power-of-two parade width.
    #[test]
    fn freeze_parade_decodes_canonically_at_predicted_length(levels in 0u32..=6) {
        let k = 1usize << levels;
        check_version(&freeze_parade(k), (4 * FREEZE_DRIFT_BITS + 394) * k - 2);
        let j = bitlen(k) - 1;
        let w = BigUint::ONE << FREEZE_DRIFT_BITS;
        let stride = &w + BigUint::ONE;
        let expected = BigUint::from((64 * k - 1) as u64)
            + (BigUint::ONE << (FREEZE_DRIFT_BITS + 2 + bitlen(k)))
            + BigUint::from(k as u64) * &w
            + BigUint::from((k / 2 * j) as u64) * &stride
            - BigUint::from((k - 1) as u64) * &stride
            - &w;
        let ticks = min_ticks_from_big(&expected);
        assert_eq!(
            freeze_parade(k).version().min_ticks(),
            ticks,
            "the printed-base sum is the family's minimum tick count"
        );
    }

    /// Both `tooth_tail(g, m)` operands are canonical at `6m + 64g` bits,
    /// have their predicted minimum tick counts, and preserve their causal
    /// ordering throughout the supported domain.
    #[test]
    fn tooth_tail_decodes_canonically_at_predicted_length(
        g in 1usize..=16,
        m in 2usize..=64,
    ) {
        let (a, b) = tooth_tail(g, m);
        check_version(&a, 6 * m + 64 * g);
        check_version(&b, 6 * m + 64 * g);
        for (p, h) in [(&a, 1u64), (&b, 2u64)] {
            let expected = BigUint::from(m as u64 * h) + (BigUint::ONE << (32 * g));
            let ticks = min_ticks_from_big(&expected);
            assert_eq!(
                p.version().min_ticks(),
                ticks,
                "the stored-base sum is the operand's minimum tick count"
            );
        }
        assert_eq!(
            a.version().partial_cmp(&b.version()),
            Some(core::cmp::Ordering::Less),
            "b runs one tick above a everywhere except the shared terminal"
        );
    }

    /// Every staggered-comb operand is canonical at its closed-form length,
    /// has minimum tick count `m`, and the full population tiles the constant
    /// one version.
    #[test]
    fn stagger_comb_decodes_canonically_at_predicted_length(
        n_levels in 1u32..=4,
        m_levels in 0u32..=4,
    ) {
        let n = 1usize << n_levels;
        let m = 1usize << m_levels;
        let levels = n.trailing_zeros() as usize;
        for i in 0..n {
            let p = super::stagger_comb(n, m, i);
            check_version(&p, m * (4 * levels + 6) - 2);
            let ticks = crate::Count::from(m as u64);
            assert_eq!(
                p.version().min_ticks(),
                ticks,
                "the stored-base sum is the operand's minimum tick count"
            );
        }
        let (versions, _) = super::stagger_population(n, m);
        let all: Version = versions.iter().map(Encoding::version).sum();
        assert_eq!(
            all,
            uniform(1u8),
            "the population's teeth tile the whole domain at height 1"
        );
    }

    /// Every staggered-party operand is canonical at its closed-form length;
    /// the population is pairwise disjoint and joins back to the seed.
    #[test]
    fn stagger_id_decodes_canonically_at_predicted_length(
        n_levels in 1u32..=4,
        m_levels in 0u32..=4,
    ) {
        let n = 1usize << n_levels;
        let m = 1usize << m_levels;
        let levels = n.trailing_zeros() as usize;
        let parties: Vec<Party> = (0..n)
            .map(|i| check_party(&super::stagger_id(n, m, i), m * (2 * levels + 4) - 2))
            .collect();
        for (i, a) in parties.iter().enumerate() {
            for b in &parties[i + 1..] {
                assert!(a.is_disjoint(b), "distinct operands own distinct slots");
            }
        }
        let (_, ids) = super::stagger_population(n, m);
        let mut ids = ids
            .iter()
            .map(|p| Party::decode(&p.bytes[..]).expect("the population operands are canonical"));
        let mut acc = ids.next().expect("n >= 2");
        acc.join_all(ids)
            .expect("the population operands are pairwise disjoint");
        assert!(acc.is_seed(), "the population's slots tile the seed region");
    }

    /// A meet-shade population always starts with its dense carrier, contains
    /// only the advertised shades thereafter, and meets back to the carrier.
    #[test]
    fn meet_shade_is_the_dominated_carrier(
        d in 1usize..=64,
        k in 2usize..=16,
    ) {
        let population = super::meet_shade(d, k);
        assert_eq!(population.len(), k, "one carrier plus k - 1 shades");
        assert_eq!(population[0], dense(d).version(), "the carrier leads");
        for shade in &population[1..] {
            assert_eq!(shade, &hugeleaf(2).version(), "every shade is the plateau");
        }
        let met = population[0].meet_all(&population[1..]);
        assert_eq!(
            met,
            dense(d).version(),
            "the shades dominate the carrier everywhere: the meet is the carrier"
        );
    }
}

proptest! {
    /// The ascending-cliff band guard admits exactly the documented frontier.
    ///
    /// At every width `b`, the boundary knob `k = 2^b − 2` — the deepest leaf's
    /// gamma code exactly filling the width-`b` band (`k + 2 = 2^b`) — builds a
    /// canonical family member through both callers at the closed-form
    /// `k(2b + 4) + 2` bits, while the first knob past the band, `k = 2^b − 1`
    /// (`k + 2 > 2^b`), panics as both callers' contracts state.
    #[test]
    fn ascend_cliff_band_guard_admits_exactly_the_documented_frontier(b in 2usize..=16) {
        let boundary = (1usize << b) - 2;
        let builds: [fn(usize, usize) -> Encoding; 2] = [ascend_cliff, ascend_cliff_plateau];
        for build in builds {
            check_version(&build(boundary, b), boundary * (2 * b + 4) + 2);
            let past = std::panic::catch_unwind(|| build(boundary + 1, b));
            prop_assert!(
                past.is_err(),
                "k + 2 > 2^b must panic: the ascent leaves the width-b code band"
            );
        }
    }
}
