//! Generate the sync-budget trade-off table included in the rustdoc.
//!
//! Sweeps `Peer::sync_memory_budget` against mutual divergence on a
//! paused-clock delayed link, measuring each cell's session time in exact
//! virtual time relative to the same divergence under an effectively
//! unbounded budget — isolating what the budget itself costs. Regenerate
//! with `just window-tradeoff`; the output lands in
//! `src/tree/mirror/streaming/window/tradeoff.md` and is compiled into the
//! docs of [`Peer::sync_memory_budget`](rumors::Peer::sync_memory_budget).

#[allow(dead_code)]
#[path = "../benches/support/latency.rs"]
mod latency;

use std::time::Duration;

use rand::rngs::SmallRng;
use rand::{RngCore, SeedableRng};
use rumors::{Peer, Protocol, Rumors};

/// One-way delay of the modeled link (whole milliseconds: the timer grain).
const DELAY: Duration = Duration::from_millis(10);

/// Per-stream pipe buffering: roomy, so only round-trip structure and the
/// window are measured — the latency-only regime, where slowdown factors
/// are upper bounds for every real bandwidth.
const LINK_CAPACITY: usize = 8 * 1024 * 1024;

/// The unbounded-budget baseline each cell's slowdown is measured against.
const BASELINE_BUDGET: usize = 8 << 30;

/// The budget rows of the table; the last is the default.
const BUDGETS: &[(&str, usize)] = &[
    ("256 KiB", 256 << 10),
    ("1 MiB", 1 << 20),
    ("4 MiB", 4 << 20),
    ("16 MiB", 16 << 20),
    ("64 MiB", 64 << 20),
    ("128 MiB (default)", rumors::DEFAULT_SYNC_MEMORY_BUDGET),
];

/// The mutual-divergence columns (messages per side).
const DIVERGENCES: &[usize] = &[1_000, 10_000, 50_000];

/// Messages both peers share before the fork.
const COMMON: usize = 2_048;

fn main() {
    println!("<!-- Generated by `just window-tradeoff`; do not edit. -->");
    println!(
        "Session slowdown by budget and mutual divergence (messages per \
         side), measured in virtual time against the same divergence under \
         an unbounded budget. The link is latency-only, so these are \
         worst-case factors — independent of the delay itself — and a real \
         link's bandwidth absorbs them: once transfer time exceeds window \
         stall (dispute throughput `budget / (3 \u{d7} RTT)` at or above the \
         link rate), the factor is 1."
    );
    println!();
    println!("| budget | 1k | 10k | 50k |");
    println!("|---|---|---|---|");

    let baselines: Vec<Duration> = DIVERGENCES
        .iter()
        .map(|&d| session(BASELINE_BUDGET, d))
        .collect();

    for &(label, budget) in BUDGETS {
        let mut row = format!("| {label} |");
        for (column, &divergence) in DIVERGENCES.iter().enumerate() {
            let elapsed = session(budget, divergence);
            let slowdown = elapsed.as_secs_f64() / baselines[column].as_secs_f64();
            row.push_str(&format!(" {slowdown:.1}\u{d7} |"));
        }
        println!("{row}");
    }
}

/// One reconciliation at `budget` and `divergence`: virtual session time.
fn session(budget: usize, divergence: usize) -> Duration {
    let (left, right) = diverged(budget, divergence);
    let mut wire = latency::DelayedWire::new(LINK_CAPACITY, DELAY);
    let (_pair, elapsed) = wire.round_trip(left, right);
    elapsed
}

/// Two peers with a shared prefix, diverged by `divergent` messages each.
fn diverged(budget: usize, divergent: usize) -> (Rumors<u64>, Rumors<u64>) {
    let left = Peer::seed().sync_memory_budget(budget).into_rumors();
    let mut rng = SmallRng::seed_from_u64(0x0b05_2026_0d0c_0001);
    send_random(&left, COMMON, &mut rng);

    let right = pollster::block_on(async {
        let (mut provider, mut newcomer) = rumors::link::memory_with_capacity(LINK_CAPACITY);
        let (served, joined) = tokio::join!(
            left.gossip(&mut provider),
            Peer::<u64>::bootstrap_with_protocol(Protocol::V2, &mut newcomer),
        );
        served.expect("serve bootstrap");
        joined
            .expect("bootstrap newcomer")
            .expect("provider is established")
            .sync_memory_budget(budget)
            .into_rumors()
    });

    send_random(&left, divergent, &mut rng);
    send_random(&right, divergent, &mut rng);
    (left, right)
}

/// Commit `n` random payloads as one batch.
fn send_random(rumors: &Rumors<u64>, n: usize, rng: &mut SmallRng) {
    let mut batch = rumors.batch();
    for _ in 0..n {
        batch.send(rng.next_u64());
    }
}
