//! Pinned per-operation fuel bands: the calibration leg's committed output.
//!
//! [`BANDS`] is generated by `bin/calibrate` (which rewrites this file
//! atomically) and committed; the enforcement leg judges against these
//! constants and never refits. To re-pin — after a deliberate guest
//! toolchain bump, a kernel change, or a strategy change — run
//! `just fuzzfit-calibrate`, review the diff like a snapshot, and commit
//! with a dated movement annotation.
//!
//! The band key is **kernel × outcome**: an operation with a rejection arm
//! (`join`/`sync` on overlap, `without` on emptiness, `checked_sub` on
//! underflow) gets one band for its success path and one for its rejection
//! path. The two are different mechanisms with different cost laws — a
//! rejection can legitimately undercut the success line by decades (early
//! overlap detection), and pricing both from one pooled cloud lets a
//! superlinear regression in either arm hide under the other's ceiling.
//!
//! Band semantics: a step of kernel `k` with denominator `d` bits and fuel
//! `f` is in-band iff, writing `r = log₁₀ f − (intercept + slope · log₁₀ d)`,
//!
//! ```text
//! −(width_below + ENFORCE_MARGIN_BELOW) ≤ r ≤ width_above + ENFORCE_MARGIN
//! ```
//!
//! judged only for `d ≥ min_denom` (below the calibrated range the line
//! extrapolates the intercept's constant overhead downward, which
//! false-flags genuinely cheap small cases; the rare fresh draw above
//! `max_denom` is judged against the extrapolated line — but enforcement
//! shares the calibration leg's generators and budgets, so the catching
//! power lives *inside* the calibrated span, which is why the ceiling is
//! priced from the positive residuals alone and the reach families exist).
//! Above-band is a regression flag; below-band is a liveness flag (a dead
//! fuel meter or an accidentally-constant kernel reads below its own band,
//! never silently green). The two widths are priced separately because the
//! residual cloud is one-sidedly heavy — see [`crate::fit`].
//!
//! # Pin of record
//!
//! Pinned 2026-07-26: corpus 1536 programs (~979k measured steps), guest
//! at wasm32-unknown-unknown release (codegen-units 1, panic=abort) under
//! the toolchain in [`PINNED_RUSTC`], wasmtime 47 fuel. This pin re-keys
//! the bands by kernel × outcome (48 keys: 44 kernels, of which four have
//! sampled rejection arms) and extends the reach family's cadence battery
//! through every single-operand row and every rejection arm, so every
//! band's population changed.
//!
//! All 48 band keys read linear-or-flatter within every family above the
//! 128-bit fit floor — the within-case shape diagnostic's maximum healthy
//! excess over the whole corpus is +0.006 (see [`crate::curve`]) — while
//! the pooled envelope slopes above 1.1 remain the documented
//! family-mixture composition (families' per-bit cost levels differ
//! severalfold and the cheap families' mass sits in the small buckets,
//! tilting a pooled envelope no single family follows; every lane's own
//! medians are flat or falling, and `bin/diag` per family is the
//! ground-truth view). The rejection-arm envelopes (1.32–1.48) are the
//! same genre at smaller n: cheap immediate-overlap rejections dominate
//! the small buckets, full-scan and deferred-overlap rejections the top.
//! `ff_version_join_all` 1.144 carries the balanced fold's documented log
//! factor along the width ladder (fold width is budget-capped, so the
//! factor is bounded and the band prices it).
//!
//! Movement against the previous pin, by mechanism (movement > 0.05):
//!
//! - **Outcome re-keying** — the four rejection arms leave their success
//!   pools and pin their own laws: `clock_join [err]` 1.37 (to 21.5k
//!   bits), `clock_sync [err]` 1.39, `party_join [err]` 1.48,
//!   `party_without [err]` 1.32. The vacated success floors tighten
//!   accordingly (width_below: `clock_join` 2.27→1.38, `clock_sync`
//!   2.29→1.07, `party_join` 1.53→0.76). `version_meet_all`'s and
//!   `rank_checked_sub`'s rejection arms are generator-unreachable (folds
//!   are never empty; rank pools hold a single rank, so `checked_sub`
//!   never underflows) and have no bands.
//! - **Reach reclassifications** — the escalation cadence battery gives
//!   the single-operand rows real spans; kernels the old corpus sampled
//!   under a decade now fit slopes: `clock_recv` const→1.05 (to 18.5k
//!   bits), `clock_send` const→1.09, `version_tick` const→0.87,
//!   `party_fork` const→0.88 (13 samples→251), `party_forks` const→0.90,
//!   `party_without` const→0.82 (5 samples→119); `clock_from_parts`
//!   const(431 bits)→slope 0.000 with width 0.000 over 129..10.8k bits —
//!   the proven-constant reading for the O(1) wrap, now over real reach.
//!   `clock_join`'s success span extends 3.8k→21.3k bits (the ladder's
//!   top-size coupled join), slope 0.97→1.00.
//! - **Population recomposition** — the cadence battery's mass re-tilts
//!   a few pooled envelopes: `party_encode` 0.36→0.21, `version_project`
//!   1.00→0.87 (escalated operands land family-pure top buckets),
//!   `clock_encode` 0.33→0.38, `version_join` 1.04→1.06 with its floor
//!   tightening 3.39→2.22. The meet ladder recomposes `version_meet`
//!   1.14→1.03 and halves its ceiling (+0.87→+0.30): the widest thin
//!   row now carries dense within-case mass across the reach, so both
//!   its point ceiling and its shape-leg evidence tighten together (its
//!   floor widens 2.33→2.85 with the ladder's cheap adjacent-rung
//!   meets — legitimate fast-path mass on the liveness side).
//! - **Early-exit economics re-measured** — `version_meet_all` −0.26→1.05:
//!   the ladder's snapshots now share the cadence recv's events, so
//!   escalated meets no longer collapse to a common floor immediately and
//!   the envelope rises back toward linear; still inside its width.

/// One pinned band (see the module doc for the membership predicate).
#[derive(Debug, Clone, Copy)]
pub struct Band {
    /// The guest kernel this band prices (with `rejected`, the band key).
    pub kernel: &'static str,
    /// Whether this band prices the kernel's rejection arm (`ERR_OP`
    /// outcomes) rather than its success path.
    pub rejected: bool,
    /// Pinned log-log slope.
    pub slope: f64,
    /// Pinned intercept (`log₁₀` fuel at 1 bit).
    pub intercept: f64,
    /// Pinned ceiling width: max positive residual over the calibration
    /// corpus (the regression flag's threshold).
    pub width_above: f64,
    /// Pinned floor width: max negative residual magnitude over the
    /// calibration corpus (the liveness flag's threshold).
    pub width_below: f64,
    /// Smallest calibrated denominator (bits): the judgment floor.
    pub min_denom: u64,
    /// Largest calibrated denominator (bits), recorded for provenance.
    pub max_denom: u64,
    /// Calibration corpus size behind this band.
    pub samples: usize,
    /// Whether the band was constant-classified (slope pinned at 0).
    pub constant: bool,
}

/// Slack beyond each band's fitted ceiling, in `log₁₀` units.
///
/// Absorbs allocator-history variance between calibration and
/// enforcement contexts (≈ 1.6× in fuel). The ceiling carries the
/// regression claim, so its slack stays tight; contrast
/// [`ENFORCE_MARGIN_BELOW`].
pub const ENFORCE_MARGIN: f64 = 0.2;

/// Slack beyond each band's fitted floor, in `log₁₀` units.
///
/// The floor carries the liveness claim, and a dead meter or an
/// unmeasured path reads *decades* below any honest floor (nop-level
/// fuel sits well over a decade under every pinned floor even with this
/// slack), so the floor's slack is priced against the honest cheap tail
/// instead: fresh draws legitimately undercut the corpus minimum — the
/// committed rejection-shape seed's `join_all` step reads 0.29 below its
/// pinned floor width — and a liveness threshold left inside the honest
/// distribution's tail relocates that dispersion into flakiness. One
/// decade sits in the measured gap between the cheapest honest readings
/// and dead-meter readings.
pub const ENFORCE_MARGIN_BELOW: f64 = 1.0;

/// The staleness cross-check's prefix length.
///
/// The enforcement suite refits the first `REFIT_PREFIX_PROGRAMS`
/// programs of the deterministic calibration stream
/// (`drive::for_each_deterministic_program`) and compares each covered
/// band key's fresh line against its pin, so a pin the current code would
/// no longer produce fails loud instead of silently drifting. A prefix,
/// because a full-corpus refit would duplicate the calibration sweep
/// inside every suite run.
pub const REFIT_PREFIX_PROGRAMS: usize = 256;

/// Largest allowed [`crate::fit::line_divergence`] between the prefix
/// refit and the pin, in `log₁₀` units.
///
/// Measured 2026-07-26 at pin time (`bin/calibrate` re-derives the
/// evidence on every re-pin): the prefix's own sampling difference from
/// the full corpus peaks at 0.547 (`ff_party_join`'s rejection arm, the
/// thinnest-sampled band key). The tolerance sits above that, so the
/// check is deaf to sub-half-decade drift on the worst key but fails
/// loud on anything past ~5x in fuel constants — a staleness detector,
/// not the criterion of record.
pub const REFIT_TOLERANCE: f64 = 0.7;

/// Look up the pinned band for one band key (kernel × outcome).
pub fn band_for(kernel: &str, rejected: bool) -> Option<&'static Band> {
    BANDS
        .iter()
        .find(|b| b.kernel == kernel && b.rejected == rejected)
}

/// One step's verdict against a band.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Within the band: the pinned claim held for this step.
    InBand,
    /// Above the band: a regression flag (more work than the pinned law
    /// predicts for this size).
    Above,
    /// Below the band: a liveness flag (less work than any honest
    /// execution of this kernel performs — a dead meter or a measurement
    /// hole).
    Below,
    /// Below the calibrated floor: not judged (the line extrapolates the
    /// constant-overhead regime downward there).
    BelowFloor,
}

/// Judge one measured step against a band (the enforcement predicate; see
/// the module doc for its definition).
pub fn judge_against(band: &Band, denom_bits: u64, fuel: u64) -> Verdict {
    if denom_bits < band.min_denom {
        return Verdict::BelowFloor;
    }
    let predicted = band.intercept + band.slope * (denom_bits as f64).log10();
    let actual = (fuel.max(1) as f64).log10();
    if actual > predicted + band.width_above + ENFORCE_MARGIN {
        Verdict::Above
    } else if actual < predicted - band.width_below - ENFORCE_MARGIN_BELOW {
        Verdict::Below
    } else {
        Verdict::InBand
    }
}

/// The toolchain that pinned the constants below, as `rustc --version`
/// reports it.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: guest
/// codegen (and so every fuel constant) is a function of this compiler,
/// and the suite asserts the building toolchain matches, so a toolchain
/// bump reads red until the bands are re-pinned. wasmtime (the fuel
/// schedule's other half) is pinned exactly by the workspace
/// `Cargo.lock`; bumping it there is likewise a re-pin event.
pub const PINNED_RUSTC: &str = "rustc 1.96.1 (31fca3adb 2026-06-26)";

/// The pinned bands.
///
/// Generated by `just fuzzfit-calibrate` — review the diff like a
/// snapshot, commit with a dated movement annotation.
pub const BANDS: &[Band] = &[
    Band {
        kernel: "ff_clock_decode",
        rejected: false,
        slope: 1.075479,
        intercept: 2.063816,
        width_above: 0.137325,
        width_below: 0.116549,
        min_denom: 128,
        max_denom: 10760,
        samples: 569,
        constant: false,
    },
    Band {
        kernel: "ff_clock_encode",
        rejected: false,
        slope: 0.371211,
        intercept: 2.154891,
        width_above: 0.157382,
        width_below: 0.292917,
        min_denom: 128,
        max_denom: 10755,
        samples: 551,
        constant: false,
    },
    Band {
        kernel: "ff_clock_fork",
        rejected: false,
        slope: 0.880579,
        intercept: 1.751391,
        width_above: 0.254444,
        width_below: 0.304187,
        min_denom: 128,
        max_denom: 10862,
        samples: 35036,
        constant: false,
    },
    Band {
        kernel: "ff_clock_from_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.390935,
        width_above: 0.000000,
        width_below: 0.000000,
        min_denom: 129,
        max_denom: 10751,
        samples: 596,
        constant: false,
    },
    Band {
        kernel: "ff_clock_into_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.511883,
        width_above: 0.020871,
        width_below: 0.000000,
        min_denom: 128,
        max_denom: 10862,
        samples: 13606,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: false,
        slope: 0.998234,
        intercept: 2.621136,
        width_above: 0.298486,
        width_below: 1.377877,
        min_denom: 128,
        max_denom: 21318,
        samples: 9724,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: true,
        slope: 1.367191,
        intercept: 0.226880,
        width_above: 0.332591,
        width_below: 0.810780,
        min_denom: 131,
        max_denom: 21510,
        samples: 146,
        constant: false,
    },
    Band {
        kernel: "ff_clock_own_version",
        rejected: false,
        slope: 1.050176,
        intercept: 2.441467,
        width_above: 0.164876,
        width_below: 0.173782,
        min_denom: 128,
        max_denom: 13116,
        samples: 422,
        constant: false,
    },
    Band {
        kernel: "ff_clock_recv",
        rejected: false,
        slope: 1.050441,
        intercept: 2.985644,
        width_above: 0.314164,
        width_below: 0.466625,
        min_denom: 128,
        max_denom: 18460,
        samples: 2043,
        constant: false,
    },
    Band {
        kernel: "ff_clock_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 3.139967,
        width_above: 0.007400,
        width_below: 0.002613,
        min_denom: 8,
        max_denom: 8,
        samples: 1704,
        constant: true,
    },
    Band {
        kernel: "ff_clock_send",
        rejected: false,
        slope: 1.092440,
        intercept: 2.934446,
        width_above: 0.090667,
        width_below: 0.376427,
        min_denom: 128,
        max_denom: 10748,
        samples: 1190,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: false,
        slope: 1.013720,
        intercept: 2.582119,
        width_above: 0.291112,
        width_below: 1.065539,
        min_denom: 128,
        max_denom: 21622,
        samples: 568,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: true,
        slope: 1.387287,
        intercept: 0.166272,
        width_above: 0.828238,
        width_below: 0.840874,
        min_denom: 133,
        max_denom: 20438,
        samples: 153,
        constant: false,
    },
    Band {
        kernel: "ff_clock_tick",
        rejected: false,
        slope: 1.148508,
        intercept: 2.719164,
        width_above: 0.313595,
        width_below: 0.285746,
        min_denom: 128,
        max_denom: 10862,
        samples: 119841,
        constant: false,
    },
    Band {
        kernel: "ff_clock_version",
        rejected: false,
        slope: 0.380614,
        intercept: 1.607376,
        width_above: 0.209440,
        width_below: 0.155850,
        min_denom: 128,
        max_denom: 10867,
        samples: 4306,
        constant: false,
    },
    Band {
        kernel: "ff_party_covers",
        rejected: false,
        slope: 1.065185,
        intercept: 1.617971,
        width_above: 0.149939,
        width_below: 1.378251,
        min_denom: 128,
        max_denom: 9140,
        samples: 905,
        constant: false,
    },
    Band {
        kernel: "ff_party_decode",
        rejected: false,
        slope: 0.978826,
        intercept: 1.872638,
        width_above: 0.052426,
        width_below: 0.027286,
        min_denom: 128,
        max_denom: 4536,
        samples: 634,
        constant: false,
    },
    Band {
        kernel: "ff_party_display",
        rejected: false,
        slope: 0.936714,
        intercept: 1.424546,
        width_above: 0.101252,
        width_below: 0.048274,
        min_denom: 136,
        max_denom: 66018,
        samples: 1794,
        constant: false,
    },
    Band {
        kernel: "ff_party_encode",
        rejected: false,
        slope: 0.212749,
        intercept: 2.505014,
        width_above: 0.234350,
        width_below: 0.353453,
        min_denom: 128,
        max_denom: 4530,
        samples: 589,
        constant: false,
    },
    Band {
        kernel: "ff_party_fork",
        rejected: false,
        slope: 0.882867,
        intercept: 2.209588,
        width_above: 0.042517,
        width_below: 0.034911,
        min_denom: 132,
        max_denom: 4478,
        samples: 251,
        constant: false,
    },
    Band {
        kernel: "ff_party_forks",
        rejected: false,
        slope: 0.898670,
        intercept: 2.442970,
        width_above: 0.090588,
        width_below: 0.208127,
        min_denom: 128,
        max_denom: 4246,
        samples: 447,
        constant: false,
    },
    Band {
        kernel: "ff_party_fromstr",
        rejected: false,
        slope: 0.980489,
        intercept: 1.376199,
        width_above: 0.163863,
        width_below: 0.056156,
        min_denom: 136,
        max_denom: 66018,
        samples: 1794,
        constant: false,
    },
    Band {
        kernel: "ff_party_is_disjoint",
        rejected: false,
        slope: 1.206957,
        intercept: 0.886294,
        width_above: 0.387562,
        width_below: 1.100886,
        min_denom: 128,
        max_denom: 9140,
        samples: 905,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: false,
        slope: 1.236561,
        intercept: 1.617362,
        width_above: 0.325335,
        width_below: 0.762715,
        min_denom: 128,
        max_denom: 7678,
        samples: 13369,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: true,
        slope: 1.478924,
        intercept: 0.413072,
        width_above: 0.455574,
        width_below: 0.865125,
        min_denom: 132,
        max_denom: 9140,
        samples: 143,
        constant: false,
    },
    Band {
        kernel: "ff_party_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 2.694181,
        width_above: 0.025150,
        width_below: 0.003100,
        min_denom: 8,
        max_denom: 8,
        samples: 112,
        constant: true,
    },
    Band {
        kernel: "ff_party_without",
        rejected: false,
        slope: 0.818424,
        intercept: 2.174045,
        width_above: 0.043970,
        width_below: 0.041294,
        min_denom: 146,
        max_denom: 4260,
        samples: 119,
        constant: false,
    },
    Band {
        kernel: "ff_party_without",
        rejected: true,
        slope: 1.321537,
        intercept: 1.106616,
        width_above: 0.333306,
        width_below: 0.194712,
        min_denom: 134,
        max_denom: 8896,
        samples: 124,
        constant: false,
    },
    Band {
        kernel: "ff_rank_add",
        rejected: false,
        slope: 0.502460,
        intercept: 1.891041,
        width_above: 0.230421,
        width_below: 0.188264,
        min_denom: 128,
        max_denom: 7072,
        samples: 491,
        constant: false,
    },
    Band {
        kernel: "ff_rank_checked_sub",
        rejected: false,
        slope: 0.604469,
        intercept: 1.410730,
        width_above: 0.206506,
        width_below: 0.150459,
        min_denom: 128,
        max_denom: 7072,
        samples: 514,
        constant: false,
    },
    Band {
        kernel: "ff_rank_cmp",
        rejected: false,
        slope: 0.682950,
        intercept: 1.103930,
        width_above: 0.227065,
        width_below: 0.155913,
        min_denom: 128,
        max_denom: 7072,
        samples: 514,
        constant: false,
    },
    Band {
        kernel: "ff_rank_display",
        rejected: false,
        slope: 1.119253,
        intercept: 0.671393,
        width_above: 0.256261,
        width_below: 0.123384,
        min_denom: 128,
        max_denom: 7072,
        samples: 514,
        constant: false,
    },
    Band {
        kernel: "ff_version_cmp",
        rejected: false,
        slope: 1.148414,
        intercept: 1.773463,
        width_above: 0.337800,
        width_below: 0.921905,
        min_denom: 128,
        max_denom: 15574,
        samples: 1855,
        constant: false,
    },
    Band {
        kernel: "ff_version_concurrent",
        rejected: false,
        slope: 1.148511,
        intercept: 1.773102,
        width_above: 0.337642,
        width_below: 0.922525,
        min_denom: 128,
        max_denom: 15574,
        samples: 1855,
        constant: false,
    },
    Band {
        kernel: "ff_version_decode",
        rejected: false,
        slope: 1.163056,
        intercept: 1.798911,
        width_above: 0.343441,
        width_below: 0.424695,
        min_denom: 128,
        max_denom: 7792,
        samples: 1199,
        constant: false,
    },
    Band {
        kernel: "ff_version_display",
        rejected: false,
        slope: 0.970625,
        intercept: 1.923186,
        width_above: 0.137147,
        width_below: 0.125024,
        min_denom: 141,
        max_denom: 99746,
        samples: 2163,
        constant: false,
    },
    Band {
        kernel: "ff_version_distance",
        rejected: false,
        slope: 1.083273,
        intercept: 2.845198,
        width_above: 0.331485,
        width_below: 0.465697,
        min_denom: 128,
        max_denom: 15574,
        samples: 1791,
        constant: false,
    },
    Band {
        kernel: "ff_version_encode",
        rejected: false,
        slope: 0.426583,
        intercept: 1.517665,
        width_above: 0.214221,
        width_below: 0.255032,
        min_denom: 128,
        max_denom: 7787,
        samples: 1173,
        constant: false,
    },
    Band {
        kernel: "ff_version_fromstr",
        rejected: false,
        slope: 0.968124,
        intercept: 2.130363,
        width_above: 0.101627,
        width_below: 0.081173,
        min_denom: 141,
        max_denom: 99746,
        samples: 2163,
        constant: false,
    },
    Band {
        kernel: "ff_version_join",
        rejected: false,
        slope: 1.064352,
        intercept: 2.099364,
        width_above: 0.700140,
        width_below: 2.223804,
        min_denom: 128,
        max_denom: 12998,
        samples: 2192,
        constant: false,
    },
    Band {
        kernel: "ff_version_join_all",
        rejected: false,
        slope: 1.143965,
        intercept: 2.864669,
        width_above: 0.349791,
        width_below: 2.110810,
        min_denom: 128,
        max_denom: 166296,
        samples: 1256,
        constant: false,
    },
    Band {
        kernel: "ff_version_lag",
        rejected: false,
        slope: 1.093285,
        intercept: 2.626707,
        width_above: 0.369358,
        width_below: 0.479048,
        min_denom: 128,
        max_denom: 15574,
        samples: 1791,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet",
        rejected: false,
        slope: 1.033879,
        intercept: 2.585769,
        width_above: 0.302315,
        width_below: 2.850207,
        min_denom: 128,
        max_denom: 15222,
        samples: 1211,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet_all",
        rejected: false,
        slope: 1.050694,
        intercept: 1.970389,
        width_above: 0.888276,
        width_below: 1.072782,
        min_denom: 128,
        max_denom: 114722,
        samples: 442,
        constant: false,
    },
    Band {
        kernel: "ff_version_min_ticks",
        rejected: false,
        slope: 1.139518,
        intercept: 2.103752,
        width_above: 0.327353,
        width_below: 0.502944,
        min_denom: 128,
        max_denom: 7322,
        samples: 1099,
        constant: false,
    },
    Band {
        kernel: "ff_version_project",
        rejected: false,
        slope: 0.865493,
        intercept: 2.916583,
        width_above: 0.580950,
        width_below: 0.406934,
        min_denom: 128,
        max_denom: 42083,
        samples: 1584,
        constant: false,
    },
    Band {
        kernel: "ff_version_rank",
        rejected: false,
        slope: 1.153875,
        intercept: 2.053129,
        width_above: 0.370830,
        width_below: 0.436567,
        min_denom: 128,
        max_denom: 7787,
        samples: 1911,
        constant: false,
    },
    Band {
        kernel: "ff_version_tick",
        rejected: false,
        slope: 0.871695,
        intercept: 3.407286,
        width_above: 0.324585,
        width_below: 0.920425,
        min_denom: 128,
        max_denom: 12185,
        samples: 966,
        constant: false,
    },
];

/// The band keys the pin-time prefix refit covered: the staleness
/// cross-check's committed expectation list.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: every key
/// listed here had, at pin time, a prefix refit whose classification
/// matched its pin. The enforcement suite requires each listed key to
/// still fit, still match its pin's classification, and still agree
/// within [`REFIT_TOLERANCE`] — so coverage decay, a classification flip
/// (the reach-regression tell), and line drift each fail by name instead
/// of hollowing the check out silently. Keys not listed are outside the
/// staleness detector's reach at pin time; calibration prints them for
/// the re-pinner to review.
pub const REFIT_COVERAGE: &[(&str, bool)] = &[
    ("ff_clock_decode", false),
    ("ff_clock_encode", false),
    ("ff_clock_fork", false),
    ("ff_clock_from_parts", false),
    ("ff_clock_into_parts", false),
    ("ff_clock_join", false),
    ("ff_clock_join", true),
    ("ff_clock_own_version", false),
    ("ff_clock_recv", false),
    ("ff_clock_seed", false),
    ("ff_clock_send", false),
    ("ff_clock_sync", false),
    ("ff_clock_sync", true),
    ("ff_clock_tick", false),
    ("ff_clock_version", false),
    ("ff_party_covers", false),
    ("ff_party_decode", false),
    ("ff_party_display", false),
    ("ff_party_encode", false),
    ("ff_party_fork", false),
    ("ff_party_forks", false),
    ("ff_party_fromstr", false),
    ("ff_party_is_disjoint", false),
    ("ff_party_join", false),
    ("ff_party_join", true),
    ("ff_party_seed", false),
    ("ff_party_without", false),
    ("ff_party_without", true),
    ("ff_rank_add", false),
    ("ff_rank_checked_sub", false),
    ("ff_rank_cmp", false),
    ("ff_rank_display", false),
    ("ff_version_cmp", false),
    ("ff_version_concurrent", false),
    ("ff_version_decode", false),
    ("ff_version_display", false),
    ("ff_version_distance", false),
    ("ff_version_encode", false),
    ("ff_version_fromstr", false),
    ("ff_version_join", false),
    ("ff_version_join_all", false),
    ("ff_version_lag", false),
    ("ff_version_meet", false),
    ("ff_version_meet_all", false),
    ("ff_version_min_ticks", false),
    ("ff_version_project", false),
    ("ff_version_rank", false),
    ("ff_version_tick", false),
];
