//! Pinned per-operation fuel bands: the calibration leg's committed output.
//!
//! [`BANDS`] is generated by `bin/calibrate` (which rewrites this file
//! atomically) and committed; the enforcement leg judges against these
//! constants and never refits. To re-pin — after a deliberate guest
//! toolchain bump, a kernel change, or a strategy change — run
//! `just fuzzfit-calibrate`, review the diff like a snapshot, and commit
//! with a dated movement annotation.
//!
//! The band key is **kernel × outcome**: an operation with a rejection arm
//! (`join`/`sync` on overlap, `without` on emptiness, `checked_sub` on
//! underflow) gets one band for its success path and one for its rejection
//! path. The two are different mechanisms with different cost laws — a
//! rejection can legitimately undercut the success line by decades (early
//! overlap detection), and pricing both from one pooled cloud lets a
//! superlinear regression in either arm hide under the other's ceiling.
//!
//! Band semantics: a step of kernel `k` with denominator `d` bits and fuel
//! `f` is in-band iff, writing `r = log₁₀ f − (intercept + slope · log₁₀ d)`,
//!
//! ```text
//! −(width_below + ENFORCE_MARGIN_BELOW) ≤ r ≤ width_above + ENFORCE_MARGIN
//! ```
//!
//! judged only for `d ≥ min_denom` (below the calibrated range the line
//! extrapolates the intercept's constant overhead downward, which
//! false-flags genuinely cheap small cases; the rare fresh draw above
//! `max_denom` is judged against the extrapolated line — but enforcement
//! shares the calibration leg's generators and budgets, so the catching
//! power lives *inside* the calibrated span, which is why the ceiling is
//! priced from the positive residuals alone and the reach families exist).
//! Above-band is a regression flag; below-band is a liveness flag (a dead
//! fuel meter or an accidentally-constant kernel reads below its own band,
//! never silently green). The two widths are priced separately because the
//! residual cloud is one-sidedly heavy — see [`crate::fit`].
//!
//! # Pin of record
//!
//! Pinned 2026-07-26: corpus 1536 programs (~985k measured steps), guest
//! at wasm32-unknown-unknown release (codegen-units 1, panic=abort) under
//! the toolchain in [`PINNED_RUSTC`], wasmtime 47 fuel. 49 band keys: 44
//! kernels, of which five have sampled rejection arms (`clock_join` and
//! `clock_sync` on overlap, `party_join` on overlap, `party_without` on
//! emptiness, `rank_checked_sub` on underflow). The one deliberately
//! unpriced outcome is `meet_all([])`'s `None`: production-reachable but
//! structurally constant — no operand exists, so there is nothing for a
//! regression to scale with and nothing to denominate a cost against.
//!
//! All 49 band keys read linear-or-flatter within every family above the
//! 128-bit fit floor — the within-case shape diagnostic's maximum healthy
//! excess over the whole corpus is +0.006 (see [`crate::curve`]) — while
//! the pooled envelope slopes above 1.1 remain the documented
//! family-mixture composition (families' per-bit cost levels differ
//! severalfold and the cheap families' mass sits in the small buckets,
//! tilting a pooled envelope no single family follows; every lane's own
//! medians are flat or falling, and `bin/diag` per family is the
//! ground-truth view). The operation-rejection envelopes (1.32–1.48) are
//! the same genre at smaller n: cheap immediate-overlap rejections
//! dominate the small buckets, full-scan and deferred-overlap rejections
//! the top. `rank_checked_sub`'s underflow arm reads flat (−0.12): the
//! ordering pre-check settles the outcome before any alignment work, so
//! its cost does not grow with the operands. `ff_version_join_all` 1.143
//! carries the balanced fold's documented log factor along the width
//! ladder (fold width is budget-capped, so the factor is bounded and the
//! band prices it).
//!
//! Movement against the previous pin (2026-07-26, at the merge onto the
//! campaign line), by mechanism. This re-pin absorbs the kernel work the
//! merge brought under the guest — no generator, strategy, or toolchain
//! change rode along: the deterministic corpus replayed with identical
//! sample counts per band key, so every movement is guest fuel. Judged
//! at 1000 denominated bits; movement > 0.05 decades:
//!
//! - **Version and Party at rest are the wire stream** (`codec::Bits`
//!   for Version, the raw bit stream for Party — not a structured
//!   tree) — the bridge, codec, and query rows re-shape around
//!   stream-form storage: `clock_version` slope
//!   +0.38→+0.86 with intercept 1.61→1.13 (the clone-out is a packed
//!   byte copy — costlier at scale, +0.97 decades, still linear);
//!   `party_encode` slope +0.21→+0.40 with intercept 2.50→1.61 (encode
//!   emits the stored bytes, −0.34 decades); `clock_encode` −0.15;
//!   `party_is_disjoint` +0.12 and `clock_fork` +0.06 (queries and id
//!   splits work over the packed form).
//! - **Fill and grow are one fused walk plus at most one splice** — the
//!   tick/transfer family cheapens at scale: `clock_tick` −0.35 decades
//!   (slope 1.15→1.06), `clock_send` −0.38, `clock_recv` −0.21,
//!   `version_tick` intercept 3.40→2.72 (slope 0.87→1.05).
//!
//! Every other band key moves under 0.05 decades.

/// One pinned band (see the module doc for the membership predicate).
#[derive(Debug, Clone, Copy)]
pub struct Band {
    /// The guest kernel this band prices (with `rejected`, the band key).
    pub kernel: &'static str,
    /// Whether this band prices the kernel's rejection arm (`ERR_OP`
    /// outcomes) rather than its success path.
    pub rejected: bool,
    /// Pinned log-log slope.
    pub slope: f64,
    /// Pinned intercept (`log₁₀` fuel at 1 bit).
    pub intercept: f64,
    /// Pinned ceiling width: max positive residual over the calibration
    /// corpus (the regression flag's threshold).
    pub width_above: f64,
    /// Pinned floor width: max negative residual magnitude over the
    /// calibration corpus (the liveness flag's threshold).
    pub width_below: f64,
    /// Smallest calibrated denominator (bits): the judgment floor.
    pub min_denom: u64,
    /// Largest calibrated denominator (bits), recorded for provenance.
    pub max_denom: u64,
    /// Calibration corpus size behind this band.
    pub samples: usize,
    /// Whether the band was constant-classified (slope pinned at 0).
    pub constant: bool,
}

/// Slack beyond each band's fitted ceiling, in `log₁₀` units.
///
/// Absorbs allocator-history variance between calibration and
/// enforcement contexts (≈ 1.6× in fuel). Measured at pin time
/// (`bin/calibrate` replays the enforcement suite's fixed escalation
/// programs — deterministic enforcement-context executions outside the
/// calibration corpus — and re-derives their worst ceiling excess on
/// every re-pin): the observed maximum is +0.040 decades (2026-07-26,
/// `ff_rank_cmp` at the depth-cap replay), so the margin sits 5× above
/// the honest enforcement-context excess. The ceiling carries the
/// regression claim, so its slack stays tight; contrast
/// [`ENFORCE_MARGIN_BELOW`].
pub const ENFORCE_MARGIN: f64 = 0.2;

/// Slack beyond each band's fitted floor, in `log₁₀` units.
///
/// The floor carries the liveness claim: a dead meter or an unmeasured
/// path reads at nop level, and every pinned floor still clears that
/// reading with this slack subtracted. Measured at pin time
/// (`bin/calibrate` re-derives the minimum on every re-pin): the
/// narrowest gap is 0.14 decades, `ff_rank_cmp` at its 128-bit fit floor
/// — its floor width carries the unequal-pair fast-path tail — and the
/// gap widens with size along every fitted slope from there. The slack
/// itself is priced against the honest cheap tail rather than the
/// dead-meter gap: fresh draws legitimately undercut the corpus
/// minimum — the committed rejection-shape seed's `join_all` step read
/// 0.29 below the pinned floor width at this margin's derivation
/// (2026-07-26) — and a liveness threshold left inside the honest
/// distribution's tail relocates that dispersion into flakiness.
pub const ENFORCE_MARGIN_BELOW: f64 = 1.0;

/// The staleness cross-check's prefix length.
///
/// The enforcement suite refits the first `REFIT_PREFIX_PROGRAMS`
/// programs of the deterministic calibration stream
/// (`drive::for_each_deterministic_program`) and compares each covered
/// band key's fresh line against its pin, so a pin the current code would
/// no longer produce fails loud instead of silently drifting. A prefix,
/// because a full-corpus refit would duplicate the calibration sweep
/// inside every suite run.
pub const REFIT_PREFIX_PROGRAMS: usize = 256;

/// Largest allowed [`crate::fit::line_divergence`] between the prefix
/// refit and the pin, in `log₁₀` units.
///
/// Measured 2026-07-26 at pin time (`bin/calibrate` re-derives the
/// evidence on every re-pin): the prefix's own sampling difference from
/// the full corpus peaks at 0.547 (`ff_party_join`'s rejection arm, the
/// thinnest-sampled band key). The tolerance sits above that, so the
/// check is deaf to sub-half-decade drift on the worst key but fails
/// loud on anything past ~5x in fuel constants — a staleness detector,
/// not the criterion of record.
pub const REFIT_TOLERANCE: f64 = 0.7;

/// Look up the pinned band for one band key (kernel × outcome).
pub fn band_for(kernel: &str, rejected: bool) -> Option<&'static Band> {
    BANDS
        .iter()
        .find(|b| b.kernel == kernel && b.rejected == rejected)
}

/// One step's verdict against a band.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Within the band: the pinned claim held for this step.
    InBand,
    /// Above the band: a regression flag (more work than the pinned law
    /// predicts for this size).
    Above,
    /// Below the band: a liveness flag (less work than any honest
    /// execution of this kernel performs — a dead meter or a measurement
    /// hole).
    Below,
    /// Below the calibrated floor: not judged (the line extrapolates the
    /// constant-overhead regime downward there).
    BelowFloor,
}

/// Judge one measured step against a band (the enforcement predicate; see
/// the module doc for its definition).
pub fn judge_against(band: &Band, denom_bits: u64, fuel: u64) -> Verdict {
    if denom_bits < band.min_denom {
        return Verdict::BelowFloor;
    }
    let predicted = band.intercept + band.slope * (denom_bits as f64).log10();
    let actual = (fuel.max(1) as f64).log10();
    if actual > predicted + band.width_above + ENFORCE_MARGIN {
        Verdict::Above
    } else if actual < predicted - band.width_below - ENFORCE_MARGIN_BELOW {
        Verdict::Below
    } else {
        Verdict::InBand
    }
}

/// The toolchain that pinned the constants below, as `rustc --version`
/// reports it.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: guest
/// codegen (and so every fuel constant) is a function of this compiler,
/// and the suite asserts the building toolchain matches, so a toolchain
/// bump reads red until the bands are re-pinned. wasmtime (the fuel
/// schedule's other half) is pinned exactly by the workspace
/// `Cargo.lock`; bumping it there is likewise a re-pin event.
pub const PINNED_RUSTC: &str = "rustc 1.96.1 (31fca3adb 2026-06-26)";

/// The pinned bands.
///
/// Generated by `just fuzzfit-calibrate` — review the diff like a
/// snapshot, commit with a dated movement annotation.
pub const BANDS: &[Band] = &[
    Band {
        kernel: "ff_clock_decode",
        rejected: false,
        slope: 1.085317,
        intercept: 2.030129,
        width_above: 0.148921,
        width_below: 0.100560,
        min_denom: 128,
        max_denom: 10760,
        samples: 561,
        constant: false,
    },
    Band {
        kernel: "ff_clock_encode",
        rejected: false,
        slope: 0.296457,
        intercept: 2.229961,
        width_above: 0.166921,
        width_below: 0.211788,
        min_denom: 129,
        max_denom: 10755,
        samples: 542,
        constant: false,
    },
    Band {
        kernel: "ff_clock_fork",
        rejected: false,
        slope: 0.893495,
        intercept: 1.768963,
        width_above: 0.233192,
        width_below: 0.222675,
        min_denom: 128,
        max_denom: 10862,
        samples: 35043,
        constant: false,
    },
    Band {
        kernel: "ff_clock_from_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.361728,
        width_above: 0.000000,
        width_below: 0.000000,
        min_denom: 129,
        max_denom: 10751,
        samples: 592,
        constant: false,
    },
    Band {
        kernel: "ff_clock_into_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.503791,
        width_above: 0.021254,
        width_below: 0.000000,
        min_denom: 128,
        max_denom: 10862,
        samples: 13603,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: false,
        slope: 0.998980,
        intercept: 2.614492,
        width_above: 0.299104,
        width_below: 1.327747,
        min_denom: 128,
        max_denom: 21318,
        samples: 9719,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: true,
        slope: 1.369620,
        intercept: 0.217426,
        width_above: 0.334513,
        width_below: 0.817709,
        min_denom: 131,
        max_denom: 21510,
        samples: 146,
        constant: false,
    },
    Band {
        kernel: "ff_clock_own_version",
        rejected: false,
        slope: 1.044111,
        intercept: 2.464348,
        width_above: 0.137339,
        width_below: 0.145785,
        min_denom: 128,
        max_denom: 13116,
        samples: 422,
        constant: false,
    },
    Band {
        kernel: "ff_clock_recv",
        rejected: false,
        slope: 1.004318,
        intercept: 2.910700,
        width_above: 0.239958,
        width_below: 0.421768,
        min_denom: 128,
        max_denom: 18460,
        samples: 2061,
        constant: false,
    },
    Band {
        kernel: "ff_clock_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 3.136434,
        width_above: 0.007517,
        width_below: 0.002895,
        min_denom: 8,
        max_denom: 8,
        samples: 1704,
        constant: true,
    },
    Band {
        kernel: "ff_clock_send",
        rejected: false,
        slope: 1.036240,
        intercept: 2.724858,
        width_above: 0.204881,
        width_below: 0.243115,
        min_denom: 128,
        max_denom: 10748,
        samples: 1196,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: false,
        slope: 1.012981,
        intercept: 2.588595,
        width_above: 0.287568,
        width_below: 1.081151,
        min_denom: 128,
        max_denom: 21622,
        samples: 573,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: true,
        slope: 1.388618,
        intercept: 0.161252,
        width_above: 0.822660,
        width_below: 0.843331,
        min_denom: 133,
        max_denom: 20438,
        samples: 153,
        constant: false,
    },
    Band {
        kernel: "ff_clock_tick",
        rejected: false,
        slope: 1.059618,
        intercept: 2.634274,
        width_above: 0.287969,
        width_below: 0.197001,
        min_denom: 128,
        max_denom: 10862,
        samples: 119863,
        constant: false,
    },
    Band {
        kernel: "ff_clock_version",
        rejected: false,
        slope: 0.862102,
        intercept: 1.130704,
        width_above: 0.126028,
        width_below: 0.075730,
        min_denom: 128,
        max_denom: 10867,
        samples: 4320,
        constant: false,
    },
    Band {
        kernel: "ff_party_covers",
        rejected: false,
        slope: 1.073875,
        intercept: 1.590856,
        width_above: 0.158118,
        width_below: 1.378046,
        min_denom: 128,
        max_denom: 9140,
        samples: 900,
        constant: false,
    },
    Band {
        kernel: "ff_party_decode",
        rejected: false,
        slope: 0.977831,
        intercept: 1.875171,
        width_above: 0.040409,
        width_below: 0.027452,
        min_denom: 128,
        max_denom: 4536,
        samples: 638,
        constant: false,
    },
    Band {
        kernel: "ff_party_display",
        rejected: false,
        slope: 0.935486,
        intercept: 1.431324,
        width_above: 0.096767,
        width_below: 0.051236,
        min_denom: 136,
        max_denom: 66018,
        samples: 1801,
        constant: false,
    },
    Band {
        kernel: "ff_party_encode",
        rejected: false,
        slope: 0.396773,
        intercept: 1.609275,
        width_above: 0.237758,
        width_below: 0.248906,
        min_denom: 128,
        max_denom: 4530,
        samples: 592,
        constant: false,
    },
    Band {
        kernel: "ff_party_fork",
        rejected: false,
        slope: 0.883459,
        intercept: 2.199568,
        width_above: 0.041488,
        width_below: 0.035166,
        min_denom: 132,
        max_denom: 4478,
        samples: 251,
        constant: false,
    },
    Band {
        kernel: "ff_party_forks",
        rejected: false,
        slope: 0.896541,
        intercept: 2.441546,
        width_above: 0.090418,
        width_below: 0.213360,
        min_denom: 128,
        max_denom: 4246,
        samples: 451,
        constant: false,
    },
    Band {
        kernel: "ff_party_fromstr",
        rejected: false,
        slope: 0.978951,
        intercept: 1.384265,
        width_above: 0.150331,
        width_below: 0.059407,
        min_denom: 136,
        max_denom: 66018,
        samples: 1801,
        constant: false,
    },
    Band {
        kernel: "ff_party_is_disjoint",
        rejected: false,
        slope: 1.197944,
        intercept: 1.026752,
        width_above: 0.420297,
        width_below: 1.103763,
        min_denom: 128,
        max_denom: 9140,
        samples: 900,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: false,
        slope: 1.236760,
        intercept: 1.610607,
        width_above: 0.326332,
        width_below: 0.766636,
        min_denom: 128,
        max_denom: 7678,
        samples: 13369,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: true,
        slope: 1.479444,
        intercept: 0.410966,
        width_above: 0.455460,
        width_below: 0.908277,
        min_denom: 132,
        max_denom: 9140,
        samples: 143,
        constant: false,
    },
    Band {
        kernel: "ff_party_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 2.694796,
        width_above: 0.024536,
        width_below: 0.001949,
        min_denom: 8,
        max_denom: 8,
        samples: 112,
        constant: true,
    },
    Band {
        kernel: "ff_party_without",
        rejected: false,
        slope: 0.817774,
        intercept: 2.176055,
        width_above: 0.042115,
        width_below: 0.041285,
        min_denom: 146,
        max_denom: 4260,
        samples: 119,
        constant: false,
    },
    Band {
        kernel: "ff_party_without",
        rejected: true,
        slope: 1.320749,
        intercept: 1.109486,
        width_above: 0.331035,
        width_below: 0.189954,
        min_denom: 134,
        max_denom: 8896,
        samples: 124,
        constant: false,
    },
    Band {
        kernel: "ff_rank_add",
        rejected: false,
        slope: 0.408880,
        intercept: 2.149224,
        width_above: 0.229051,
        width_below: 0.208956,
        min_denom: 128,
        max_denom: 7072,
        samples: 645,
        constant: false,
    },
    Band {
        kernel: "ff_rank_checked_sub",
        rejected: false,
        slope: 0.496816,
        intercept: 1.737789,
        width_above: 0.351084,
        width_below: 0.179276,
        min_denom: 128,
        max_denom: 7072,
        samples: 669,
        constant: false,
    },
    Band {
        kernel: "ff_rank_checked_sub",
        rejected: true,
        slope: -0.126481,
        intercept: 2.737357,
        width_above: 0.347597,
        width_below: 0.210763,
        min_denom: 128,
        max_denom: 2488,
        samples: 111,
        constant: false,
    },
    Band {
        kernel: "ff_rank_cmp",
        rejected: false,
        slope: 0.568911,
        intercept: 1.382535,
        width_above: 0.248475,
        width_below: 1.141284,
        min_denom: 128,
        max_denom: 7072,
        samples: 390,
        constant: false,
    },
    Band {
        kernel: "ff_rank_display",
        rejected: false,
        slope: 1.096063,
        intercept: 0.745250,
        width_above: 0.231471,
        width_below: 0.128363,
        min_denom: 128,
        max_denom: 7072,
        samples: 390,
        constant: false,
    },
    Band {
        kernel: "ff_version_cmp",
        rejected: false,
        slope: 1.148473,
        intercept: 1.773445,
        width_above: 0.345618,
        width_below: 0.930389,
        min_denom: 128,
        max_denom: 15574,
        samples: 1844,
        constant: false,
    },
    Band {
        kernel: "ff_version_concurrent",
        rejected: false,
        slope: 1.148557,
        intercept: 1.773109,
        width_above: 0.345762,
        width_below: 0.930268,
        min_denom: 128,
        max_denom: 15574,
        samples: 1844,
        constant: false,
    },
    Band {
        kernel: "ff_version_decode",
        rejected: false,
        slope: 1.168578,
        intercept: 1.779372,
        width_above: 0.350960,
        width_below: 0.420214,
        min_denom: 128,
        max_denom: 7792,
        samples: 1200,
        constant: false,
    },
    Band {
        kernel: "ff_version_display",
        rejected: false,
        slope: 0.971522,
        intercept: 1.922572,
        width_above: 0.131296,
        width_below: 0.127295,
        min_denom: 141,
        max_denom: 99746,
        samples: 2142,
        constant: false,
    },
    Band {
        kernel: "ff_version_distance",
        rejected: false,
        slope: 1.084689,
        intercept: 2.833888,
        width_above: 0.335926,
        width_below: 0.461103,
        min_denom: 128,
        max_denom: 15574,
        samples: 1790,
        constant: false,
    },
    Band {
        kernel: "ff_version_encode",
        rejected: false,
        slope: 0.421901,
        intercept: 1.522231,
        width_above: 0.274911,
        width_below: 0.240563,
        min_denom: 128,
        max_denom: 7787,
        samples: 1174,
        constant: false,
    },
    Band {
        kernel: "ff_version_fromstr",
        rejected: false,
        slope: 0.965723,
        intercept: 2.136232,
        width_above: 0.105503,
        width_below: 0.083331,
        min_denom: 141,
        max_denom: 99746,
        samples: 2142,
        constant: false,
    },
    Band {
        kernel: "ff_version_join",
        rejected: false,
        slope: 1.012960,
        intercept: 2.665293,
        width_above: 0.239717,
        width_below: 2.691654,
        min_denom: 128,
        max_denom: 12998,
        samples: 2183,
        constant: false,
    },
    Band {
        kernel: "ff_version_join_all",
        rejected: false,
        slope: 1.143021,
        intercept: 2.866135,
        width_above: 0.347591,
        width_below: 1.989907,
        min_denom: 129,
        max_denom: 166296,
        samples: 1264,
        constant: false,
    },
    Band {
        kernel: "ff_version_lag",
        rejected: false,
        slope: 1.092954,
        intercept: 2.622308,
        width_above: 0.372833,
        width_below: 0.475274,
        min_denom: 128,
        max_denom: 15574,
        samples: 1790,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet",
        rejected: false,
        slope: 1.035571,
        intercept: 2.575154,
        width_above: 0.304598,
        width_below: 2.874861,
        min_denom: 128,
        max_denom: 15222,
        samples: 1207,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet_all",
        rejected: false,
        slope: 1.054679,
        intercept: 1.953776,
        width_above: 0.890553,
        width_below: 1.068236,
        min_denom: 128,
        max_denom: 114722,
        samples: 436,
        constant: false,
    },
    Band {
        kernel: "ff_version_min_ticks",
        rejected: false,
        slope: 1.140846,
        intercept: 2.100550,
        width_above: 0.328267,
        width_below: 0.503559,
        min_denom: 128,
        max_denom: 7322,
        samples: 1120,
        constant: false,
    },
    Band {
        kernel: "ff_version_project",
        rejected: false,
        slope: 0.864654,
        intercept: 2.917865,
        width_above: 0.578856,
        width_below: 0.410136,
        min_denom: 128,
        max_denom: 42083,
        samples: 1594,
        constant: false,
    },
    Band {
        kernel: "ff_version_rank",
        rejected: false,
        slope: 1.155152,
        intercept: 2.050245,
        width_above: 0.372297,
        width_below: 0.436074,
        min_denom: 128,
        max_denom: 7787,
        samples: 2266,
        constant: false,
    },
    Band {
        kernel: "ff_version_tick",
        rejected: false,
        slope: 1.054042,
        intercept: 2.724168,
        width_above: 0.256098,
        width_below: 0.466529,
        min_denom: 128,
        max_denom: 12185,
        samples: 964,
        constant: false,
    },
];

/// The band keys the pin-time prefix refit covered: the staleness
/// cross-check's committed expectation list.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: every key
/// listed here had, at pin time, a prefix refit whose classification
/// matched its pin. The enforcement suite requires each listed key to
/// still fit, still match its pin's classification, and still agree
/// within [`REFIT_TOLERANCE`] — so coverage decay, a classification flip
/// (the reach-regression tell), and line drift each fail by name instead
/// of hollowing the check out silently. Keys not listed are outside the
/// staleness detector's reach at pin time; calibration prints them for
/// the re-pinner to review.
pub const REFIT_COVERAGE: &[(&str, bool)] = &[
    ("ff_clock_decode", false),
    ("ff_clock_encode", false),
    ("ff_clock_fork", false),
    ("ff_clock_from_parts", false),
    ("ff_clock_into_parts", false),
    ("ff_clock_join", false),
    ("ff_clock_join", true),
    ("ff_clock_own_version", false),
    ("ff_clock_recv", false),
    ("ff_clock_seed", false),
    ("ff_clock_send", false),
    ("ff_clock_sync", false),
    ("ff_clock_sync", true),
    ("ff_clock_tick", false),
    ("ff_clock_version", false),
    ("ff_party_covers", false),
    ("ff_party_decode", false),
    ("ff_party_display", false),
    ("ff_party_encode", false),
    ("ff_party_fork", false),
    ("ff_party_forks", false),
    ("ff_party_fromstr", false),
    ("ff_party_is_disjoint", false),
    ("ff_party_join", false),
    ("ff_party_join", true),
    ("ff_party_seed", false),
    ("ff_party_without", false),
    ("ff_party_without", true),
    ("ff_rank_add", false),
    ("ff_rank_checked_sub", false),
    ("ff_rank_cmp", false),
    ("ff_rank_display", false),
    ("ff_version_cmp", false),
    ("ff_version_concurrent", false),
    ("ff_version_decode", false),
    ("ff_version_display", false),
    ("ff_version_distance", false),
    ("ff_version_encode", false),
    ("ff_version_fromstr", false),
    ("ff_version_join", false),
    ("ff_version_join_all", false),
    ("ff_version_lag", false),
    ("ff_version_meet", false),
    ("ff_version_meet_all", false),
    ("ff_version_min_ticks", false),
    ("ff_version_project", false),
    ("ff_version_rank", false),
    ("ff_version_tick", false),
];
