//! Pinned per-operation fuel bands: the calibration leg's committed output.
//!
//! [`BANDS`] is generated by `bin/calibrate` (which rewrites this file
//! atomically) and committed; the enforcement leg judges against these
//! constants and never refits. To re-pin — after a deliberate guest
//! toolchain bump, a kernel change, or a strategy change — run
//! `just fuzzfit-calibrate`, review the diff like a snapshot, and commit
//! with a dated movement annotation.
//!
//! The band key is **kernel × outcome**: an operation with a rejection arm
//! (`join`/`sync` on overlap, `without` on emptiness, `checked_sub` on
//! underflow) gets one band for its success path and one for its rejection
//! path. The two are different mechanisms with different cost laws — a
//! rejection can legitimately undercut the success line by decades (early
//! overlap detection), and pricing both from one pooled cloud lets a
//! superlinear regression in either arm hide under the other's ceiling.
//!
//! Band semantics: a step of kernel `k` with denominator `d` bits and fuel
//! `f` is in-band iff, writing `r = log₁₀ f − (intercept + slope · log₁₀ d)`,
//!
//! ```text
//! −(width_below + ENFORCE_MARGIN_BELOW) ≤ r ≤ width_above + ENFORCE_MARGIN
//! ```
//!
//! judged only for `d ≥ min_denom` (below the calibrated range the line
//! extrapolates the intercept's constant overhead downward, which
//! false-flags genuinely cheap small cases; the rare fresh draw above
//! `max_denom` is judged against the extrapolated line — but enforcement
//! shares the calibration leg's generators and budgets, so the catching
//! power lives *inside* the calibrated span, which is why the ceiling is
//! priced from the positive residuals alone and the reach families exist).
//! Above-band is a regression flag; below-band is a liveness flag (a dead
//! fuel meter or an accidentally-constant kernel reads below its own band,
//! never silently green). The two widths are priced separately because the
//! residual cloud is one-sidedly heavy — see [`crate::fit`].
//!
//! # Pin of record
//!
//! Re-pinned 2026-07-30 at the Bytes-backed at-rest form (`codec::Bits`
//! over a refcounted byte buffer: clones are refcount bumps, the empty
//! version and the seed id are static buffers, and the identity-law
//! fast paths dispatch on clone identity). Attribution is
//! parent-measured, fit against fit (a fresh parent calibration at
//! 3a4f3c8e moved every band only at the third decimal — fit wobble —
//! with `ff_clock_seed` unmoved). Three movements are the change's own
//! mechanisms: `ff_clock_seed` intercept 3.136 → 2.228 (the seed
//! allocates nothing off the static streams; ~1,369 → ~169 fuel),
//! `ff_party_seed` intercept 2.695 → 2.196 (same mechanism), and
//! `ff_clock_version` slope 0.865 → 0.000 with intercept 1.122 → 2.401
//! (the accessor's version clone is a refcount bump, so the kernel is
//! flat — the old size law was the clone's byte copy). Alongside the
//! re-fit, pair steps whose operands dispatch an identity-law fast
//! path (clone-shared buffers under cmp/concurrent, equal values under
//! distance/lag/join/meet) leave the sample stream (`Step::identity`):
//! their cost is `O(1)` by mechanism, not a size law, and fitting them
//! alongside the walked cloud would smear both bands decoration-wide —
//! their liveness is owned by before's `identity_fast_paths` meter
//! pins. Every other band key moved at the second decimal or below —
//! clone-cost constants inside the clock composites (fork/send/recv
//! hand a version over by refcount now) and the parent refit's own
//! wobble band.
//!
//! Re-pinned 2026-07-29 at the fused sync (`Clock::sync`'s party leg
//! is one sum-split walk: the union's spine read in lockstep off both
//! operands, the branch children delegated to `sum` or spliced
//! verbatim where one side alone owns them; `sum` and `split`
//! themselves are untouched). Attribution is parent-measured, fit
//! against fit (a fresh parent calibration reproduced the committed
//! pin byte-identically before the change): 24 of 48 band keys moved.
//! The sync arms are the change's own mechanism — `ff_clock_sync`
//! success slope 1.0062 → 0.9971 (intercept +0.0049: the fused walk
//! undercuts the composition as operands grow), and its rejection
//! arm's intercept 0.2897 → 0.0498 (−0.24 decades, ~42% fuel at the
//! fit line, slope −0.012: an overlap refusal is now the walk's own
//! early full-meets-nonempty exit, with none of the join-and-hand-back
//! plumbing around it). Every other movement is guest code layout from
//! `sum` and `split` gaining a second caller (inlining shifts — their
//! own algorithms are byte-untouched, and every non-sync board counter
//! reading is byte-identical to the parent at both scales):
//! `ff_party_join` slope +0.0197 with intercept −0.0174 and its
//! rejection arm's intercept +0.0809, `ff_clock_join` rejection slope
//! +0.0216 with intercept +0.0119, the fork trio's intercepts +0.0106
//! to +0.0140, and everything else at the third decimal or below. The
//! enforcement leg held green at the previous pin before the re-fit.
//!
//! Re-pinned 2026-07-29 at the overlay migration (the remaining
//! hand-rolled overlay advances — projection, the masked walk's n-ary
//! loop, the id difference — onto the plateau-cursor law, plus the
//! shared two-skyline opening whose unread opening-height buffers now
//! drop at the destructure instead of living to function end). Every
//! deterministic limb, scan, touch, and segment reading held
//! byte-identical at both board scales against the parent; the heap
//! column alone moved, per-byte transient-peak constants down on the
//! wide-opening families (the freed opening buffers) with
//! second-decimal exponent wobble from the reduced peaks, zero verdict
//! flips, and the worst-case pin clean. Attribution is parent-measured,
//! fit against fit (a fresh parent calibration reproduced the committed
//! pin byte-identically before the change): 29 of 49 band keys moved,
//! every slope and intercept at the third decimal or below, and every
//! width leg likewise except the comparison pair's below-line widths,
//! which narrowed (`ff_version_cmp` −0.0115, `ff_version_concurrent`
//! −0.0116: the re-fit's one-sided residual cloud pulled in from
//! below, tightening the liveness allowance). The walk kernels'
//! constants:
//! `ff_version_cmp`/`ff_version_concurrent` intercepts
//! +0.0053/+0.0052 (~1.2% fuel at the fit line, slopes −0.0014),
//! `ff_version_project` +0.0047, `ff_version_lag` +0.0032,
//! `ff_version_distance` +0.0028, join/meet and their n-ary folds
//! +0.0019 to +0.0028, `ff_party_without` +0.0011 (its rejection arm
//! +0.0002), with `ff_version_rank`, `ff_version_min_ticks`, and
//! `ff_version_tick` unmoved past the fourth decimal. The single
//! largest constant movement is an untouched kernel — `ff_rank_add`
//! intercept +0.0099 at slope −0.0034, Rank addition, which shares
//! nothing with the walk seam — so that scale of residue is guest code
//! layout from the recompile, and the walk kernels' own constant
//! movement sits at or under the ~1.2% pair. The enforcement leg held
//! green at the previous pin before the re-fit.
//!
//! Re-pinned 2026-07-29 at the overlay-advance unification (the
//! plateau-cursor trait and the one generic binary `advance` in
//! `version/skyline/sweep.rs`, traversal separated from algebra: the
//! cursors yield their crossings and the clients fold them). Every
//! value and every deterministic meter reading held byte-identical —
//! the amplification board renders byte-identically at both scales of
//! record against the parent — so the movement here is instruction
//! count alone, code layout from the guest recompile. Attribution is
//! parent-measured, fit against fit at the parent and the tip: this
//! change moved 15 bands, all at the third decimal or below — the
//! largest is the comparison pair's intercept (+0.005 decades, ~1.1%
//! fuel at the fit line: `ff_version_cmp` 1.7557 → 1.7606,
//! `ff_version_concurrent` 1.7579 → 1.7627, at slopes −0.0009 and
//! −0.0008), then the pair integrals' intercepts
//! (`ff_version_distance` +0.0022, `ff_version_lag` +0.0024), with
//! every other movement — join, meet, rank, min_ticks, project, and
//! the clock compositions — at ±0.0015 or below (largest
//! `ff_version_meet` intercept −0.0014). The diff on top of the
//! committed pin is larger than that: 24 bands carried pre-existing
//! drift from the rounds since the first-freeze pin below, which held
//! enforcement green without recalibrating (largest
//! `ff_version_encode` width_above +0.099 and `ff_version_fromstr`
//! intercept +0.024, neither a sweep kernel; the sweep kernels' own
//! drift tops out at ±0.0016, `ff_version_min_ticks`
//! width_below) — this re-pin absorbs that drift, and
//! the numbers above are this change's own movement only. The
//! enforcement leg held green at the previous pin before the re-fit.
//!
//! Re-pinned 2026-07-29 at the first-freeze segment gate (round #87:
//! the query integrator's segment and window feeds open at the first
//! freeze, so never-freezing sweeps — most of the organic corpus —
//! deposit no interval mass; same corpus, toolchain, and strategy as
//! the cluster-delegated pin below, the movement is the kernels'):
//! the linear-functional trio's intercepts dropped with slopes
//! marginally flatter — `ff_version_rank` 2.095 → 2.046 (−0.049
//! decades, ~11% fuel at the fit line) at slope 1.1289 → 1.1274,
//! `ff_version_distance` 2.206 → 2.179 at slope −0.0006,
//! `ff_version_lag` 2.155 → 2.130 at slope −0.0017 — and
//! `ff_version_min_ticks` wobbled at the sixth decimal with every
//! other band at the third or below (code layout from the guest
//! recompile; the min_ticks fold does not ride the integrator). The
//! enforcement leg held green at the previous pin before the re-fit.
//!
//! Re-pinned 2026-07-28 at the cluster-delegated settle (the settle
//! products through the backend's multiplication, mass-balanced
//! ledger tree; same corpus, toolchain, and strategy as the meet-fold
//! pin below — the movement is the kernels'): every enforcement leg
//! held at the previous pin without a trip, and the re-fit moved one
//! band at the sixth decimal — `ff_version_min_ticks` slope
//! 1.097606 → 1.097638 — with the linear-functional trio
//! byte-identical: the organic corpus rarely arms the ledger, its
//! settles sit inside the pinned tolerances, and min_ticks' wobble is
//! code layout alone (its own kernels are untouched; `mul_into` lost
//! its query-settle callers, which moves inlining, not work).
//!
//! Re-pinned 2026-07-28 at the balanced meet fold and the window-digit
//! combine tap (same corpus, toolchain, and strategy as the
//! product-tree pin below — the movement is the kernels'):
//! `ff_version_meet_all` slope 1.020 → 1.109 with intercept
//! 2.068 → 2.491 and width_above 0.897 → 0.289 — the fold left the
//! sequential reduce for the join folds' balanced binary counter, so
//! its organic law now sits at `ff_version_join_all`'s shape (slope
//! 1.144) with a much tighter ceiling: the wide positive residuals
//! were the reduce's non-shrinking-accumulator re-walks, exactly what
//! the cure forecloses (its committed adversarial record is the
//! `meet_fold` band and tripwire, `tests/meter.rs`; this band prices
//! the organic corpus). `ff_version_join_all` width_below
//! 2.03 → 2.39 (the shared reduction's drain starts from the heaviest
//! group instead of folding from the empty identity, so the cheapest
//! draws got cheaper); the linear-functional trio and every other
//! band moved at the third decimal or below (the guest builds
//! `before` at default features, so the combine tap compiles to
//! nothing there — any fuel movement from it is code layout alone).
//!
//! Re-pinned 2026-07-28 at the balanced product-tree ledger settle
//! (same corpus, toolchain, and strategy as the #78 pin below — the
//! movement is the kernels'): the linear-functional trio moved at the
//! fourth decimal (`ff_version_rank` slope 1.1291 → 1.1289 with
//! intercept +0.0006, `ff_version_distance` and `ff_version_lag`
//! alike) — the corpus's organic draws rarely promote, so the settle's
//! tree registers only at the margin — and `ff_version_min_ticks`
//! drifted at the same decimal with them (guest codegen layout from
//! the query module's new settle code, not a kernel change; the
//! min_ticks fold does not ride the integrator). No width moved past
//! the third decimal; the staleness leg stayed green through the cure.
//!
//! Re-pinned 2026-07-28 at the cure round #78 merge (same corpus,
//! toolchain, and strategy as the 2026-07-27 pin below — the movement is
//! the kernels'): `ff_version_min_ticks` slope 1.123 → 1.098 with
//! intercept 2.176 → 2.568 — the anchor-web fold's trade, a flatter law
//! bought with ~0.39 decades of small-operand setup (the prior law
//! read the retired pending-minima fold, and the new fold's ~180k fuel
//! at 167 bits sat 1.7× over the stale ceiling); `ff_version_rank`
//! +0.05 decades intercept at a marginally flatter slope (the
//! anchored-segment integrator); every other band moved at the third
//! decimal (the zero-run ledger's per-write upkeep riding every
//! accumulator kernel).
//!
//! Pinned 2026-07-27: corpus 4096 programs (~2.64M measured steps), guest
//! at wasm32-unknown-unknown release (codegen-units 1, panic=abort) under
//! the toolchain in [`PINNED_RUSTC`], wasmtime 47 fuel. 49 band keys: 44
//! kernels, of which five have sampled rejection arms (`clock_join` and
//! `clock_sync` on overlap, `party_join` on overlap, `party_without` on
//! emptiness, `rank_checked_sub` on underflow). The one deliberately
//! unpriced outcome is `meet_all([])`'s `None`: production-reachable but
//! structurally constant — no operand exists, so there is nothing for a
//! regression to scale with and nothing to denominate a cost against.
//!
//! All 49 band keys read linear-or-flatter within every family above the
//! 128-bit fit floor — the within-case shape diagnostic's maximum healthy
//! excess over the whole corpus is +0.081 (see [`crate::curve`]) — while
//! the pooled envelope slopes above 1.1 remain the documented
//! family-mixture composition (families' per-bit cost levels differ
//! severalfold and the cheap families' mass sits in the small buckets,
//! tilting a pooled envelope no single family follows; every lane's own
//! medians are flat or falling, and `bin/diag` per family is the
//! ground-truth view). The rejection envelopes (1.36–1.42:
//! `clock_join`, `clock_sync`, `party_join`, and `party_without`'s
//! emptiness arm) are the same genre at smaller n: cheap early
//! rejections dominate the small buckets — immediate overlap detection
//! on the join/sync arms, covered operands settled in one block scan
//! on the emptiness arm — while the full-scan rejections hold the top,
//! where each arm's own per-bit medians read flat; legitimate full-scan
//! rejections at small n price inside each arm's own ceiling width.
//! `party_without`'s success arm reads sublinear (0.72) as the mirror
//! of the same mixture: the sweep's covered-block early exits win
//! proportionally more at scale, and the arm's per-bit medians fall
//! monotonically along the whole calibrated span.
//! `rank_checked_sub`'s underflow arm reads flat (−0.02): the
//! ordering pre-check settles the outcome before any alignment work, so
//! its cost does not grow with the operands. `ff_version_join_all` 1.143
//! carries the balanced fold's documented log factor along the width
//! ladder (fold width is budget-capped, so the factor is bounded and the
//! band prices it).
//!
//! Movement against the previous pin (2026-07-27, the DsiCursor pin),
//! by mechanism. This re-pin is the #72 merge round's owner-approved
//! evidence widening: the corpus of record grew 1536 → 4096 programs
//! (~985k → ~2.64M steps) with no guest, generator, strategy, or
//! toolchain change riding along, so the lines replay within sampling
//! noise (slopes move in the third decimal) and every movement is
//! evidence, not fuel:
//!
//! - **The rejection arms learned the full-scan genre at small
//!   denominators.** Tripled evidence on every rejection band
//!   (`clock_join` [err] 146 → 409 samples) prices the genre the old
//!   corpus under-sampled: a legitimate full-scan rejection at small n
//!   sits above the cheap-early-detection line that dominates the small
//!   buckets, and the widened corpus draws enough of them that the
//!   ceiling learns their spread (`clock_join` [err] width_above
//!   0.335 → 0.550, slope 1.370 → 1.374 — the committed enforcement
//!   sentry seed, a 139-bit full-scan overlap rejection at 6805 fuel,
//!   prices in-band under this pin; it was the escape that motivated
//!   the widening).
//! - **Floor widths widen where the new draws populate cheap tails**
//!   (`rank_cmp` width_below 1.141 → 1.455, `clock_join` success
//!   1.305 → 1.490): more small-denominator mass, honest dispersion,
//!   no slope movement.

/// One pinned band (see the module doc for the membership predicate).
#[derive(Debug, Clone, Copy)]
pub struct Band {
    /// The guest kernel this band prices (with `rejected`, the band key).
    pub kernel: &'static str,
    /// Whether this band prices the kernel's rejection arm (`ERR_OP`
    /// outcomes) rather than its success path.
    pub rejected: bool,
    /// Pinned log-log slope.
    pub slope: f64,
    /// Pinned intercept (`log₁₀` fuel at 1 bit).
    pub intercept: f64,
    /// Pinned ceiling width: max positive residual over the calibration
    /// corpus (the regression flag's threshold).
    pub width_above: f64,
    /// Pinned floor width: max negative residual magnitude over the
    /// calibration corpus (the liveness flag's threshold).
    pub width_below: f64,
    /// Smallest calibrated denominator (bits): the judgment floor.
    pub min_denom: u64,
    /// Largest calibrated denominator (bits), recorded for provenance.
    pub max_denom: u64,
    /// Calibration corpus size behind this band.
    pub samples: usize,
    /// Whether the band was constant-classified (slope pinned at 0).
    pub constant: bool,
}

/// Slack beyond each band's fitted ceiling, in `log₁₀` units.
///
/// Absorbs allocator-history variance between calibration and
/// enforcement contexts (≈ 1.6× in fuel). Measured at pin time
/// (`bin/calibrate` replays the enforcement suite's fixed escalation
/// programs — deterministic enforcement-context executions outside the
/// calibration corpus — and re-derives their worst ceiling excess on
/// every re-pin): the observed maximum is +0.023 decades (2026-07-27,
/// `ff_version_project` at the depth-1792 escalation replay), so the
/// margin sits ~9× above the honest enforcement-context excess. The ceiling carries the
/// regression claim, so its slack stays tight; contrast
/// [`ENFORCE_MARGIN_BELOW`].
pub const ENFORCE_MARGIN: f64 = 0.2;

/// Slack beyond each band's fitted floor, in `log₁₀` units.
///
/// The floor carries the liveness claim: a dead meter or an unmeasured
/// path reads at nop level, and every pinned floor still clears that
/// reading with this slack subtracted. Measured at pin time
/// (`bin/calibrate` re-derives the minimum on every re-pin, 2026-07-27,
/// the 4096-program corpus): the narrowest gap is 0.11 decades,
/// `ff_rank_cmp` at its 128-bit fit floor — its floor width carries the
/// unequal-pair fast-path tail, widened by the corpus's extra
/// small-denominator mass — and the gap widens with size along every
/// fitted slope from there. The slack sits between two measured edges:
/// below the dead-meter gap (at 1.0 the `ff_rank_cmp` floor dipped
/// 0.087 decades under nop level, voiding the liveness claim on that
/// key), and above the honest cheap tail (fresh draws legitimately
/// undercut the corpus minimum — the committed rejection-shape seed's
/// `join_all` step read 0.29 below the pinned floor width at this
/// margin's original derivation, 2026-07-26 — because a liveness
/// threshold left inside the honest distribution's tail relocates that
/// dispersion into flakiness).
pub const ENFORCE_MARGIN_BELOW: f64 = 0.8;

/// The staleness cross-check's prefix length.
///
/// The enforcement suite refits the first `REFIT_PREFIX_PROGRAMS`
/// programs of the deterministic calibration stream
/// (`drive::for_each_deterministic_program`) and compares each covered
/// band key's fresh line against its pin, so a pin the current code would
/// no longer produce fails loud instead of silently drifting. A prefix,
/// because a full-corpus refit would duplicate the calibration sweep
/// inside every suite run.
pub const REFIT_PREFIX_PROGRAMS: usize = 256;

/// Largest allowed [`crate::fit::line_divergence`] between the prefix
/// refit and the pin, in `log₁₀` units.
///
/// Measured 2026-07-27 at pin time (`bin/calibrate` re-derives the
/// evidence on every re-pin; the 4096-program corpus): the prefix's own
/// sampling difference from the full corpus peaks at 0.489
/// (`ff_party_join`'s rejection arm, the thinnest-sampled band key
/// genre). The tolerance sits above that, so the
/// check is deaf to sub-half-decade drift on the worst key but fails
/// loud on anything past ~5x in fuel constants — a staleness detector,
/// not the criterion of record.
pub const REFIT_TOLERANCE: f64 = 0.7;

/// Look up the pinned band for one band key (kernel × outcome).
pub fn band_for(kernel: &str, rejected: bool) -> Option<&'static Band> {
    BANDS
        .iter()
        .find(|b| b.kernel == kernel && b.rejected == rejected)
}

/// One step's verdict against a band.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Within the band: the pinned claim held for this step.
    InBand,
    /// Above the band: a regression flag (more work than the pinned law
    /// predicts for this size).
    Above,
    /// Below the band: a liveness flag (less work than any honest
    /// execution of this kernel performs — a dead meter or a measurement
    /// hole).
    Below,
    /// Below the calibrated floor: not judged (the line extrapolates the
    /// constant-overhead regime downward there).
    BelowFloor,
}

/// Judge one measured step against a band (the enforcement predicate; see
/// the module doc for its definition).
pub fn judge_against(band: &Band, denom_bits: u64, fuel: u64) -> Verdict {
    if denom_bits < band.min_denom {
        return Verdict::BelowFloor;
    }
    let predicted = band.intercept + band.slope * (denom_bits as f64).log10();
    let actual = (fuel.max(1) as f64).log10();
    if actual > predicted + band.width_above + ENFORCE_MARGIN {
        Verdict::Above
    } else if actual < predicted - band.width_below - ENFORCE_MARGIN_BELOW {
        Verdict::Below
    } else {
        Verdict::InBand
    }
}

/// The toolchain that pinned the constants below, as `rustc --version`
/// reports it.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: guest
/// codegen (and so every fuel constant) is a function of this compiler,
/// and the suite asserts the building toolchain matches, so a toolchain
/// bump reads red until the bands are re-pinned. wasmtime (the fuel
/// schedule's other half) is pinned exactly by the workspace
/// `Cargo.lock`; bumping it there is likewise a re-pin event.
pub const PINNED_RUSTC: &str = "rustc 1.96.1 (31fca3adb 2026-06-26)";

/// The pinned bands.
///
/// Generated by `just fuzzfit-calibrate` — review the diff like a
/// snapshot, commit with a dated movement annotation.
pub const BANDS: &[Band] = &[
    Band {
        kernel: "ff_clock_decode",
        rejected: false,
        slope: 1.064549,
        intercept: 2.029586,
        width_above: 0.113588,
        width_below: 0.155161,
        min_denom: 128,
        max_denom: 12160,
        samples: 1531,
        constant: false,
    },
    Band {
        kernel: "ff_clock_encode",
        rejected: false,
        slope: 0.319619,
        intercept: 2.144816,
        width_above: 0.184922,
        width_below: 0.238259,
        min_denom: 128,
        max_denom: 12155,
        samples: 1480,
        constant: false,
    },
    Band {
        kernel: "ff_clock_fork",
        rejected: false,
        slope: 0.872990,
        intercept: 1.780458,
        width_above: 0.244686,
        width_below: 0.349853,
        min_denom: 128,
        max_denom: 12234,
        samples: 94548,
        constant: false,
    },
    Band {
        kernel: "ff_clock_from_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.414973,
        width_above: 0.000000,
        width_below: 0.000000,
        min_denom: 128,
        max_denom: 12151,
        samples: 1663,
        constant: false,
    },
    Band {
        kernel: "ff_clock_into_parts",
        rejected: false,
        slope: 0.000000,
        intercept: 2.537819,
        width_above: 0.019688,
        width_below: 0.000000,
        min_denom: 128,
        max_denom: 12234,
        samples: 34188,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: false,
        slope: 0.997742,
        intercept: 2.608440,
        width_above: 0.291441,
        width_below: 1.524420,
        min_denom: 128,
        max_denom: 24065,
        samples: 26887,
        constant: false,
    },
    Band {
        kernel: "ff_clock_join",
        rejected: true,
        slope: 1.386356,
        intercept: 0.259595,
        width_above: 0.567393,
        width_below: 0.915553,
        min_denom: 129,
        max_denom: 24310,
        samples: 409,
        constant: false,
    },
    Band {
        kernel: "ff_clock_own_version",
        rejected: false,
        slope: 1.042300,
        intercept: 2.445194,
        width_above: 0.159784,
        width_below: 0.129163,
        min_denom: 128,
        max_denom: 13943,
        samples: 1101,
        constant: false,
    },
    Band {
        kernel: "ff_clock_recv",
        rejected: false,
        slope: 1.016980,
        intercept: 2.919032,
        width_above: 0.299164,
        width_below: 0.449515,
        min_denom: 128,
        max_denom: 20860,
        samples: 5743,
        constant: false,
    },
    Band {
        kernel: "ff_clock_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 2.227887,
        width_above: 0.000000,
        width_below: 0.000000,
        min_denom: 8,
        max_denom: 8,
        samples: 4565,
        constant: true,
    },
    Band {
        kernel: "ff_clock_send",
        rejected: false,
        slope: 1.054017,
        intercept: 2.784793,
        width_above: 0.239193,
        width_below: 0.312077,
        min_denom: 128,
        max_denom: 12148,
        samples: 3459,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: false,
        slope: 0.994932,
        intercept: 2.595383,
        width_above: 0.297418,
        width_below: 1.511516,
        min_denom: 128,
        max_denom: 24394,
        samples: 1652,
        constant: false,
    },
    Band {
        kernel: "ff_clock_sync",
        rejected: true,
        slope: 1.329034,
        intercept: 0.099238,
        width_above: 1.056264,
        width_below: 1.122424,
        min_denom: 133,
        max_denom: 23090,
        samples: 419,
        constant: false,
    },
    Band {
        kernel: "ff_clock_tick",
        rejected: false,
        slope: 1.048373,
        intercept: 2.798880,
        width_above: 0.257440,
        width_below: 0.308432,
        min_denom: 128,
        max_denom: 12234,
        samples: 312284,
        constant: false,
    },
    Band {
        kernel: "ff_clock_version",
        rejected: false,
        slope: 0.000000,
        intercept: 2.401401,
        width_above: 0.219776,
        width_below: 0.000000,
        min_denom: 128,
        max_denom: 12239,
        samples: 12317,
        constant: false,
    },
    Band {
        kernel: "ff_party_covers",
        rejected: false,
        slope: 1.051435,
        intercept: 1.617233,
        width_above: 0.151736,
        width_below: 1.366182,
        min_denom: 128,
        max_denom: 10316,
        samples: 2390,
        constant: false,
    },
    Band {
        kernel: "ff_party_decode",
        rejected: false,
        slope: 0.989264,
        intercept: 1.838184,
        width_above: 0.041102,
        width_below: 0.025314,
        min_denom: 128,
        max_denom: 5160,
        samples: 1785,
        constant: false,
    },
    Band {
        kernel: "ff_party_display",
        rejected: false,
        slope: 0.935297,
        intercept: 1.428213,
        width_above: 0.101654,
        width_below: 0.049547,
        min_denom: 136,
        max_denom: 74488,
        samples: 4907,
        constant: false,
    },
    Band {
        kernel: "ff_party_encode",
        rejected: false,
        slope: 0.405534,
        intercept: 1.595215,
        width_above: 0.289789,
        width_below: 0.264110,
        min_denom: 128,
        max_denom: 5160,
        samples: 1659,
        constant: false,
    },
    Band {
        kernel: "ff_party_fork",
        rejected: false,
        slope: 0.887313,
        intercept: 2.197790,
        width_above: 0.050336,
        width_below: 0.034403,
        min_denom: 132,
        max_denom: 5120,
        samples: 675,
        constant: false,
    },
    Band {
        kernel: "ff_party_forks",
        rejected: false,
        slope: 0.885453,
        intercept: 2.491465,
        width_above: 0.097127,
        width_below: 0.218161,
        min_denom: 128,
        max_denom: 4760,
        samples: 1298,
        constant: false,
    },
    Band {
        kernel: "ff_party_fromstr",
        rejected: false,
        slope: 0.979962,
        intercept: 1.317855,
        width_above: 0.146399,
        width_below: 0.052408,
        min_denom: 136,
        max_denom: 74488,
        samples: 4907,
        constant: false,
    },
    Band {
        kernel: "ff_party_is_disjoint",
        rejected: false,
        slope: 1.244001,
        intercept: 0.902853,
        width_above: 0.434578,
        width_below: 1.076783,
        min_denom: 128,
        max_denom: 10316,
        samples: 2390,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: false,
        slope: 1.251697,
        intercept: 1.606538,
        width_above: 0.344322,
        width_below: 0.829030,
        min_denom: 128,
        max_denom: 8622,
        samples: 33327,
        constant: false,
    },
    Band {
        kernel: "ff_party_join",
        rejected: true,
        slope: 1.409307,
        intercept: 0.719413,
        width_above: 0.544580,
        width_below: 1.011155,
        min_denom: 132,
        max_denom: 10316,
        samples: 406,
        constant: false,
    },
    Band {
        kernel: "ff_party_seed",
        rejected: false,
        slope: 0.000000,
        intercept: 2.196401,
        width_above: 0.041645,
        width_below: 0.000502,
        min_denom: 8,
        max_denom: 8,
        samples: 336,
        constant: true,
    },
    Band {
        kernel: "ff_party_without",
        rejected: false,
        slope: 0.713954,
        intercept: 2.578303,
        width_above: 0.103808,
        width_below: 0.051724,
        min_denom: 128,
        max_denom: 4870,
        samples: 321,
        constant: false,
    },
    Band {
        kernel: "ff_party_without",
        rejected: true,
        slope: 1.398132,
        intercept: 1.286970,
        width_above: 0.459545,
        width_below: 0.353770,
        min_denom: 134,
        max_denom: 9980,
        samples: 339,
        constant: false,
    },
    Band {
        kernel: "ff_rank_add",
        rejected: false,
        slope: 0.432992,
        intercept: 2.112596,
        width_above: 0.214051,
        width_below: 0.231156,
        min_denom: 128,
        max_denom: 8464,
        samples: 1841,
        constant: false,
    },
    Band {
        kernel: "ff_rank_checked_sub",
        rejected: false,
        slope: 0.555367,
        intercept: 1.668061,
        width_above: 0.353264,
        width_below: 0.304999,
        min_denom: 128,
        max_denom: 8464,
        samples: 1918,
        constant: false,
    },
    Band {
        kernel: "ff_rank_checked_sub",
        rejected: true,
        slope: -0.018256,
        intercept: 2.470002,
        width_above: 0.527865,
        width_below: 0.171462,
        min_denom: 128,
        max_denom: 4216,
        samples: 308,
        constant: false,
    },
    Band {
        kernel: "ff_rank_cmp",
        rejected: false,
        slope: 0.631700,
        intercept: 1.338792,
        width_above: 0.188018,
        width_below: 1.455456,
        min_denom: 128,
        max_denom: 8464,
        samples: 1113,
        constant: false,
    },
    Band {
        kernel: "ff_rank_display",
        rejected: false,
        slope: 1.084360,
        intercept: 0.798575,
        width_above: 0.204590,
        width_below: 0.160640,
        min_denom: 128,
        max_denom: 8464,
        samples: 1104,
        constant: false,
    },
    Band {
        kernel: "ff_version_cmp",
        rejected: false,
        slope: 1.165292,
        intercept: 1.677192,
        width_above: 0.334852,
        width_below: 0.869598,
        min_denom: 128,
        max_denom: 17400,
        samples: 2091,
        constant: false,
    },
    Band {
        kernel: "ff_version_concurrent",
        rejected: false,
        slope: 1.165534,
        intercept: 1.676211,
        width_above: 0.334190,
        width_below: 0.870335,
        min_denom: 128,
        max_denom: 17400,
        samples: 2091,
        constant: false,
    },
    Band {
        kernel: "ff_version_decode",
        rejected: false,
        slope: 1.174963,
        intercept: 1.707752,
        width_above: 0.330603,
        width_below: 0.353247,
        min_denom: 128,
        max_denom: 8768,
        samples: 3166,
        constant: false,
    },
    Band {
        kernel: "ff_version_display",
        rejected: false,
        slope: 0.973961,
        intercept: 1.822993,
        width_above: 0.197560,
        width_below: 0.136070,
        min_denom: 129,
        max_denom: 118788,
        samples: 5688,
        constant: false,
    },
    Band {
        kernel: "ff_version_distance",
        rejected: false,
        slope: 1.154815,
        intercept: 2.067449,
        width_above: 0.332040,
        width_below: 0.398797,
        min_denom: 128,
        max_denom: 6174,
        samples: 2208,
        constant: false,
    },
    Band {
        kernel: "ff_version_encode",
        rejected: false,
        slope: 0.425451,
        intercept: 1.511232,
        width_above: 0.307244,
        width_below: 0.254661,
        min_denom: 128,
        max_denom: 8767,
        samples: 3072,
        constant: false,
    },
    Band {
        kernel: "ff_version_fromstr",
        rejected: false,
        slope: 0.968483,
        intercept: 2.138194,
        width_above: 0.136979,
        width_below: 0.078923,
        min_denom: 129,
        max_denom: 118788,
        samples: 5688,
        constant: false,
    },
    Band {
        kernel: "ff_version_join",
        rejected: false,
        slope: 1.019067,
        intercept: 2.664680,
        width_above: 0.239415,
        width_below: 2.796196,
        min_denom: 128,
        max_denom: 17040,
        samples: 5421,
        constant: false,
    },
    Band {
        kernel: "ff_version_join_all",
        rejected: false,
        slope: 1.143282,
        intercept: 2.845030,
        width_above: 0.355320,
        width_below: 2.456448,
        min_denom: 128,
        max_denom: 187770,
        samples: 3514,
        constant: false,
    },
    Band {
        kernel: "ff_version_lag",
        rejected: false,
        slope: 1.163678,
        intercept: 2.023197,
        width_above: 0.354166,
        width_below: 0.384412,
        min_denom: 128,
        max_denom: 6174,
        samples: 2208,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet",
        rejected: false,
        slope: 1.007892,
        intercept: 2.650862,
        width_above: 0.283837,
        width_below: 2.847751,
        min_denom: 128,
        max_denom: 17157,
        samples: 3174,
        constant: false,
    },
    Band {
        kernel: "ff_version_meet_all",
        rejected: false,
        slope: 1.109367,
        intercept: 2.490924,
        width_above: 0.293499,
        width_below: 1.869470,
        min_denom: 128,
        max_denom: 131830,
        samples: 1263,
        constant: false,
    },
    Band {
        kernel: "ff_version_min_ticks",
        rejected: false,
        slope: 1.097626,
        intercept: 2.568604,
        width_above: 0.254632,
        width_below: 0.454091,
        min_denom: 128,
        max_denom: 8767,
        samples: 3043,
        constant: false,
    },
    Band {
        kernel: "ff_version_project",
        rejected: false,
        slope: 0.860565,
        intercept: 2.921638,
        width_above: 0.603044,
        width_below: 0.393759,
        min_denom: 128,
        max_denom: 52428,
        samples: 4302,
        constant: false,
    },
    Band {
        kernel: "ff_version_rank",
        rejected: false,
        slope: 1.126510,
        intercept: 2.077241,
        width_above: 0.325389,
        width_below: 0.383718,
        min_denom: 128,
        max_denom: 8767,
        samples: 6179,
        constant: false,
    },
    Band {
        kernel: "ff_version_tick",
        rejected: false,
        slope: 1.037616,
        intercept: 2.867340,
        width_above: 0.185660,
        width_below: 0.531059,
        min_denom: 128,
        max_denom: 13827,
        samples: 2663,
        constant: false,
    },
];

/// The band keys the pin-time prefix refit covered: the staleness
/// cross-check's committed expectation list.
///
/// Generated by `just fuzzfit-calibrate` alongside [`BANDS`]: every key
/// listed here had, at pin time, a prefix refit whose classification
/// matched its pin. The enforcement suite requires each listed key to
/// still fit, still match its pin's classification, and still agree
/// within [`REFIT_TOLERANCE`] — so coverage decay, a classification flip
/// (the reach-regression tell), and line drift each fail by name instead
/// of hollowing the check out silently. Keys not listed are outside the
/// staleness detector's reach at pin time; calibration prints them for
/// the re-pinner to review.
pub const REFIT_COVERAGE: &[(&str, bool)] = &[
    ("ff_clock_decode", false),
    ("ff_clock_encode", false),
    ("ff_clock_fork", false),
    ("ff_clock_from_parts", false),
    ("ff_clock_into_parts", false),
    ("ff_clock_join", false),
    ("ff_clock_join", true),
    ("ff_clock_own_version", false),
    ("ff_clock_recv", false),
    ("ff_clock_seed", false),
    ("ff_clock_send", false),
    ("ff_clock_sync", false),
    ("ff_clock_sync", true),
    ("ff_clock_tick", false),
    ("ff_clock_version", false),
    ("ff_party_covers", false),
    ("ff_party_decode", false),
    ("ff_party_display", false),
    ("ff_party_encode", false),
    ("ff_party_fork", false),
    ("ff_party_forks", false),
    ("ff_party_fromstr", false),
    ("ff_party_is_disjoint", false),
    ("ff_party_join", false),
    ("ff_party_join", true),
    ("ff_party_seed", false),
    ("ff_party_without", false),
    ("ff_party_without", true),
    ("ff_rank_add", false),
    ("ff_rank_checked_sub", false),
    ("ff_rank_cmp", false),
    ("ff_rank_display", false),
    ("ff_version_cmp", false),
    ("ff_version_concurrent", false),
    ("ff_version_decode", false),
    ("ff_version_display", false),
    ("ff_version_distance", false),
    ("ff_version_encode", false),
    ("ff_version_fromstr", false),
    ("ff_version_join", false),
    ("ff_version_join_all", false),
    ("ff_version_lag", false),
    ("ff_version_meet", false),
    ("ff_version_meet_all", false),
    ("ff_version_min_ticks", false),
    ("ff_version_project", false),
    ("ff_version_rank", false),
    ("ff_version_tick", false),
];
