//! A simulated peer: a `Local<T>` paired with its observation log, plus
//! helpers for the schedule executor (`gossip_step` for bidirectional
//! `Local::process`, `quiesce` for full-mesh convergence to a fixed
//! point).

use borsh::{BorshDeserialize, BorshSerialize};
use rumors::sync::Local;
use rumors::{Key, Version};

/// One simulated peer.
pub struct Peer<T> {
    pub local: Local<T>,
    /// All observations this peer has accumulated, across `message`,
    /// `redact`, and `process` calls. The public API contract says
    /// callback order within a batch is arbitrary; in practice it is
    /// deterministic across runs because the underlying tree is an
    /// `imbl::OrdMap`, so the log is reproducible inside a counterexample.
    pub observations: Vec<(Key, Version, T)>,
}

impl<T: Clone + BorshSerialize + BorshDeserialize> Peer<T> {
    pub fn new(party: impl AsRef<[u8]>) -> Self {
        Self {
            local: Local::for_party(party),
            observations: Vec::new(),
        }
    }

    /// Insert a single value, returning the `Key` minted for it.
    pub fn insert_one(&mut self, value: T) -> Key {
        let mut produced: Option<Key> = None;
        let obs = &mut self.observations;
        self.local.message([value], |k, v, m| {
            obs.push((k, v.clone(), T::clone(m)));
            produced = Some(k);
        });
        produced.expect("Local::message must fire on_message for every inserted value")
    }

    pub fn redact_one(&mut self, key: Key) {
        self.local.redact([key]);
    }
}

/// Bidirectional gossip between two peers: each side merges the other's
/// state into its own and records observations. After this returns,
/// `a.local == b.local`.
pub fn gossip_step<T>(a: &mut Peer<T>, b: &mut Peer<T>)
where
    T: Clone + BorshSerialize + BorshDeserialize,
{
    let a_snapshot = a.local.clone();
    let b_snapshot = b.local.clone();

    let obs_a = &mut a.observations;
    a.local.process(b_snapshot, |k, v, m| {
        obs_a.push((k, v.clone(), T::clone(m)));
    });

    let obs_b = &mut b.observations;
    b.local.process(a_snapshot, |k, v, m| {
        obs_b.push((k, v.clone(), T::clone(m)));
    });
}

/// Drive every pair toward convergence by repeatedly running
/// `gossip_step` over all pairs in a fixed order until no peer's
/// `Local` changes for a full round. A bounded outer loop guards
/// against pathological non-termination (which would itself be a bug
/// the test should catch).
pub fn quiesce<T>(peers: &mut [Peer<T>])
where
    T: Clone + Eq + BorshSerialize + BorshDeserialize,
{
    let n = peers.len();
    if n < 2 {
        return;
    }

    let max_rounds = MAX_QUIESCE_ROUNDS_PER_PEER * n;
    for _ in 0..max_rounds {
        let snapshot: Vec<Local<T>> = peers.iter().map(|p| p.local.clone()).collect();

        for i in 0..n {
            for j in (i + 1)..n {
                let (left, right) = peers.split_at_mut(j);
                gossip_step(&mut left[i], &mut right[0]);
            }
        }

        let changed = peers
            .iter()
            .zip(snapshot.iter())
            .any(|(p, s)| &p.local != s);
        if !changed {
            return;
        }
    }

    panic!(
        "quiesce did not converge within {max_rounds} rounds for {n} peers: \
         a propagation or shadow-simulator bug (schedules generated by \
         `arb_schedule` are convergent by construction)"
    );
}

/// Headroom on the convergence loop: a single piece of information
/// needs at most O(diameter) rounds to reach every peer over a
/// full-mesh schedule, so 16 rounds per peer is dramatically more than
/// enough. Used only to bound test pathologies.
const MAX_QUIESCE_ROUNDS_PER_PEER: usize = 16;
