//! Checks registered worst-case generators: each shape decodes, re-encodes
//! byte-identically, and has exactly its closed-form bit length.

use crate::codec;
use crate::{Party, Rank, Ticks, Version};

use num_bigint::BigUint;
use proptest::prelude::*;

use super::{
    alt_spine, arming_train, ascend_cliff, ascend_cliff_plateau, bigroot, bitlen, cancelling_chain,
    cliff_comb, cliff_fan, collapse_hole, concurrent_pair, copy_hole, dense, dense_suffix,
    dense_suffix_mate, dominated_undercut, dominated_undercut_id, freeze_parade, freeze_position,
    harmonic, hoisted_window, hugeleaf, id_spine, jump_comb, jump_pair, latent_ladder, lone_freeze,
    mask_drift_quadruple, mask_drift_triple, masked_hole, plateau_puncture,
    plateau_puncture_factors, promotion_rearm, promotion_rearm_mate, raise_hole, scattered_id,
    seam_plunge, seam_plunge_control, seam_stop, seam_stop_control, site_hole, tooth_tail,
    weight_comb, wide_arming, wide_tooth_comb, Encoding,
};

/// Appended to the counter-comparison failures: the first cause to rule out is
/// a shared-process test runner, under which the process-global counters bleed
/// other tests' work into the reading being compared.
const ISOLATION_NOTE: &str = "note: the counter is process-global and meaningful only one \
     test per process: run under cargo nextest, not a shared-process cargo test";

/// Convert the arbitrary-precision oracle value directly into a tick count.
fn ticks_from_big(value: &BigUint) -> Ticks {
    Ticks(value.clone())
}

/// Build a uniform version through the public tick operation.
fn uniform(count: impl Into<Ticks>) -> Version {
    let mut version = Version::new();
    Party::seed().ticks(&mut version, count);
    version
}

/// Check an event-shape output: the construction stream has exactly the
/// closed-form `bits`, and it lifts through the transcoding bridge into a
/// version that survives a wire round-trip (canonicality of both codings).
fn check_version(p: &Encoding, bits: usize) {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let v = p.version();
    let wire = v.encode();
    let back = Version::decode(&wire[..]).expect("a stored version's wire bytes decode");
    assert_eq!(back, v, "wire round-trip");
    assert_eq!(back.encode(), wire, "byte-identical re-encode");
}

/// Check an id-shape output: `decode` accepts it, the decoded party re-encodes
/// to the generated bytes (canonicality), and the live bit length is exactly
/// `bits`.
fn check_party(p: &Encoding, bits: usize) -> Party {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let id = Party::decode(&p.bytes[..]).expect("generated shape is strict normal form");
    assert_eq!(id.encoded_bits(), p.bits as u64, "decoded live bit length");
    assert_eq!(id.encode(), p.bytes, "byte-identical re-encode");
    id
}

/// The dense spine `S(d)` is canonical normal form at exactly `4d + 4` bits, at
/// both a small and a large depth.
#[test]
fn dense_decodes_canonically_at_predicted_length() {
    for d in [3, 1000] {
        check_version(&dense(d), 4 * d + 4);
    }
}

/// `bigroot(b, d)` is canonical normal form at exactly `2b + 4d + 8` bits,
/// including a root magnitude wide enough to spill machine-word gamma decoding.
#[test]
fn bigroot_decodes_canonically_at_predicted_length() {
    for (b, d) in [(3, 2), (100, 50)] {
        check_version(&bigroot(b, d), 2 * b + 4 * d + 8);
    }
}

/// `hugeleaf(b)` is canonical normal form at exactly `2b + 2` bits, including a
/// magnitude wide enough to spill machine-word gamma decoding.
#[test]
fn hugeleaf_decodes_canonically_at_predicted_length() {
    for b in [1, 200] {
        check_version(&hugeleaf(b), 2 * b + 2);
    }
}

/// `cliff_comb(k, n)` is canonical normal form at exactly `n(2k + 10) + 2`
/// bits.
///
/// The sizes cover a tooth magnitude wide enough to spill machine-word gamma
/// decoding and a tooth count deep enough for the oscillation to dominate.
#[test]
fn cliff_comb_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 1), (3, 4), (200, 50)] {
        check_version(&cliff_comb(k, n), n * (2 * k + 10) + 2);
    }
}

/// `jump_comb(k, n)` is canonical normal form at exactly `(n − 1)(2k + 10) +
/// 14` bits.
///
/// The sizes cover a cliff magnitude wide enough to spill machine-word gamma
/// decoding.
#[test]
fn jump_comb_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 2), (3, 4), (200, 50)] {
        check_version(&jump_comb(k, n), (n - 1) * (2 * k + 10) + 14);
    }
}

/// `wide_tooth_comb(k, w, n)` is canonical normal form at exactly `n(2k + 2w +
/// 6) + 2` bits.
///
/// The sizes cover teeth and cliffs wide enough to spill machine-word gamma
/// decoding.
#[test]
fn wide_tooth_comb_decodes_canonically_at_predicted_length() {
    for (k, w, n) in [(2, 1, 1), (3, 1, 4), (200, 100, 50)] {
        check_version(&wide_tooth_comb(k, w, n), n * (2 * k + 2 * w + 6) + 2);
    }
}

/// `cliff_fan(k, n)` is canonical normal form at exactly `12n + 2k + 6` bits,
/// with every tooth's 12 stored bits crossing the `2^k` path-sum boundary twice
/// under one stored root magnitude.
///
/// The sizes cover a root magnitude wide enough to spill machine-word gamma
/// decoding.
#[test]
fn cliff_fan_decodes_canonically_at_predicted_length() {
    for (k, n) in [(1, 1), (3, 4), (200, 50)] {
        check_version(&cliff_fan(k, n), 12 * n + 2 * k + 6);
    }
}

/// `cancelling_chain(k, n)` is canonical normal form at exactly `n(2k + 10) +
/// 2` bits.
///
/// The sizes cover a peak magnitude wide enough to spill machine-word gamma
/// decoding.
#[test]
fn cancelling_chain_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 1), (3, 4), (200, 50)] {
        check_version(&cancelling_chain(k, n), n * (2 * k + 10) + 2);
    }
}

/// `freeze_position(k)` is canonical normal form at exactly `4k(L + 2) + 2`
/// bits for `L = 289 + bitlen(k)`, and its `min_ticks` is exactly the leaf-sum
/// closed form `2k·2^L + k(k−1)(2^288 + 1) + k`.
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` bands in `tests/meter.rs` re-derive it at meter scale, so
/// this pin holds it at hand-checkable sizes where the tree can also be
/// spot-read (one block, descending 290-bit leaves over the terminal zero).
#[test]
fn freeze_position_decodes_canonically_at_predicted_length() {
    for (k, bitlen) in [(1usize, 1usize), (5, 3), (200, 8)] {
        let band = 289 + bitlen;
        check_version(&freeze_position(k), 4 * k * (band + 2) + 2);
        let expected = (BigUint::from(2 * k as u64) << band)
            + BigUint::from((k * (k - 1)) as u64) * ((BigUint::ONE << 288usize) + BigUint::ONE)
            + BigUint::from(k as u64);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            freeze_position(k).version().min_ticks(),
            ticks,
            "the leaf-sum closed form is the family's minimum tick count"
        );
    }
}

/// `promotion_rearm(p)` is canonical normal form at exactly `1972p + 4` bits.
///
/// Its `min_ticks` is exactly the stored-base sum `16p + p(2^608 + 2^288 + 2) +
/// 1`.
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` bands in `tests/meter.rs` re-derive it at meter scale, so
/// this pin holds it at hand-checkable sizes.
#[test]
fn promotion_rearm_decodes_canonically_at_predicted_length() {
    for p in [1usize, 5, 200] {
        check_version(&promotion_rearm(p), 1972 * p + 4);
        let expected = BigUint::from(16 * p as u64)
            + BigUint::from(p as u64)
                * ((BigUint::ONE << 608usize) + (BigUint::ONE << 288usize) + 2u8)
            + 1u8;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            promotion_rearm(p).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `lone_freeze(pre, post)` is canonical normal form at exactly `580·pre +
/// 6·post + 14` bits, and its `min_ticks` is exactly the leaf-sum closed form
/// `pre·(2^288 + 2) + pre/2 + 3·post/2 + 3`.
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` bands in `tests/meter.rs` re-derive it at meter scale on
/// both dials, so this pin holds it at hand-checkable sizes where the tree can
/// also be spot-read (a plateau pair, the drop block, a tail pair, the terminal
/// zero).
#[test]
fn lone_freeze_decodes_canonically_at_predicted_length() {
    for (pre, post) in [(2usize, 2usize), (2, 6), (6, 2), (40, 40)] {
        check_version(&lone_freeze(pre, post), 580 * pre + 6 * post + 14);
        let expected = BigUint::from(pre as u64)
            * ((BigUint::ONE << 288usize) + BigUint::from(2u8))
            + BigUint::from((pre / 2) as u64)
            + BigUint::from((3 * post / 2) as u64)
            + BigUint::from(3u8);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            lone_freeze(pre, post).version().min_ticks(),
            ticks,
            "the leaf-sum closed form is the family's minimum tick count"
        );
    }
}

/// `promotion_rearm_mate(p)` is canonical normal form at exactly `180p + 4`
/// bits.
///
/// Its `min_ticks` is exactly `18p + 1`, and `promotion_rearm(p)` dominates it
/// pointwise (the pair band's exact value legs rest on the dominance).
#[test]
fn promotion_rearm_mate_decodes_canonically_at_predicted_length() {
    for p in [1usize, 5, 200] {
        check_version(&promotion_rearm_mate(p), 180 * p + 4);
        let ticks = Ticks::from(18 * p as u64 + 1);
        assert_eq!(
            promotion_rearm_mate(p).version().min_ticks(),
            ticks,
            "the alternating spine's stored-base sum is its minimum tick count"
        );
    }
    let a = promotion_rearm(3).version();
    let b = promotion_rearm_mate(3).version();
    assert!(
        a.rank().checked_sub(&b.rank()).is_some(),
        "the re-arm spine dominates its mate"
    );
    assert_eq!(
        a.lag(&b),
        crate::Rank::ZERO,
        "the dominating side lags by nothing"
    );
}

/// The harmonic spine `H(d)` is canonical normal form at exactly `6d + 2` bits,
/// and its rank is exactly the closed form `(2^d − 1)/2^d`.
///
/// The closed form is pinned through canonical binary text at hand-checkable
/// depths and at meter scale through `1 − rank(H(d)) = 1/2^d`.
#[test]
fn harmonic_decodes_canonically_at_predicted_length_and_rank() {
    for d in [1, 2, 3, 1000] {
        check_version(&harmonic(d), 6 * d + 2);
    }
    assert_eq!(harmonic(2).version().rank().to_string(), "0.11");
    assert_eq!(harmonic(7).version().rank().to_string(), "0.1111111");
    // Meter scale: 1 − (2^d − 1)/2^d = 1/2^d, exact at any depth.
    let d = 4_096;
    let h = harmonic(d).version().rank();
    let one = uniform(1u8).rank();
    let gap = one
        .checked_sub(&h)
        .expect("H(d)'s rank is strictly under the unit rank");
    assert_eq!(gap.to_string(), format!("0.{}1", "0".repeat(d - 1)));
}

/// The alternating-binary spine `A(d)` is canonical normal form at exactly
/// `4d + 4` bits, with the internal child changing sides every level.
///
/// The checked depths cover both alternation parities.
#[test]
fn alt_spine_decodes_canonically_at_predicted_length() {
    for d in [1, 2, 3, 1000] {
        check_version(&alt_spine(d), 4 * d + 4);
    }
}

/// `dominated_undercut(k, b)` is canonical normal form at exactly
/// `k(2b + 26) + 2` bits, and each site holds the raise leaf beside the
/// `5 · 2^b` climb with the exit one above the region's minimum.
///
/// The sizes cover the generator's minimum width, an unaligned width (the
/// decidability argument is width-generic past the bound), and a site count
/// deep enough for the spine to dominate.
#[test]
fn dominated_undercut_decodes_canonically_at_predicted_length() {
    for (k, b) in [(1, 128), (3, 133), (50, 200)] {
        check_version(&dominated_undercut(k, b), k * (2 * b + 26) + 2);
    }
}

/// `dominated_undercut_id(k)` decodes canonically at exactly `6k + 2` bits:
/// per site a `(1, 0)` node over the raise leaf, bottoming in a full terminal.
#[test]
fn dominated_undercut_id_decodes_canonically_at_predicted_length() {
    for k in [1, 2, 50] {
        check_party(&dominated_undercut_id(k), 6 * k + 2);
    }
    check_party(&dominated_undercut_id(1), 8);
}

/// The stack-segment meter observes deep guarded recursion, resets to zero,
/// counts deterministically, and reads zero over a deep fill walk.
///
/// Determinism — the same count for the same descent repeated at the same call
/// depth — is what makes the meter envelope-able; the deep fill reads zero
/// because its explicit stacks put depth on the heap instead.
///
/// Every library walk is iterative, so the meter's liveness needs its own
/// witness: a test-local descent routed through `recurse::descend!` (the same
/// guard the test-only oracle bridge walks use) deep enough to outrun the
/// thread stack. Without that leg, the boards' all-zero segments column could
/// be a dead counter instead of a measured fact.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[test]
fn stack_segment_meter_counts_deterministically_and_resets() {
    use crate::recurse::descend;
    /// A guarded descent to `floor`, each frame holding a small
    /// stack-resident payload so its size is explicit.
    fn dive(depth: usize, floor: usize) -> u64 {
        if depth == floor {
            return 1;
        }
        let pad = [depth as u64; 8];
        let below = descend!(depth + 1, dive(depth + 1, floor));
        below + core::hint::black_box(pad)[0]
    }
    const FLOOR: usize = 200_000;
    super::reset_stack_segments();
    core::hint::black_box(dive(0, FLOOR));
    let first = super::stack_segments();
    assert!(
        first > 0,
        "a depth-200000 guarded descent must grow the stack"
    );
    super::reset_stack_segments();
    assert_eq!(
        super::stack_segments(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    core::hint::black_box(dive(0, FLOOR));
    assert_eq!(
        super::stack_segments(),
        first,
        "identical descents at identical call depth grow identical segments: {ISOLATION_NOTE}"
    );

    // The conversion ratchet: the fill walk pairs a deep spine on BOTH
    // sides — exactly the descent that once grew the stack — and must now
    // read zero, its depth on explicit heap stacks the heap meter prices.
    let v = dense(50_000).version();
    let id = Party::decode(&id_spine(50_000, false).bytes[..]).expect("id spine decodes");
    super::reset_stack_segments();
    let mut t = v.clone();
    t.tick(&id);
    assert_eq!(
        super::stack_segments(),
        0,
        "the iterative fill walk grows no stack segments: {ISOLATION_NOTE}"
    );
}

/// The scan meter observes encoded traversal, resets to zero, and reads
/// the same count for the same operation repeated.
///
/// Determinism is what makes it envelope-able, and its floor is live — a strict
/// decode scans every live bit at least once — so a ceiling asserted over it
/// can never pass vacuously at zero.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[cfg(feature = "scan-meter")]
#[test]
fn scan_meter_counts_deterministically_and_resets() {
    // A strict id decode reads each live bit exactly once through the
    // sequential cursor, so the count has both a floor and an exact
    // expectation.
    let count_decode = |d: usize| {
        let p = id_spine(d, false);
        super::reset_scan_bits();
        let _ = Party::decode(&p.bytes[..]).expect("id spine decodes");
        (super::scan_bits(), p.bits as u64)
    };
    let (first, bits) = count_decode(10_000);
    assert!(
        first >= bits,
        "a strict decode of {bits} live bits scanned only {first}: \
         the sequential cursor is not recording: {ISOLATION_NOTE}"
    );
    super::reset_scan_bits();
    assert_eq!(
        super::scan_bits(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    assert_eq!(
        count_decode(10_000).0,
        first,
        "identical operations scan identical bits: {ISOLATION_NOTE}"
    );
    assert!(
        count_decode(20_000).0 > first,
        "a longer stream must scan more bits: {ISOLATION_NOTE}"
    );

    // The write side is live too: joining two disjoint spines writes the joined
    // tree through the id builder, so the count covers reads of both operands
    // plus at least the output's own bits.
    let pa = id_spine(1_000, false);
    let pb = id_spine(1_000, true);
    let mut a = Party::decode(&pa.bytes[..]).expect("id spine decodes");
    let b = Party::decode(&pb.bytes[..]).expect("id spine decodes");
    super::reset_scan_bits();
    a.join(b).expect("the divert arms are disjoint");
    let joined = super::scan_bits();
    assert!(
        joined >= a.encoded_bits(),
        "a join that wrote {} output bits recorded only {joined} scan bits: \
         the id builder is not recording its writes: {ISOLATION_NOTE}",
        a.encoded_bits(),
    );
}

/// The span-traffic counters classify one constructed witness per rung arm, and
/// reset to zero.
///
/// One witness pair per rung — byte-equal streams in distinct buffers, an empty
/// operand, a ticked chain (comparable), a forked divergence (concurrent) —
/// read as the full four-cell snapshot, so a miswired rung shows as the wrong
/// cell moving, not merely a total. The empty and comparable rungs classify
/// each operand order in its own match arm, so those rungs are witnessed in
/// both orders: a miswire of either arm alone moves its cell. The counter is
/// process-global, so the per-call readings are meaningful under nextest's
/// one-test-per-process isolation (this workspace's runner).
#[test]
fn span_traffic_classifies_each_rung() {
    use crate::Clock;
    let mut main = Clock::seed();
    let mut other = main.fork();
    main.tick();
    let v = main.version().clone();
    main.tick();
    let w = main.version().clone();
    other.tick();
    let d = other.version().clone();
    let v_copy = Version::decode(&v.encode()[..]).expect("a version re-decodes");

    let cells = |a: &Version, b: &Version| {
        super::reset_span_traffic();
        let _ = a.span(b);
        let read = super::span_traffic();
        (read.equal, read.empty, read.comparable, read.concurrent)
    };

    assert_eq!(
        cells(&v, &v_copy),
        (1, 0, 0, 0),
        "byte-equal operands answer at the equal rung: {ISOLATION_NOTE}"
    );
    assert_eq!(
        cells(&Version::new(), &v),
        (0, 1, 0, 0),
        "an empty first operand answers at the empty rung: {ISOLATION_NOTE}"
    );
    assert_eq!(
        cells(&v, &Version::new()),
        (0, 1, 0, 0),
        "an empty second operand answers at the empty rung: {ISOLATION_NOTE}"
    );
    assert_eq!(
        cells(&w, &v),
        (0, 0, 1, 0),
        "a dominating first operand answers at the comparable rung: {ISOLATION_NOTE}"
    );
    assert_eq!(
        cells(&v, &w),
        (0, 0, 1, 0),
        "a dominated first operand answers at the comparable rung: {ISOLATION_NOTE}"
    );
    assert_eq!(
        cells(&v, &d),
        (0, 0, 0, 1),
        "a forked divergence reaches the emitting walk: {ISOLATION_NOTE}"
    );

    super::reset_span_traffic();
    let zero = super::span_traffic();
    assert_eq!(
        (zero.equal, zero.empty, zero.comparable, zero.concurrent),
        (0, 0, 0, 0),
        "reset returns every rung to zero: {ISOLATION_NOTE}"
    );
}

/// `I(d, divert)` is canonical normal form at exactly `2d + 2` bits for both
/// divert arms, and the two arms own disjoint regions (the property that
/// drives two-operand id walks to full lockstep depth).
#[test]
fn id_spine_decodes_canonically_at_predicted_length() {
    for d in [1, 500] {
        let a = check_party(&id_spine(d, false), 2 * d + 2);
        let b = check_party(&id_spine(d, true), 2 * d + 2);
        assert!(a.is_disjoint(&b), "divert arms own disjoint regions");
    }
}

/// `Z(e)` is canonical normal form at exactly `6e + 2` bits, and projecting a
/// comb through it keeps a wide magnitude per kept tooth: the projected output
/// out-scales the scattered party's own bits.
///
/// The overlap claim is what the generator exists for — the owned left subtrees
/// sit at the comb's tooth positions — so a projection that came back
/// near-empty would mean the shapes no longer align.
#[test]
fn scattered_id_decodes_canonically_at_predicted_length() {
    for e in [1, 500] {
        check_party(&scattered_id(e), 6 * e + 2);
    }
    let (k, n) = (64, 16);
    let comb = cliff_comb(k, n).version();
    let party =
        Party::decode(&scattered_id(n / 2).bytes[..]).expect("scattered id is strict normal form");
    let projected = (&comb / &party).to_version();
    assert!(
        projected.encoded_bits() >= ((n / 2) * k) as u64,
        "projection through the scattered id must keep a wide magnitude per kept tooth \
         (got {} bits from {} teeth of {} bits)",
        projected.encoded_bits(),
        n,
        k
    );
}

/// `MT(k, n)` is three canonical operands at their closed-form lengths, and the
/// correlation realizes the full-walk verdict: the projected comb sits strictly
/// under the plateau, fused and materialized alike.
///
/// The `Less` verdict is what keeps every measurement of this family a
/// whole-overlay walk (no early exit), so a generator drift that broke the
/// alignment would read here as a changed verdict.
#[test]
fn mask_drift_triple_decodes_canonically_and_realizes_less() {
    let (k, n) = (64, 16);
    let (comb, mask, plateau) = mask_drift_triple(k, n);
    check_version(&comb, n * (2 * k + 10) + 2);
    check_version(&plateau, 2 * k + 2);
    let party = check_party(&mask, 6 * (n / 2) + 2);
    let (v, w) = (comb.version(), plateau.version());
    let fused = (&v / &party).partial_cmp(&w);
    assert_eq!(
        fused,
        Some(std::cmp::Ordering::Less),
        "the projected comb sits strictly under the plateau"
    );
    assert_eq!(
        fused,
        (&v / &party).to_version().partial_cmp(&w),
        "the fused verdict is the materialized verdict"
    );
}

/// `MQ(k, n)` is two canonical comb/mask pairs whose interleaved parities
/// realize the full-walk `Less` verdict.
///
/// Both operand pairs decode canonically at their closed-form lengths, the
/// sparse comb's view is semantically empty (its mask owns exactly its zero
/// levels), and the fused four-stream verdict matches the materialized
/// comparison.
#[test]
fn mask_drift_quadruple_decodes_canonically_and_realizes_less() {
    let (k, n) = (64, 16);
    let ((sparse, even_mask), (comb, odd_mask)) = mask_drift_quadruple(k, n);
    check_version(&sparse, (n / 2) * (2 * k + 14) + 2);
    check_version(&comb, n * (2 * k + 10) + 2);
    let p1 = check_party(&even_mask, 6 * (n / 2) + 2);
    let p2 = check_party(&odd_mask, 6 * (n / 2) + 4);
    let (v1, v2) = (sparse.version(), comb.version());
    assert!(
        (&v1 / &p1).to_version().is_empty(),
        "the even mask owns exactly the sparse comb's zero levels"
    );
    assert!(
        !(&v2 / &p2).to_version().is_empty(),
        "the odd mask keeps the full comb's teeth"
    );
    let fused = (&v1 / &p1).partial_cmp(&(&v2 / &p2));
    assert_eq!(
        fused,
        Some(std::cmp::Ordering::Less),
        "the empty view sits strictly under the tooth-keeping view"
    );
    assert_eq!(
        fused,
        (&v1 / &p1)
            .to_version()
            .partial_cmp(&(&v2 / &p2).to_version()),
        "the fused verdict is the materialized verdict"
    );
}

/// One hole region's closed-form bit length: `4·lead + 2(m − 1) +
/// Σ_{v=1}^{m} 2·bitlen(v + 1)` (the wrapper and staircase structure plus
/// each descending step's gamma-coded leaf).
fn hole_region_bits(lead: usize, m: usize) -> usize {
    4 * lead + 2 * (m - 1) + (1..=m).map(|v| 2 * bitlen(v + 1)).sum::<usize>()
}

/// The summed region bits of one hole pair's `k` units, leads alternating
/// 2, 3 across units (even `k`, so exactly half each).
fn hole_regions_bits(k: usize, m: usize) -> usize {
    (k / 2) * (hole_region_bits(2, m) + hole_region_bits(3, m))
}

/// The sub-scan hole pairs are canonical normal form — event and id
/// sides alike — at their closed-form bit lengths.
///
/// The event closed forms are each pair's per-unit structure plus the
/// alternating-lead region sum ([`hole_regions_bits`]); the id closed
/// forms are `6k` (collapse), `2k + 6` (copy), `4k + 4` (raise), and
/// `6k + 4` (site). The sizes cover the minimal pair and a deep-region
/// pair.
#[test]
fn hole_pairs_decode_canonically_at_predicted_lengths() {
    for (k, m) in [(2, 1), (4, 33)] {
        let regions = hole_regions_bits(k, m);
        let (ev, id) = collapse_hole(k, m);
        check_version(&ev, 6 * k + 2 + regions);
        check_party(&id, 6 * k);
        let (ev, id) = copy_hole(k, m);
        check_version(&ev, 6 + 2 * k + regions);
        check_party(&id, 2 * k + 6);
        let (ev, id) = raise_hole(k, m);
        check_version(&ev, 2 * k + 2 + regions);
        check_party(&id, 4 * k + 4);
        let (ev, id) = site_hole(k, m);
        check_version(&ev, 6 * k + 6 + regions);
        check_party(&id, 6 * k + 4);
    }
}

/// `MH(d, h)` is three canonical operands at their closed-form lengths,
/// and the correlation realizes the full-walk verdict.
///
/// The lengths: the dense spine's `4d + 4`, the diverted id spine's
/// `2h + 2`, the plateau's 4. The verdict: the projected spine sits
/// strictly under the plateau, fused and materialized alike, so no
/// measurement of this family exits early.
#[test]
fn masked_hole_decodes_canonically_and_realizes_less() {
    let (d, h) = (64, 8);
    let (spine, mask, plateau) = masked_hole(d, h);
    check_version(&spine, 4 * d + 4);
    check_version(&plateau, 4);
    let party = check_party(&mask, 2 * h + 2);
    let (v, w) = (spine.version(), plateau.version());
    let fused = (&v / &party).partial_cmp(&w);
    assert_eq!(
        fused,
        Some(std::cmp::Ordering::Less),
        "the projected spine sits strictly under the plateau"
    );
    assert_eq!(
        fused,
        (&v / &party).to_version().partial_cmp(&w),
        "the fused verdict is the materialized verdict"
    );
}

/// The leaf count of a stored version's skyline stream, by one iterative
/// topology walk (payload codes skipped unread).
fn leaf_count(v: &Version) -> usize {
    use codec::BitCursor;
    let mut cur = codec::DsiCursor::new(v.as_bits());
    let mut pending = 1usize;
    let mut leaves = 0usize;
    while pending > 0 {
        pending -= 1;
        if cur.read_bit().expect("a stored stream is canonical") {
            cur.skip_int().expect("a stored stream is canonical");
            leaves += 1;
        } else {
            pending += 2;
        }
    }
    leaves
}

/// `JP(k, m, d)` is canonical normal form at its closed-form bit lengths, and
/// its overlays realize the interleave the family exists for.
///
/// The lengths: exactly `132d + m(2k + 14) + 2` bits (teeth) and `132d + 14m +
/// 2k + 2` bits (band). The overlays: the meet keeps both band leaves per tooth
/// and both gap leaves per level (4 leaves per comb level — a cheap code one
/// fold behind every wide difference crest), while the join collapses every
/// comb level to its two plateaus (the band shades every gap): the wide crests
/// live in the meet-side overlay alone.
#[test]
fn jump_pair_decodes_canonically_at_predicted_lengths_and_interleaves() {
    for (k, m, d) in [(3, 1, 1), (400, 8, 2)] {
        let (a, b) = jump_pair(k, m, d);
        check_version(&a, 132 * d + m * (2 * k + 14) + 2);
        check_version(&b, 132 * d + 14 * m + 2 * k + 2);
        let (a, b) = (a.version(), b.version());
        let spine_leaves = super::JUMP_PAIR_DIGIT_STRIDE * d;
        assert_eq!(
            leaf_count(&(&a & &b)),
            spine_leaves + 4 * m + 1,
            "the meet must keep the band and gap interleave whole"
        );
        assert_eq!(
            leaf_count(&(&a | &b)),
            spine_leaves + 2 * m + 1,
            "the join must collapse each comb level to its two plateaus"
        );
        // The valuation identity, on the public surface: the pair's
        // distance is its two lags' sum (rank modularity).
        let d1 = a.lag(&b);
        let d2 = b.lag(&a);
        assert_eq!(a.distance(&b), &d1 + &d2, "distance is the lags' sum");
    }
}

/// `CP(n)` builds two genuinely concurrent organic versions that switch sides
/// at every overlay boundary.
///
/// The join and the meet both keep one plateau per forked leaf — every one of
/// the `n − 1` overlay boundaries a side switch — and the distance is the
/// integer rank 2 at every `n` (each leaf's dominant and dominated heights
/// differ by exactly 2, so the schedule's heights are realized end to end).
#[test]
fn concurrent_pair_alternates_dominance_at_every_boundary() {
    for n in [4, 64] {
        let (v, w) = concurrent_pair(n);
        assert!(v.concurrent(&w), "the pair must be causally concurrent");
        assert_eq!(
            leaf_count(&(&v | &w)),
            n,
            "the join must keep one plateau per forked leaf"
        );
        assert_eq!(
            leaf_count(&(&v & &w)),
            n,
            "the meet must keep one plateau per forked leaf"
        );
        let two = uniform(2u8).rank();
        assert_eq!(v.distance(&w), two, "the schedule's heights are realized");
    }
}

/// `dense_suffix(p, d)` is canonical normal form at exactly `134d + 1812p + 4`
/// bits.
///
/// Its `min_ticks` is exactly the stored-base sum `d + p(2^608 + 2^288 + 2) +
/// 1` (the `d` term is the spine's turn leaves, so a spine-less generator fails
/// it).
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` dense-suffix bands in `tests/meter.rs` re-derive it at
/// meter scale, so this pin holds it at hand-checkable sizes.
#[test]
fn dense_suffix_decodes_canonically_at_predicted_length() {
    for (p, d) in [(1usize, 1usize), (5, 4), (40, 40)] {
        check_version(&dense_suffix(p, d), 134 * d + 1812 * p + 4);
        let expected = BigUint::from(d as u64)
            + BigUint::from(p as u64)
                * ((BigUint::ONE << 608usize) + (BigUint::ONE << 288usize) + 2u8)
            + 1u8;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            dense_suffix(p, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `dense_suffix_mate(p, d)` is canonical normal form at exactly `134d + 24p +
/// 4` bits.
///
/// Its `min_ticks` is exactly `d + 4p + 1`, and `dense_suffix(p, d)` dominates
/// it pointwise (the pair band's exact value legs rest on the dominance).
#[test]
fn dense_suffix_mate_decodes_canonically_at_predicted_length() {
    for (p, d) in [(1usize, 1usize), (5, 4), (40, 40)] {
        check_version(&dense_suffix_mate(p, d), 134 * d + 24 * p + 4);
        let ticks = crate::Ticks::from(d as u64 + 4 * p as u64 + 1);
        assert_eq!(
            dense_suffix_mate(p, d).version().min_ticks(),
            ticks,
            "the unit-block spine's stored-base sum is its minimum tick count"
        );
    }
    let a = dense_suffix(3, 3).version();
    let b = dense_suffix_mate(3, 3).version();
    assert!(
        a.rank().checked_sub(&b.rank()).is_some(),
        "the dense-suffix operand dominates its mate"
    );
    assert_eq!(
        a.lag(&b),
        crate::Rank::ZERO,
        "the dominating side lags by nothing"
    );
}

/// `wide_arming(w, d)` is canonical normal form at exactly `134d + 64w + 600`
/// bits.
///
/// Its `min_ticks` is exactly the stored-base sum `d + 2^(32w) + 2^288 + 2 +
/// 1`.
#[test]
fn wide_arming_decodes_canonically_at_predicted_length() {
    for (w, d) in [(10usize, 1usize), (12, 5), (40, 40)] {
        check_version(&wide_arming(w, d), 134 * d + 64 * w + 600);
        let expected =
            BigUint::from(d as u64) + (BigUint::ONE << (32 * w)) + (BigUint::ONE << 288usize) + 3u8;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            wide_arming(w, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `hoisted_window(w, d, t)` is canonical normal form at exactly `134d + 64w +
/// 4t + 600` bits.
///
/// Its `min_ticks` is exactly the stored-base sum `d + 2^(32w) + 2^288 + 2 +
/// 1`, *independent of the tail knob* — the tail's stored bases sum to the 1
/// its bottom leaf pair carries, exactly the wide-arming block terminal it
/// deepens — which is the family's whole design: the tail moves the settle
/// clusters' absolute positions and nothing else the fold's inputs denominate.
#[test]
fn hoisted_window_decodes_canonically_at_predicted_length() {
    for (w, d, t) in [(10usize, 1usize, 384usize), (12, 5, 448), (12, 5, 896)] {
        check_version(&hoisted_window(w, d, t), 134 * d + 64 * w + 4 * t + 600);
        let expected =
            BigUint::from(d as u64) + (BigUint::ONE << (32 * w)) + (BigUint::ONE << 288usize) + 3u8;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            hoisted_window(w, d, t).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count, and the \
             tail must not move it"
        );
    }
    // The tail leaves the fold's answer untouched too: rank agrees with the
    // wide-arming shape it deepens at every tail scale (the tail's leaves ride
    // the plateau for a vanishing extra area contribution — compare the
    // deepened family across its own tail doubling instead, where the deeper
    // tail's extra area halves away and the rank difference is exactly the
    // tail region's own sliver).
    let hoisted = hoisted_window(10, 2, 384).version();
    let deeper = hoisted_window(10, 2, 768).version();
    assert!(
        hoisted.rank().checked_sub(&deeper.rank()).is_some(),
        "a deeper tail only shrinks the tail sliver's area"
    );
}

/// Returns the boundary shapes' shared narrow value.
fn boundary_rung_ubig() -> BigUint {
    BigUint::from(5u8) << 64usize
}

/// Returns the boundary shapes' `w`-digit operand `5·2^(32(w−1))`.
fn boundary_wide_ubig(w: usize) -> BigUint {
    BigUint::from(5u8) << (32 * (w - 1))
}

/// `seam_plunge(k, r)` is canonical normal form at exactly
/// `(k + 1)(64r − 56) + 2` bits.
///
/// Its `min_ticks` is exactly the stored-base sum — the `k + 1` ascending
/// leaves over all-zero node bases and the zero plunge:
/// `(k + 1)·5·2^(32(r−1)) + 5·2^64·(k + 1)(k + 2)/2`. The assertion
/// ensures resource measurements describe the generated tree.
#[test]
fn descending_boundary_decodes_canonically_at_predicted_length() {
    for (k, r) in [(1usize, 5usize), (4, 5), (3, 7)] {
        let p = seam_plunge(k, r);
        check_version(&p, (k + 1) * (64 * r - 56) + 2);
        let expected = boundary_wide_ubig(r) * BigUint::from((k + 1) as u64)
            + boundary_rung_ubig() * BigUint::from(((k + 1) * (k + 2) / 2) as u64);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `seam_plunge_control(k, r)` is canonical normal form at exactly
/// `136k + 64r + 78` bits, and its stored wire differs from
/// `seam_plunge(k, r)`'s only in the final delta code.
///
/// Its `min_ticks` is exactly the stored-base sum `5·2^(32(r−1)) +
/// 5·2^64·(k + 2)` (the ascent carried on the bases, the terminal one rung
/// up); the wire-prefix identity lets the boundary band read the pair's
/// difference as the plunge's own propagation.
#[test]
fn descending_boundary_control_decodes_at_predicted_length() {
    for (k, r) in [(1usize, 5usize), (4, 5), (3, 7)] {
        let p = seam_plunge_control(k, r);
        check_version(&p, 136 * k + 64 * r + 78);
        let expected = boundary_wide_ubig(r) + boundary_rung_ubig() * BigUint::from((k + 2) as u64);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
        // The wire-prefix identity: the pair's stored streams agree byte for
        // byte up to the control's full length less its final code and
        // padding — asserted structurally instead of byte-wise here, by the
        // leaf heights: both trees walk the identical ascent.
        let plunge = seam_plunge(k, r).version();
        let control = p.version();
        let plunge_wire = plunge.encode();
        let control_wire = control.encode();
        // The shared prefix: topology and all but the last delta agree, so
        // the shorter stream's first bytes match the longer's (the final
        // codes differ in length, so compare up to the divergence).
        let shared = control_wire
            .iter()
            .zip(plunge_wire.iter())
            .take_while(|(c, p)| c == p)
            .count();
        assert!(
            shared * 8 + 200 >= control_wire.len() * 8,
            "the control's wire diverges from the plunge's more than one \
             final code early: {shared} shared bytes of {}",
            control_wire.len(),
        );
    }
}

/// `seam_stop(k)` is canonical normal form at exactly `164k + 266` bits.
///
/// Its `min_ticks` is exactly the stored-base sum `5·2^128 + (k − 1)·2^80 +
/// 5·2^64·k(k − 1)/2` — the descent node's base plus the `k` descending
/// leaves. The assertion ensures the boundary band describes the tree the generator
/// actually builds.
#[test]
fn stopping_boundary_decodes_canonically_at_predicted_length() {
    for k in [1usize, 5, 32] {
        let p = seam_stop(k);
        check_version(&p, 164 * k + 266);
        let expected = stopping_boundary_ticks(k);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// The boundary-stop shapes' shared stored-base sum: the pair differs only in
/// zero-base wrapping, so one closed form serves both pins.
fn stopping_boundary_ticks(k: usize) -> BigUint {
    (BigUint::from(5u8) << 128usize)
        + (BigUint::from((k - 1) as u64) << 80usize)
        + boundary_rung_ubig() * BigUint::from((k * (k - 1) / 2) as u64)
}

/// `seam_stop_control(k)` is canonical normal form at exactly `164k + 262`
/// bits, with the same stored-base sum as `seam_stop(k)`.
///
/// The control drops only the zero-based root and floor leaf, so its
/// `min_ticks` is unchanged — the removed boundary lives in the *walk's*
/// difference stack, never in the total.
#[test]
fn stopping_boundary_control_decodes_at_predicted_length() {
    for k in [1usize, 5, 32] {
        let p = seam_stop_control(k);
        check_version(&p, 164 * k + 262);
        let ticks = ticks_from_big(&stopping_boundary_ticks(k));
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `latent_ladder(w, k)` is canonical normal form at exactly
/// `k(64w − 56) + 64w − 48` bits.
///
/// Its `min_ticks` is exactly the stored-base sum `(k + 1)·5·2^(32(w−1)) +
/// 1 − k(k + 1)/2` (the parked pair's base and `(0, 1)` leaves, plus the
/// `k` ladder leaves one to `k` under the anchor) — pinned so the ladder
/// band reasons about the tree the generator actually builds.
#[test]
fn latent_ladder_decodes_canonically_at_predicted_length() {
    for (w, k) in [(3usize, 1usize), (4, 5), (10, 8)] {
        let p = latent_ladder(w, k);
        check_version(&p, k * (64 * w - 56) + 64 * w - 48);
        let expected = boundary_wide_ubig(w) * BigUint::from((k + 1) as u64) + BigUint::ONE
            - BigUint::from((k * (k + 1) / 2) as u64);
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            p.version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `plateau_puncture(w, d)` is canonical normal form at exactly `d(64w + 262) +
/// 4` bits.
///
/// The length derivation: `66d` spine levels at 2 bits, `d` turn leaves at
/// `64w` bits each (the plateau's exact `32w`-bit width, bit 0 clear, keeps its
/// gamma code at `2 · 32w` with the leaf flag), the bottom 1 leaf at 4 bits,
/// and `65d` trailing 0-leaves at 2 bits. Its `min_ticks` is exactly the
/// stored-base sum `d · x + 1` (the turn leaves all on the plateau plus the
/// bottom 1), and its exact rank realizes the answer-embedded product the
/// family exists for: `rank · 2^(66d) = 2 · x · y + 1` over the committed
/// factors, checked here through the public fold at hand-checkable sizes (the
/// `answer_embedded_product` pin in `tests/meter.rs` measures the cost at meter
/// scale; the query fold's differential suite pins the value against the
/// oracle, and its proptest pins the same embedding over arbitrary factors).
#[test]
fn plateau_puncture_decodes_canonically_at_predicted_length() {
    for (w, d) in [(10usize, 1usize), (12, 5), (40, 40)] {
        check_version(&plateau_puncture(w, d), d * (64 * w + 262) + 4);
        // The reduction's size premise, exact on the committed instance: the
        // STORED stream is `128w + 198d + 2` bits — `4·bits(x) + 3·bits(2y) +
        // 5`, the climb and plunge codes at `2·bits(x)` each plus 3 bits per
        // level — linear in the factors' widths even though the encoded
        // construction above is `Θ(d·w)` (it spells the plateau per turn). The
        // floor's funding argument divides the fold's cost by exactly this
        // stored size, so the premise is pinned beside the length it must not
        // drift from (the arbitrary-factor proptest beside the query fold pins
        // the same bound as an inequality).
        assert_eq!(
            plateau_puncture(w, d).version().encoded_bits(),
            (128 * w + 198 * d + 2) as u64,
            "the stored stream must stay linear in the factors' widths"
        );
        let (x, y) = plateau_puncture_factors(w, d);
        let expected = BigUint::from(d as u64) * &x + 1u8;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            plateau_puncture(w, d).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
        // The rank is exactly (2xy + 1) / 2^(66d).
        let numerator = ((&x * &y) << 1usize) + 1u8;
        assert_eq!(
            plateau_puncture(w, d).version().rank(),
            Rank::from_raw(numerator, (66 * d) as u64),
            "the exact rank is the plateau times the punctured turn mass"
        );
    }
}

/// `arming_train(n, w, g, alternate)` is canonical normal form at exactly
/// `n(g(2·band + 132) + 8·band + 16) + 2` bits, `band = 32w + ⌈log₂ n⌉ + 2`.
///
/// Its `min_ticks` is the mirrored leaf-value sum (the recurrence the generator
/// doc states): the swing, park, kicker, and promoting-freeze leaves per block
/// plus `g` plateau turns per window, over the bottom 0. The same-sign and
/// alternating trains share topology and differ only in the swings' directions.
#[test]
fn arming_train_decodes_canonically_at_predicted_length() {
    for (n, w, g, alt) in [
        (1usize, 19usize, 1usize, false),
        (2, 19, 1, true),
        (3, 20, 2, true),
        (4, 19, 3, false),
    ] {
        let band = 32 * w + (usize::BITS - n.leading_zeros()) as usize + 2;
        check_version(
            &arming_train(n, w, g, alt),
            n * (g * (2 * band + 132) + 8 * band + 16) + 2,
        );
        // The mirror: replay the generator's plateau recurrence and sum every
        // leaf value (the bottom and trailing leaves are all 0).
        let arm = BigUint::ONE << (32 * w);
        let kicker = BigUint::ONE << 288usize;
        let mut plateau = (BigUint::ONE << band) + (&arm << 1);
        let mut expected = BigUint::ZERO;
        for b in 0..n {
            expected += &plateau * BigUint::from(g as u64); // the window turns
            if alt && b % 2 == 1 {
                plateau -= &arm;
            } else {
                plateau += &arm;
            }
            for kick in [BigUint::ZERO, BigUint::ONE, kicker.clone(), BigUint::ONE] {
                plateau += kick;
                expected += &plateau;
            }
        }
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            arming_train(n, w, g, alt).version().min_ticks(),
            ticks,
            "the mirrored leaf-value sum is the family's minimum tick count"
        );
    }
}

/// `weight_comb(n)` is canonical normal form at exactly `202n − 4` bits.
///
/// Its `min_ticks` is exactly the stored-base sum `34n − 1` (the spine's `32n −
/// 1` unit leaves plus the block's `n` twos).
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` weight-comb band in `tests/meter.rs` re-derives it at
/// meter scale, so this pin holds it at hand-checkable sizes.
#[test]
fn weight_comb_decodes_canonically_at_predicted_length() {
    for n in [1usize, 4, 32] {
        check_version(&weight_comb(n), 202 * n - 4);
        let ticks = crate::Ticks::from(34 * n as u64 - 1);
        assert_eq!(
            weight_comb(n).version().min_ticks(),
            ticks,
            "the stored-base sum is the family's minimum tick count"
        );
    }
}

/// `freeze_parade(k)` is canonical normal form at exactly `1546k − 2` bits.
///
/// Its `min_ticks` is exactly
/// `(64k − 1) + 2^band + k·2^288 + (k/2)·log2(k)·(2^288 + 1) − (k − 1)(2^288 + 1) − 2^288`,
/// where `band = 290 + bitlen(k)`: the spine's unit leaves, then the block's `k`
/// left-leaf wide drops, its internal left children's half-minima differences
/// (`k/2` per level, each level's difference doubling from the pair stride),
/// and its root's absolute minimum.
///
/// The closed form is the family's independent semantic leg: the
/// `skyline_flatness` freeze-parade band in `tests/meter.rs` re-derives it at
/// meter scale, so this pin holds it at hand-checkable sizes.
#[test]
fn freeze_parade_decodes_canonically_at_predicted_length() {
    for k in [1usize, 2, 8] {
        check_version(&freeze_parade(k), 1546 * k - 2);
        let j = bitlen(k) - 1;
        let w = BigUint::ONE << 288usize;
        let stride = &w + BigUint::ONE;
        let expected = BigUint::from((64 * k - 1) as u64)
            + (BigUint::ONE << (290 + bitlen(k)))
            + BigUint::from(k as u64) * &w
            + BigUint::from((k / 2 * j) as u64) * &stride
            - BigUint::from((k - 1) as u64) * &stride
            - &w;
        let ticks = ticks_from_big(&expected);
        assert_eq!(
            freeze_parade(k).version().min_ticks(),
            ticks,
            "the printed-base sum is the family's minimum tick count"
        );
    }
}

/// `tooth_tail(g, m)` is canonical normal form at exactly `6m + 64g` bits per
/// operand.
///
/// Each operand's `min_ticks` is exactly the stored-base sum `m·h + 2^(32g)`
/// (`h` its unit height, 1 for `a` and 2 for `b`), `a` precedes `b` in the
/// causal order (the pair band's verdict leg rests on it).
#[test]
fn tooth_tail_decodes_canonically_at_predicted_length() {
    for (g, m) in [(1usize, 2usize), (2, 5), (9, 64)] {
        let (a, b) = tooth_tail(g, m);
        check_version(&a, 6 * m + 64 * g);
        check_version(&b, 6 * m + 64 * g);
        for (p, h) in [(&a, 1u64), (&b, 2u64)] {
            let expected = BigUint::from(m as u64 * h) + (BigUint::ONE << (32 * g));
            let ticks = ticks_from_big(&expected);
            assert_eq!(
                p.version().min_ticks(),
                ticks,
                "the stored-base sum is the operand's minimum tick count"
            );
        }
        assert_eq!(
            a.version().partial_cmp(&b.version()),
            Some(core::cmp::Ordering::Less),
            "b runs one tick above a everywhere except the shared terminal"
        );
    }
}

/// `stagger_comb(n, m, i)` is canonical normal form at exactly `m(4·log2(n) +
/// 6) − 2` bits for every operand index.
///
/// Each operand's `min_ticks` is exactly `m` (its stored-base sum: `m` unit
/// teeth over zero-based structure), and the whole population's join is the
/// constant-1 skyline — every
/// slot owned exactly once, the population-level witness that the teeth
/// interleave without overlap or gap.
#[test]
fn stagger_comb_decodes_canonically_at_predicted_length() {
    for (n, m) in [(2usize, 1usize), (4, 4), (16, 8)] {
        let levels = n.trailing_zeros() as usize;
        for i in 0..n {
            let p = super::stagger_comb(n, m, i);
            check_version(&p, m * (4 * levels + 6) - 2);
            let ticks = crate::Ticks::from(m as u64);
            assert_eq!(
                p.version().min_ticks(),
                ticks,
                "the stored-base sum is the operand's minimum tick count"
            );
        }
        let (versions, _) = super::stagger_population(n, m);
        let all: Version = versions.iter().map(Encoding::version).sum();
        assert_eq!(
            all,
            uniform(1u8),
            "the population's teeth tile the whole domain at height 1"
        );
    }
}

/// `stagger_id(n, m, i)` is canonical normal form at exactly `m(2·log2(n) + 4)
/// − 2` bits for every operand index.
///
/// The `n` operands are pairwise disjoint, and folding the whole population
/// back together reunites the seed — every slot owned exactly once, the id-side
/// witness of the same tiling the comb pin holds for the event side.
#[test]
fn stagger_id_decodes_canonically_at_predicted_length() {
    for (n, m) in [(2usize, 1usize), (4, 4), (16, 8)] {
        let levels = n.trailing_zeros() as usize;
        let parties: Vec<Party> = (0..n)
            .map(|i| check_party(&super::stagger_id(n, m, i), m * (2 * levels + 4) - 2))
            .collect();
        for (i, a) in parties.iter().enumerate() {
            for b in &parties[i + 1..] {
                assert!(a.is_disjoint(b), "distinct operands own distinct slots");
            }
        }
        let (_, ids) = super::stagger_population(n, m);
        let mut ids = ids
            .iter()
            .map(|p| Party::decode(&p.bytes[..]).expect("the population operands are canonical"));
        let mut acc = ids.next().expect("n >= 2");
        acc.join_all(ids)
            .expect("the population operands are pairwise disjoint");
        assert!(acc.is_seed(), "the population's slots tile the seed region");
    }
}

/// `meet_shade(d, k)` is the dominated-carrier population: the carrier first,
/// `k − 1` byte-identical plateau shades after, and the meet of the whole
/// population is the carrier itself, byte for byte.
///
/// The composition reuses two pinned shapes (`dense(d)`, `hugeleaf(2)`), so no
/// new closed form is owed; the pin here is the domination schedule the red
/// pin's cost argument rests on — the running meet never shrinks, so every step
/// re-walks the whole carrier.
#[test]
fn meet_shade_is_the_dominated_carrier() {
    for (d, k) in [(1usize, 2usize), (5, 4), (64, 16)] {
        let population = super::meet_shade(d, k);
        assert_eq!(population.len(), k, "one carrier plus k - 1 shades");
        assert_eq!(population[0], dense(d).version(), "the carrier leads");
        for shade in &population[1..] {
            assert_eq!(shade, &hugeleaf(2).version(), "every shade is the plateau");
        }
        let met = population[0].meet_all(&population[1..]);
        assert_eq!(
            met,
            dense(d).version(),
            "the shades dominate the carrier everywhere: the meet is the carrier"
        );
    }
}

proptest! {
    /// The ascending-cliff band guard admits exactly the documented frontier.
    ///
    /// At every width `b`, the boundary knob `k = 2^b − 2` — the deepest leaf's
    /// gamma code exactly filling the width-`b` band (`k + 2 = 2^b`) — builds a
    /// canonical family member through both callers at the closed-form
    /// `k(2b + 4) + 2` bits, while the first knob past the band, `k = 2^b − 1`
    /// (`k + 2 > 2^b`), panics as both callers' contracts state.
    #[test]
    fn ascend_cliff_band_guard_admits_exactly_the_documented_frontier(b in 2usize..=16) {
        let boundary = (1usize << b) - 2;
        let builds: [fn(usize, usize) -> Encoding; 2] = [ascend_cliff, ascend_cliff_plateau];
        for build in builds {
            check_version(&build(boundary, b), boundary * (2 * b + 4) + 2);
            let past = std::panic::catch_unwind(|| build(boundary + 1, b));
            prop_assert!(
                past.is_err(),
                "k + 2 > 2^b must panic: the ascent leaves the width-b code band"
            );
        }
    }
}
