//! Pins for the adversarial generators: each shape decodes, re-encodes
//! byte-identically, and has exactly its closed-form bit length.

use crate::codec;
use crate::{Party, Version};

use super::{
    alt_spine, bigroot, cancelling_chain, cliff_comb, cliff_fan, concurrent_pair, dense, harmonic,
    hugeleaf, id_spine, jump_comb, jump_pair, scattered_id, wide_tooth_comb, Packed,
};

/// Appended to the counter-comparison failures: the first cause to rule out
/// is a shared-process test runner, under which the process-global counters
/// bleed other tests' work into the reading being compared.
const ISOLATION_NOTE: &str = "note: the counter is process-global and meaningful only one \
     test per process: run under cargo nextest, not a shared-process cargo test";

/// Check an event-shape output: the construction stream has exactly the
/// closed-form `bits`, and it lifts through the transcoding bridge into a
/// version that survives a wire round-trip (canonicality of both codings).
fn check_version(p: &Packed, bits: usize) {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let v = p.version();
    let wire = v.encode();
    let back = Version::decode(&wire[..]).expect("a stored version's wire bytes decode");
    assert_eq!(back, v, "wire round-trip");
    assert_eq!(back.encode(), wire, "byte-identical re-encode");
}

/// Check an id-shape output: `decode` accepts it, the decoded party
/// re-encodes to the generated bytes (canonicality), and the live bit length
/// is exactly `bits`.
fn check_party(p: &Packed, bits: usize) -> Party {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let id = Party::decode(&p.bytes[..]).expect("generated shape is strict normal form");
    assert_eq!(id.encoded_bits(), p.bits, "decoded live bit length");
    assert_eq!(id.encode(), p.bytes, "byte-identical re-encode");
    id
}

/// The dense spine `S(d)` is canonical normal form at exactly `4d + 4` bits,
/// at both a small and a large depth.
#[test]
fn dense_decodes_canonically_at_predicted_length() {
    for d in [3, 1000] {
        check_version(&dense(d), 4 * d + 4);
    }
}

/// `bigroot(b, d)` is canonical normal form at exactly `2b + 4d + 8` bits,
/// including a root magnitude wide enough to spill machine-word gamma
/// decoding.
#[test]
fn bigroot_decodes_canonically_at_predicted_length() {
    for (b, d) in [(3, 2), (100, 50)] {
        check_version(&bigroot(b, d), 2 * b + 4 * d + 8);
    }
}

/// `hugeleaf(b)` is canonical normal form at exactly `2b + 2` bits, including
/// a magnitude wide enough to spill machine-word gamma decoding.
#[test]
fn hugeleaf_decodes_canonically_at_predicted_length() {
    for b in [1, 200] {
        check_version(&hugeleaf(b), 2 * b + 2);
    }
}

/// `cliff_comb(k, n)` is canonical normal form at exactly `n(2k + 10) + 2`
/// bits, and its preorder leaf values oscillate across the `2^k` boundary.
///
/// The sizes cover a tooth magnitude wide enough to spill machine-word gamma
/// decoding and a tooth count deep enough for the oscillation to dominate.
#[test]
fn cliff_comb_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 1), (3, 4), (200, 50)] {
        check_version(&cliff_comb(k, n), n * (2 * k + 10) + 2);
    }
    // The oscillation the family exists for: leaf values alternate
    // `2^k − 1 ↔ 2^k`, pinned on a hand-checkable size via the paper
    // notation (leaf values are absolute there).
    let p = cliff_comb(3, 2);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (7, 0, 1), (0, (7, 0, 1), 0))");
}

/// `jump_comb(k, n)` is canonical normal form at exactly
/// `(n − 1)(2k + 10) + 14` bits, and its preorder leaf values run `1, 2`,
/// jump to `2^k − 1`, then oscillate across the `2^k` boundary.
///
/// The sizes cover a cliff magnitude wide enough to spill machine-word
/// gamma decoding; the low-tooth-then-jump structure is pinned via the
/// paper notation on a hand-checkable size (leaf values are absolute
/// there).
#[test]
fn jump_comb_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 2), (3, 4), (200, 50)] {
        check_version(&jump_comb(k, n), (n - 1) * (2 * k + 10) + 14);
    }
    // The jump the family exists for: tooth (1, 0, 1), then teeth
    // (2^3 − 1, 0, 1).
    let p = jump_comb(3, 2);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (1, 0, 1), (0, (7, 0, 1), 0))");
}

/// `wide_tooth_comb(k, w, n)` is canonical normal form at exactly
/// `n(2k + 2w + 6) + 2` bits, and its preorder leaf values oscillate
/// `2^k − 2^w ↔ 2^k`.
///
/// The sizes cover teeth and cliffs wide enough to spill machine-word gamma
/// decoding, and the leaf-value oscillation is pinned via the paper
/// notation on a hand-checkable size (leaf values are absolute there).
#[test]
fn wide_tooth_comb_decodes_canonically_at_predicted_length() {
    for (k, w, n) in [(2, 1, 1), (3, 1, 4), (200, 100, 50)] {
        check_version(&wide_tooth_comb(k, w, n), n * (2 * k + 2 * w + 6) + 2);
    }
    // Teeth (2^3 − 2^1, 0, 2^1): leaf values oscillate 6 ↔ 8 across 2^3.
    let p = wide_tooth_comb(3, 1, 2);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (6, 0, 2), (0, (6, 0, 2), 0))");
}

/// `cliff_fan(k, n)` is canonical normal form at exactly `12n + 2k + 6`
/// bits, with every tooth's 12 stored bits crossing the `2^k` path-sum
/// boundary twice under one stored root magnitude.
///
/// The sizes cover a root magnitude wide enough to spill machine-word gamma
/// decoding, and the one-magnitude-over-cheap-teeth structure is pinned via
/// the paper notation on a hand-checkable size.
#[test]
fn cliff_fan_decodes_canonically_at_predicted_length() {
    for (k, n) in [(1, 1), (3, 4), (200, 50)] {
        check_version(&cliff_fan(k, n), 12 * n + 2 * k + 6);
    }
    // Root 2^3 − 1 = 7 over teeth (1, 0, 1): the fan's path sum enters
    // 2^3 at every tooth and leaves it again.
    let p = cliff_fan(3, 2);
    let v = p.version();
    assert_eq!(v.to_string(), "(7, (0, (1, 0, 1), (0, (1, 0, 1), 0)), 0)");
}

/// `cancelling_chain(k, n)` is canonical normal form at exactly
/// `n(2k + 10) + 2` bits, and its preorder leaf values oscillate `2^k ↔ 1`.
///
/// The sizes cover a peak magnitude wide enough to spill machine-word gamma
/// decoding, and the peak-to-1 oscillation is pinned via the paper notation
/// on a hand-checkable size.
#[test]
fn cancelling_chain_decodes_canonically_at_predicted_length() {
    for (k, n) in [(2, 1), (3, 4), (200, 50)] {
        check_version(&cancelling_chain(k, n), n * (2 * k + 10) + 2);
    }
    // Teeth (1, 2^3 − 1, 0): leaf values oscillate 8 ↔ 1.
    let p = cancelling_chain(3, 2);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (1, 7, 0), (0, (1, 7, 0), 0))");
}

/// The harmonic spine `H(d)` is canonical normal form at exactly `6d + 2`
/// bits, and its rank is exactly the closed form `(2^d − 1)/2^d`.
///
/// The closed form is pinned two ways: directly against the rendered
/// rational at hand-checkable depths, and at meter scale through the
/// telescoping witness `1 − rank(H(d)) = 1/2^d` — `checked_sub` against
/// the unit rank yields a one-bit numerator whose rendering is cheap at
/// any depth, so the pin stays exact where the direct string would be
/// thousands of digits.
#[test]
fn harmonic_decodes_canonically_at_predicted_length_and_rank() {
    for d in [1, 2, 3, 1000] {
        check_version(&harmonic(d), 6 * d + 2);
    }
    let p = harmonic(2);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (0, 0, 1), 1)");
    assert_eq!(v.rank().to_string(), "3/2^2");
    assert_eq!(harmonic(7).version().rank().to_string(), "127/2^7");
    // Meter scale: 1 − (2^d − 1)/2^d = 1/2^d, exact at any depth.
    let d = 4_096;
    let h = harmonic(d).version().rank();
    let one = Version::try_from(1u64)
        .expect("a one-tick version is valid")
        .rank();
    let gap = one
        .checked_sub(&h)
        .expect("H(d)'s rank is strictly under the unit rank");
    assert_eq!(gap.to_string(), format!("1/2^{d}"));
}

/// The alternating-binary spine `A(d)` is canonical normal form at exactly
/// `4d + 4` bits, with the internal child changing sides every level.
///
/// The direction alternation is pinned via the paper notation on a
/// hand-checkable depth: left at the root (even), right one level down
/// (odd).
#[test]
fn alt_spine_decodes_canonically_at_predicted_length() {
    for d in [1, 2, 3, 1000] {
        check_version(&alt_spine(d), 4 * d + 4);
    }
    let p = alt_spine(3);
    let v = p.version();
    assert_eq!(v.to_string(), "(0, (0, 0, (0, 0, 1)), 0)");
}

/// The stack-segment meter observes deep guarded recursion, resets to
/// zero, counts deterministically, and reads zero over a deep fill walk.
///
/// Determinism — the same count for the same descent repeated at the same
/// call depth — is what makes the meter envelope-able; the deep fill reads
/// zero because its explicit stacks put depth on the heap instead.
///
/// Every library walk is iterative, so the meter's liveness needs its own
/// witness: a test-local descent routed through `recurse::descend!` (the
/// same guard the test-only oracle bridge walks use) deep enough to outrun
/// the thread stack. Without that leg, the boards' all-zero segments column
/// could be a dead counter instead of a measured fact.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[test]
fn stack_segment_meter_counts_deterministically_and_resets() {
    use crate::recurse::descend;
    /// A guarded descent to `floor`, each frame holding a small
    /// stack-resident payload so its size is honest.
    fn dive(depth: usize, floor: usize) -> u64 {
        if depth == floor {
            return 1;
        }
        let pad = [depth as u64; 8];
        let below = descend!(depth + 1, dive(depth + 1, floor));
        below + core::hint::black_box(pad)[0]
    }
    const FLOOR: usize = 200_000;
    super::reset_stack_segments();
    core::hint::black_box(dive(0, FLOOR));
    let first = super::stack_segments();
    assert!(
        first > 0,
        "a depth-200000 guarded descent must grow the stack"
    );
    super::reset_stack_segments();
    assert_eq!(
        super::stack_segments(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    core::hint::black_box(dive(0, FLOOR));
    assert_eq!(
        super::stack_segments(),
        first,
        "identical descents at identical call depth grow identical segments: {ISOLATION_NOTE}"
    );

    // The conversion ratchet: the fill walk pairs a deep spine on BOTH
    // sides — exactly the descent that once grew the stack — and must now
    // read zero, its depth on explicit heap stacks the heap meter prices.
    let v = dense(50_000).version();
    let id = Party::decode(&id_spine(50_000, false).bytes[..]).expect("id spine decodes");
    super::reset_stack_segments();
    let mut t = v.clone();
    t.tick(&id);
    assert_eq!(
        super::stack_segments(),
        0,
        "the iterative fill walk grows no stack segments: {ISOLATION_NOTE}"
    );
}

/// The limb meter observes arithmetic width, resets to zero, and reads the
/// same count for the same operation repeated (determinism is what makes it
/// envelope-able); doubling a decoded magnitude grows the count.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[cfg(feature = "limb-meter")]
#[test]
fn limb_meter_counts_deterministically_and_resets() {
    // Wide-gamma decode is the arithmetic-width worst case: the whole input
    // is one code, so the decoded value's width is the input's bit length.
    let count_decode = |b: usize| {
        let p = hugeleaf(b);
        super::reset_limb_ops();
        let _ = p.version();
        super::limb_ops()
    };
    let first = count_decode(10_000);
    assert!(first > 0, "a spilled-gamma decode must count limb work");
    super::reset_limb_ops();
    assert_eq!(
        super::limb_ops(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    assert_eq!(
        count_decode(10_000),
        first,
        "identical operations count identical limb work: {ISOLATION_NOTE}"
    );
    assert!(
        count_decode(20_000) > first,
        "a wider magnitude must count more limb work: {ISOLATION_NOTE}"
    );
}

/// The scan meter observes packed-stream traversal, resets to zero, and
/// reads the same count for the same operation repeated.
///
/// Determinism is what makes it envelope-able, and its floor is live — a
/// strict decode scans every live bit at least once — so a ceiling
/// asserted over it can never pass vacuously at zero.
///
/// The counter is process-global, so the repeat-run comparison is
/// meaningful under nextest's one-test-per-process isolation (this
/// workspace's runner).
#[cfg(feature = "scan-meter")]
#[test]
fn scan_meter_counts_deterministically_and_resets() {
    // A strict id decode reads each live bit exactly once through the
    // sequential cursor, so the count has both a floor and an exact
    // expectation.
    let count_decode = |d: usize| {
        let p = id_spine(d, false);
        super::reset_scan_bits();
        let _ = Party::decode(&p.bytes[..]).expect("id spine decodes");
        (super::scan_bits(), p.bits as u64)
    };
    let (first, bits) = count_decode(10_000);
    assert!(
        first >= bits,
        "a strict decode of {bits} live bits scanned only {first}: \
         the sequential cursor is not recording: {ISOLATION_NOTE}"
    );
    super::reset_scan_bits();
    assert_eq!(
        super::scan_bits(),
        0,
        "reset returns the meter to zero: {ISOLATION_NOTE}"
    );
    assert_eq!(
        count_decode(10_000).0,
        first,
        "identical operations scan identical bits: {ISOLATION_NOTE}"
    );
    assert!(
        count_decode(20_000).0 > first,
        "a longer stream must scan more bits: {ISOLATION_NOTE}"
    );

    // The write side is live too: joining two disjoint spines writes the
    // joined tree through the id builder, so the count covers reads of
    // both operands plus at least the output's own bits.
    let pa = id_spine(1_000, false);
    let pb = id_spine(1_000, true);
    let mut a = Party::decode(&pa.bytes[..]).expect("id spine decodes");
    let b = Party::decode(&pb.bytes[..]).expect("id spine decodes");
    super::reset_scan_bits();
    a.join(b).expect("the divert arms are disjoint");
    let joined = super::scan_bits();
    assert!(
        joined as usize >= a.encoded_bits(),
        "a join that wrote {} output bits recorded only {joined} scan bits: \
         the id builder is not recording its writes: {ISOLATION_NOTE}",
        a.encoded_bits(),
    );
}

/// `I(d, divert)` is canonical normal form at exactly `2d + 2` bits for both
/// divert arms, and the two arms own disjoint regions (the property that
/// drives two-operand id walks to full lockstep depth).
#[test]
fn id_spine_decodes_canonically_at_predicted_length() {
    for d in [1, 500] {
        let a = check_party(&id_spine(d, false), 2 * d + 2);
        let b = check_party(&id_spine(d, true), 2 * d + 2);
        assert!(a.is_disjoint(&b), "divert arms own disjoint regions");
    }
}

/// `Z(e)` is canonical normal form at exactly `6e + 2` bits, and projecting
/// a comb through it keeps a wide magnitude per kept tooth: the projected
/// output out-scales the scattered party's own bits.
///
/// The overlap claim is what the generator exists for — the owned left
/// subtrees sit at the comb's tooth positions — so a projection that came
/// back near-empty would mean the shapes no longer align.
#[test]
fn scattered_id_decodes_canonically_at_predicted_length() {
    for e in [1, 500] {
        check_party(&scattered_id(e), 6 * e + 2);
    }
    let (k, n) = (64, 16);
    let comb = cliff_comb(k, n).version();
    let party =
        Party::decode(&scattered_id(n / 2).bytes[..]).expect("scattered id is strict normal form");
    let projected = (&comb / &party).to_version();
    assert!(
        projected.encoded_bits() >= (n / 2) * k,
        "projection through the scattered id must keep a wide magnitude per kept tooth \
         (got {} bits from {} teeth of {} bits)",
        projected.encoded_bits(),
        n,
        k
    );
}

/// The leaf count of a stored version's skyline stream, by one iterative
/// topology walk (payload codes skipped unread).
fn leaf_count(v: &Version) -> usize {
    use codec::BitCursor;
    let all = codec::bytes_as_bits(v.as_bytes());
    let bits = &all[..v.encoded_bits()];
    let mut cur = codec::DsiCursor::new(bits);
    let mut pending = 1usize;
    let mut leaves = 0usize;
    while pending > 0 {
        pending -= 1;
        if cur.read_bit().expect("a stored stream is canonical") {
            cur.skip_int().expect("a stored stream is canonical");
            leaves += 1;
        } else {
            pending += 2;
        }
    }
    leaves
}

/// `JP(k, m, d)` is canonical normal form at its closed-form bit
/// lengths, and its overlays realize the interleave the family exists
/// for.
///
/// The lengths: exactly `132d + m(2k + 14) + 2` bits (teeth) and
/// `132d + 14m + 2k + 2` bits (band). The overlays: the meet keeps both
/// band leaves per tooth and both gap leaves per level (4 leaves per
/// comb level — a cheap code one fold behind every wide difference
/// crest), while the join collapses every comb level to its two
/// plateaus (the band shades every gap): the wide crests live in the
/// meet-side overlay alone.
#[test]
fn jump_pair_decodes_canonically_at_predicted_lengths_and_interleaves() {
    for (k, m, d) in [(3, 1, 1), (400, 8, 2)] {
        let (a, b) = jump_pair(k, m, d);
        check_version(&a, 132 * d + m * (2 * k + 14) + 2);
        check_version(&b, 132 * d + 14 * m + 2 * k + 2);
        let (a, b) = (a.version(), b.version());
        let spine_leaves = super::JUMP_PAIR_DIGIT_STRIDE * d;
        assert_eq!(
            leaf_count(&(&a & &b)),
            spine_leaves + 4 * m + 1,
            "the meet must keep the band and gap interleave whole"
        );
        assert_eq!(
            leaf_count(&(&a | &b)),
            spine_leaves + 2 * m + 1,
            "the join must collapse each comb level to its two plateaus"
        );
        // The valuation identity, on the public surface: the pair's
        // distance is its two lags' sum (rank modularity).
        let d1 = a.lag(&b);
        let d2 = b.lag(&a);
        assert_eq!(a.distance(&b), &d1 + &d2, "distance is the lags' sum");
    }
}

/// `CP(n)` builds two genuinely concurrent organic versions that switch
/// sides at every overlay boundary.
///
/// The join and the meet both keep one plateau per forked leaf — every
/// one of the `n − 1` overlay boundaries a side switch — and the
/// distance is the integer rank 2 at every `n` (each leaf's dominant
/// and dominated heights differ by exactly 2, so the schedule's heights
/// are realized end to end).
#[test]
fn concurrent_pair_alternates_dominance_at_every_boundary() {
    for n in [4, 64] {
        let (v, w) = concurrent_pair(n);
        assert!(v.concurrent(&w), "the pair must be causally concurrent");
        assert_eq!(
            leaf_count(&(&v | &w)),
            n,
            "the join must keep one plateau per forked leaf"
        );
        assert_eq!(
            leaf_count(&(&v & &w)),
            n,
            "the meet must keep one plateau per forked leaf"
        );
        let two = Version::try_from(2u64)
            .expect("a small integer version is valid")
            .rank();
        assert_eq!(v.distance(&w), two, "the schedule's heights are realized");
    }
}
