//! Pins for the adversarial generators: each shape decodes, re-encodes
//! byte-identically, and has exactly its closed-form bit length.

use crate::{Party, Version};

use super::{bigroot, dense, hugeleaf, id_spine, Packed};

/// Check an event-shape output: `decode` accepts it, the decoded version
/// re-encodes to the generated bytes (canonicality), and the live bit length
/// is exactly `bits`.
fn check_version(p: &Packed, bits: usize) {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let v = Version::decode(&p.bytes[..]).expect("generated shape is strict normal form");
    assert_eq!(v.encoded_bits(), p.bits, "decoded live bit length");
    assert_eq!(v.encode(), p.bytes, "byte-identical re-encode");
}

/// Check an id-shape output: `decode` accepts it, the decoded party
/// re-encodes to the generated bytes (canonicality), and the live bit length
/// is exactly `bits`.
fn check_party(p: &Packed, bits: usize) -> Party {
    assert_eq!(p.bits, bits, "closed-form bit length");
    let id = Party::decode(&p.bytes[..]).expect("generated shape is strict normal form");
    assert_eq!(id.encoded_bits(), p.bits, "decoded live bit length");
    assert_eq!(id.encode(), p.bytes, "byte-identical re-encode");
    id
}

/// The dense spine `S(d)` is canonical normal form at exactly `4d + 4` bits,
/// at both a small and a large depth.
#[test]
fn dense_decodes_canonically_at_predicted_length() {
    for d in [3, 1000] {
        check_version(&dense(d), 4 * d + 4);
    }
}

/// `bigroot(b, d)` is canonical normal form at exactly `2b + 4d + 8` bits,
/// including a root magnitude wide enough to spill machine-word gamma
/// decoding.
#[test]
fn bigroot_decodes_canonically_at_predicted_length() {
    for (b, d) in [(3, 2), (100, 50)] {
        check_version(&bigroot(b, d), 2 * b + 4 * d + 8);
    }
}

/// `hugeleaf(b)` is canonical normal form at exactly `2b + 2` bits, including
/// a magnitude wide enough to spill machine-word gamma decoding.
#[test]
fn hugeleaf_decodes_canonically_at_predicted_length() {
    for b in [1, 200] {
        check_version(&hugeleaf(b), 2 * b + 2);
    }
}

/// The stack-segment meter observes deep recursion, resets to zero, and reads
/// the same count for the same traversal repeated at the same call depth
/// (determinism is what makes it envelope-able).
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[test]
fn stack_segment_meter_counts_deterministically_and_resets() {
    // Comparison recurses on depth; decode itself parses iteratively and
    // must not show up in the meter.
    let p = dense(50_000);
    let v = Version::decode(&p.bytes[..]).expect("dense spine decodes");
    super::reset_stack_segments();
    let first = {
        let _ = v.partial_cmp(&Version::new());
        super::stack_segments()
    };
    assert!(first > 0, "a depth-50000 comparison must grow the stack");
    super::reset_stack_segments();
    assert_eq!(
        super::stack_segments(),
        0,
        "reset returns the meter to zero"
    );
    let _ = v.partial_cmp(&Version::new());
    assert_eq!(
        super::stack_segments(),
        first,
        "identical traversals at identical call depth grow identical segments"
    );
}

/// The limb meter observes arithmetic width, resets to zero, and reads the
/// same count for the same operation repeated (determinism is what makes it
/// envelope-able); doubling a decoded magnitude grows the count.
///
/// The counter is process-global, so the repeat-run comparison is meaningful
/// under nextest's one-test-per-process isolation (this workspace's runner).
#[cfg(feature = "limb-meter")]
#[test]
fn limb_meter_counts_deterministically_and_resets() {
    // Wide-gamma decode is the arithmetic-width worst case: the whole input
    // is one code, so the decoded value's width is the input's bit length.
    let count_decode = |b: usize| {
        let p = hugeleaf(b);
        super::reset_limb_ops();
        let _ = Version::decode(&p.bytes[..]).expect("hugeleaf decodes");
        super::limb_ops()
    };
    let first = count_decode(10_000);
    assert!(first > 0, "a spilled-gamma decode must count limb work");
    super::reset_limb_ops();
    assert_eq!(super::limb_ops(), 0, "reset returns the meter to zero");
    assert_eq!(
        count_decode(10_000),
        first,
        "identical operations count identical limb work"
    );
    assert!(
        count_decode(20_000) > first,
        "a wider magnitude must count more limb work"
    );
}

/// `I(d, divert)` is canonical normal form at exactly `2d + 2` bits for both
/// divert arms, and the two arms own disjoint regions (the property that
/// drives two-operand id walks to full lockstep depth).
#[test]
fn id_spine_decodes_canonically_at_predicted_length() {
    for d in [1, 500] {
        let a = check_party(&id_spine(d, false), 2 * d + 2);
        let b = check_party(&id_spine(d, true), 2 * d + 2);
        assert!(a.is_disjoint(&b), "divert arms own disjoint regions");
    }
}
